### ISSUE TITLE
Understanding Scenarios

### ISSUE THREAD

**Issue by terfani** [pywr/pywr#1000]
I need help understanding the scenarios please. 

Suppose that my JSON has a sceanrio of the form: 

```
"scenarios": [
        {
            "name": "weather",
            "size": 5
        }
    ],

"nodes": [
        {
            "name": "supply",
            "type": "Input",
            "max_flow": "supply_flow",
            "cost": 3
        },
"parameters": {
      "supply_flow": {
      "type": "dataframe",
      "url": "flow.csv",
      "scenario": "weather",
      "parse_dates": true,
      "dayfirst": true,
      "index_col": 0,
    }

"scenario_combinations": [
    [
      3
    ]

```
my weather flow data is in a csv file:
```
                 0      1      2      3       4
timestamp                                      
2025-01-01   63.80  66.82  80.97  46.95   53.25
2025-01-02   61.83  64.32  78.48  45.53   51.62
2025-01-03   59.93  62.16  76.10  44.17   50.02
2025-01-04   58.13  60.21  73.77  42.85   48.48
2025-01-05   56.37  58.31  71.50  41.56   47.00
```
The above code in JSON should give me the thrid sceanrio? right? How can I access that what it is imported from the JSON for simulation use? I tried:

```
A = [i for i in model.nodes]
B = A[0].max_flow
print(B.dataframe)
```

But this seems to give me the full dataframe. and then I tried B.sceanrio. but I cannot access the value? Could you help me fetch the scenario being simulated as an output of the model?

Also on another note, when I change the size in the above JSON to 1, 5, 100, 10000, nothing changes in the B.dataframe. Can size be dropped? Is not B.dataframe the value imported by scenario combination?

**Comment by jetuk** [comment]
> The above code in JSON should give me the thrid sceanrio?

It'll give you the 4th entry. "scenario_combinations" uses zero-based indexing.

You need to run the model and then only the 4th scenario will be in any recorders you've specified.

```python
model.run()
flow_in_final_timestep = model.nodes["supply"].flow[0]
print(f"The flow in the final timestep of the 4th scenario is: {flow_in_final_timestep}")
```

```python
B = A[0].max_flow
print(B.dataframe)
```
This, as you've discovered, is accessing your input data.

> Is not `B.dataframe` the value imported by scenario combination?

The current implementation loads the entire dataset regardless if it is used. I believe it does sub-sample it to the required dataset prior to simulation, but that is not accessible from Python. Nonetheless the original dataframe is left in `.dataframe`.

**Comment by jetuk** [comment]
I assume this answered the question.
