### ISSUE TITLE
Memory allocation error with multiprocessing

### ISSUE THREAD

**Issue by s-simoncelli** [pywr/pywr#1008]
Hello,

when I try to run different Pywr instances with Python multiprocessing, I get the following error from the solver:

```
glp_free: memory allocation error
Error detected in file ..\src\env\alloc.c at line 72
```

This occurs only when a certain number of parallel processes run simultaneously. Below 20 instances no error is reported. Above that number only a certain number of instances of the model fail. 

Each Python process initialises and runs its Pywr instance from a dictionary using v 1.5.3 on a Window machine with 100 GB of free RAM memory. This seems to be related to #819

**Comment by jetuk** [comment]
@s-simoncelli did you solve your problem?

**Comment by s-simoncelli** [comment]
No. Each process initialises it’s own model instance by using the same serialised object but with different values for a parameter. My code is pretty simple, I’ll paste it on Monday when I’m back to work

Thanks for your help.


________________________________

**Comment by jetuk** [comment]
Is this run inside a function? I suspect what is happening is that the `model` instance goes out of context at the end of the function, but it is not explicitly deallocated then because of the garbage collector. Try adding this after the model run:

```python
    # run the model
    model = Model.load(self.model_dict)
    model.run()

    # Force garbage collection to ensure GLPK is deallocated before the next simulation
    # Otherwise it could be garbage collected during a following simulation.
    import gc
    gc.collect()
```

**Comment by jetuk** [comment]
I assume also you are using a process pool? And that this is coming from reusing the same process to run multiple models. You might also fix it by making it so each process only runs one model:

```
multiprocessing.pool.Pool(maxtasksperchild=1)
```
See here for more info: https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool

**Comment by s-simoncelli** [comment]
Yes I'm using the Pool class

        with Pool(processes=self.config.max_workers) as pool:
            pool.imap(partial(PywrInstance, base_model), config.replicates_to_run)

Each process copies the `base_model` dictionary. Even with the garbage collector, the problem persists. I noticed that while some processes fails, Pywr manages to save the H5 files but some of them contain empty numpy arrays for some keys.

Do you think it is how Windows handles the GPLK memory? May using Linux solve the issue?

**Comment by jetuk** [comment]
Does this help?

```python
with Pool(processes=self.config.max_workers, maxtasksperchild=1) as pool:
        pool.imap(partial(PywrInstance, base_model), config.replicates_to_run)
```
Is `PywrInstance` a function that runs the code you pasted earlier? 

I'll have to see if I can replicate this problem. The empty H5 data is probably expected if the process crashed while the file was open and the arrays initialised but before they were populated. The randomness of it makes me think it is the garbage collector because that can do its collection at any time. 

Perhaps this is a Windows only bug, but it would be good if we can reduce it to a minimal failing example (with no sensitive data) that we can test.

**Comment by s-simoncelli** [comment]
Sorry for the late reply, but I had time to work on this only yesterday. I solved the issue by extending the Python Process class. The sub class runs the Pywr instance using Queue to handle the different tasks. This doesn't trigger the memory allocation error anymore on WIn10.

Thanks for your tips
