### ISSUE TITLE
Dropping PyTables dependency?

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#1011]
The PyTables project hasn't had a release for a couple of years and they do not produce wheels for Windows for Python 3.9 or above. There's still some activity in the project which we could contribute to. Alternatively, we can consider dropping PyTables and using h5py instead. This would require some changes to the relevant parameter and recorder instances. 

Any thoughts on this?

**Comment by Batch21** [comment]
I'd support a move to using h5py. Scanning the pytables repo, it seems unlikely that there will be a release soon. A few other packages have also made the decision to drop pytables in favour of h5py.

Based on this [description](http://www.pytables.org/FAQ.html#how-does-pytables-compare-with-the-h5py-project) of the differences, there likely wouldn't be much downside to switching other than the time needed to make the changes.

**Comment by jetuk** [comment]
Agreed, we don't use the "database" features of PyTables. I'd be happy with the switch also.

**Comment by jetuk** [comment]
The next question is whether we can update `TablesRecorder` to use h5py transparently to users. This would be the preference but some of the keyword arguments are possibly PyTables specific.

**Comment by jetuk** [comment]
Looks like there's been some movement in the PyTables project to start publishing wheels for the main OS and architectures.

**Comment by jetuk** [comment]
PyTables has not released v3.7.0 with wheels for all our supported targets. I suggest we close this for now as there's not really a need to change it and no-one has time to work on it. 

In future I'd be happy to merge a h5py based recorder.
