### ISSUE TITLE
solver argument overwritten in Model.load

### ISSUE THREAD

**Issue by pmslavin** [pywr/pywr#1042]
During the model loading process, after the call to `Model.loads()` returns the subsequent call to `Model._load_from_dict()` on `_model.pyx:295` has the kwarg `solver=None` which overwrites any solver argument passed to `Model.load()`.

https://github.com/pywr/pywr/blob/e3bc628cb0ff7bebfd91a2273e97132d720a8907/pywr/_model.pyx#L295

As a result, the solver defaults to the first in the `solver_registry` unless either the env variable or model keyword is supplied.

**Comment by jetuk** [comment]
@pmslavin thanks for this. I will investigate.

**Comment by jetuk** [comment]
@pmslavin proposed fix in #1043. If you have time could you confirm if it solves your issue?

**Comment by pmslavin** [comment]
I can confirm that this fixes the issue I encountered (explicitly specifying `solver=solver_name`  to `Model.load()`), but I think the tests for this may have "passed" because their class in `test_core.py` is `SpecifyingSolver` rather than `TestSpecifyingSolver` and weren't collected as a consequence.

If the tests there are run, I get a couple of errors in the `test_load_solver_with_json` and `test_load_override_solver_in_json` cases.  The first of these is that `Model.load()` tries to pop `name` from `solver_data` without a default (L323), and this hasn't been added by the test.  Second is that  (L324) `solver_args` then ends up set to the whole of `solver_data`, which arrives in `Model.__init__()` and L103 then passes this to the solver ctor, then via this to the solver base class ctor, which for the case of the  `CythonGLPKEdgeSolver` passes it on to the base class ctor as an unexpected keyword, so I suspect that the L324 above isn't the intention.

The other new tests succeed and this seems to solve the original issue.

**Comment by jetuk** [comment]
> their class in test_core.py is SpecifyingSolver rather than TestSpecifyingSolver and weren't collected as a consequence.

Thanks for spotting this!
