### ISSUE TITLE
Implement a HiGHS based solver

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#1050]
A high performance LP solver with a GPL compatible licence. 

https://github.com/ERGO-Code/HiGHS

This might be a good alternative to GLPK for larger models.

**Comment by wdvichete84** [comment]
This optimizer is already working on PYWR?

**Comment by jetuk** [comment]
Not it is not. Do you have a reason for using it over the existing GLPK implementation?

**Comment by wdvichete84** [comment]
No specific reason. I'm building a large model. So far, so good.

**Comment by jetuk** [comment]
You'll want to try out the existing "glpk-edge" solver if it is a big model.

**Comment by wdvichete84** [comment]
It´s seems not a large model. 
The model will be around 60 to 90 nodes. Thanks for let me know about the "glpk-edge" solver.

**Comment by jetuk** [comment]
The HiGHS solver has been implemented in Pywr-next.
