### ISSUE TITLE
Error with DivisionParameter

### ISSUE THREAD

**Issue by ahamilton144** [pywr/pywr#1054]
Hi there, I am trying to build a model that includes a DivisionParameter. However, when I try to load the model, I get an error with a long traceback that ends like this:

`  File "pywr/parameters/_parameters.pyx", line 2159, in pywr.parameters._parameters.load_parameter
  File "pywr/parameters/_parameters.pyx", line 1680, in pywr.parameters._parameters.DivisionParameter.load
KeyError: 'numerator'`

I assume this is a Cython slots error, since self.numerator and self.denominator are defined in `_parameters.pyx, DivisionParameter.__init__()`, but not declared in the pxd file? I'm unsure what the proper way to handle properties in Cython is. I tried two fixes: (1) declaring numerators & denominators in the pxd file, and (2) declaring `cdef dict __dict__` in the pxd file. However, both gave me the same error:

`ValueError: pywr.parameters._parameters.DivisionParameter size changed, may indicate binary incompatibility. Expected 336 from C header, got 328 from PyObject`

Not sure if this is part of the same error, or an entirely different problem... I appreciate any help you can provide.

Thank,
Andrew

**Comment by jetuk** [comment]
How are you building the model? Using the Python API or from a JSON file? From the traceback it looks like from JSON. The error is indicating you are missing the "numerator" key in the JSON definition for this parameter type. It should look something like this:

```json
"my-parameter": {
  "type": "division",
  "numerator": "my-numerator-parameter",
  "denominator": "my-denominator-parameter"
}

**Comment by ahamilton144** [comment]
Ok wow, I was overthinking that. Yes this works. I had assumed the numerator and denominator belonged in a "parameters" list like the aggregated parameters, but this makes sense now. Thanks!

**Comment by jetuk** [comment]
No problem. 

> ValueError: pywr.parameters._parameters.DivisionParameter size changed, may indicate binary incompatibility. Expected 336 from C header, got 328 from PyObject

FYI this error is often caused by a Cython extension's dependent extension's definitions being modified. This requires the dependent extension to be recompiled.
