### ISSUE TITLE
Parameter equal to Node values

### ISSUE THREAD

**Issue by aiduran** [pywr/pywr#1056]
Hi, I was wondering if there is a parameter which is equal to the value of a node. For example, I want to have a parameter that is the storage of my reservoir and it's equivalent to the storage values of this node. I mean, If I recoder the node and the parameter the values will be the same. 

Thanks in advance.

**Comment by jetuk** [comment]
You're correct this does not currently exist. It would not be too difficult to and would make re-using some parameters much easier with storage nodes without requiring a specific storage node version. I may find time to implement this over the next few days.

**Comment by aiduran** [comment]
Hello,  does it was implemented? I will help to do it, but it's not easy to me

**Comment by jetuk** [comment]
I'm afraid not yet.

**Comment by jetuk** [comment]
@aiduran I have opened a pull request that implements this parameter: #1057 

If it gets merged it'll be available in the next version of Pywr, or you can install the development version from that branch for testing. Any testing would be gratefully received.

**Comment by aiduran** [comment]
Thank you James, sorry for asking, but how I can upgrade the new version of pywr?

**Comment by jetuk** [comment]
It's not released yet. We've merged the pull request but need to release a new version. We'll probably merge #1041 before doing the release. Alternatively you can try to compile Pywr from the master branch source code. There are some instructions in the documentation.
