### ISSUE TITLE
Additional question based on #1053

### ISSUE THREAD

**Issue by wdvichete84** [pywr/pywr#1063]
Hi @jetuk, according to #1053 the input discharges unit must be in m3/day.

However, if I´m using the month time step, and I have median monthly discharge input in m3/s , is the input discharge unit must be in m3 in a month (m3/month)? . 
is that correct?

In order to clarify the units used by PYWR, let me know if my understand about the units bellow are correct:
**_- Time step = 1_**
Input discharge = m3/day;
Output = m³/day;
Storage volume = m3;
Storage area = m2;
Turbine discharge = m3/day

**_Time step = M_**
Input discharge = m3/month;
Output = m3/month;
Storage volume = m3
Storage area = m2;
Turbine discharge = m3/month

are the units above correct?

**Comment by jetuk** [comment]
Hi @wdvichete84, even in the the case with non-daily timestep make sure the units are V/day. Pywr will multiply by the time-step length in days when undertaking the delta volume calculations. I.e., you should enter your monthly daily averaged flows.
