### ISSUE TITLE
Catchment is inefficient

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#107]
Attaching a `Parameter` to `Catchment.flow` causes `Parameter.before` et al to be called twice. Once for the `min_flow` and once for `max_flow`. This is unexpected before and can cause unexpected results if `Parameter.before` is written with the expectation of only being called once per time-step.

**Comment by snorfalorpagus** [comment]
Is the solution to this a caching parameter or a modification to `Catchment`?

**Comment by jetuk** [comment]
It's mostly a problem is `Parameter` is stateful and `Parameter.before` should be called once per time-step. The Catchmod parameter has this issue. I solved it there by putting a check in `Parameter.before` to ensure it was a different time-step. 

We ideally need a mechanism to guarantee `before` and `after` are only called once per time-step. Assuming, of course, if this our intended behaviour?

**Comment by snorfalorpagus** [comment]
The `Parameter` objects now have `parents` and `children` attributes. Rather than calling the `before` and `after` methods recursively it should be possible to create a dependency tree in `Model.setup`. This can be flattened to a list, then called in a loop in `Model.before` and `Model.after` directly.

**Comment by snorfalorpagus** [comment]
I hadn't appreciated that you were thinking of improving this at the solver level (i.e. a `Catchment` would only have one row in the LP (flow == X), instead of two (flow <= max_flow, flow >= min_flow). This probably isn't too difficult but I suspect will involve more LOC than you might expect.

**Comment by jetuk** [comment]
Actually I think our current code does this already because it sets the row to fixed (at least in the GLPK solver).

https://github.com/pywr/pywr/blob/master/pywr/solvers/glpk.pxi#L45
