### ISSUE TITLE
Question: return flow from output nodes

### ISSUE THREAD

**Issue by ccalvocm** [pywr/pywr#1077]
Greetings,

¿Does anybody know if there's an option to link an Output node (representing water demand) and link it downstream other nodes to simulate return flows from unused demands?.

Thanks in advance.
Kind regards,

**Comment by jetuk** [comment]
If you need a proportional return flow then you can add an `Input` node for the returns. Then add an `AggregatedNode` which links the flow through the `Output` and `Input` nodes at a given ratio. Does this help?

**Comment by ccalvocm** [comment]
@jetuk Thank you, that suits me.

Best regards.
