### ISSUE TITLE
Segmentation fault error!

### ISSUE THREAD

**Issue by Jmiguel17** [pywr/pywr#1082]
Hi, I'm running an optimisation problem using mpi; however, after some function evaluation (FE), the process stops leaving a "Segmentation fault error". I have been reading, and maybe it is a memory error.

1. Is it possible that memory use increases during the optimisation process, or is memory usage stable? 
2. Should I add a `reset.model()` to clear the memory between every FE?
3. Is there another method to clear the memory, or definitely do you think this is not a problem with the memory?

Thanks

**Comment by jetuk** [comment]
I think we'll need some more information here. Can you see process memory increasing a lot before the crash? I believe the MOEA wrappers (unless you are using your own) call `model.reset()` already. It's very difficult to know what is the cause without further information. 

Are you using the latest version of Pywr (> 1.17) that includes the NaN handling on the solver interface? Can you tell if it is a particular set of variables that cause the problem? E.g. a division by zero not being caught in Cython?

I'm not sure how your MPI is working, but note that GLPK is not thread-safe (unless you've specifically built the re-entrant version).

The only really way to debug this will be to figure out a reproducible test case and then use a debugger to find the cause of the fault.

**Comment by Jmiguel17** [comment]
Thanks!

I will check the memory during the optimisation. I checked the memory status at the end of the run, and the memory reached the limit I had available in the cluster.

I'm using my own wrapper because I'm using Borg, but basically is almost a copy of the Platypus wrapper. I checked my wrapper and the pywr online wrappers and didn't find the `model.reset()` command. it should go into the `evaluate` method?

In the coming days, I will try to create a reproducible test to check and debug the model.

**Comment by jetuk** [comment]
> I checked the memory status at the end of the run, and the memory reached the limit I had available in the cluster.

This will probably manifest in a seg fault as your process asks to allocate more memory but is denied. 

The question then is why is the memory usage growing? Is it just the size of the population & associated data growing as you do more function evaluations, or is it a memory leak in your model/custom code/Pywr/GLPK?

> I'm using my own wrapper because I'm using Borg, but basically is almost a copy of the Platypus wrapper. I checked my wrapper and the pywr online wrappers and didn't find the model.reset() command. it should go into the evaluate method?

I think `model.run()` is probably sufficient as it will call reset internally.
