### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get' - when specifying the loss_factor of a losslink via a parameter

### ISSUE THREAD

**Issue by BaptisteFrancois** [pywr/pywr#1091]
Hello,
I am getting this error when specifying the `loss_factor` of a `losslink` via a parameter. There is an easy workaround, that is to specify the loss_factor in the node section directly but I find it more convenient when copying with scenarios to have it defined in the parameter section.

Note that the parameter I'd like to use is simply a constant parameter.
B.

**Comment by jetuk** [comment]
Can you give a minimal example of the problem? I think I understand the issue but want to double check.

**Comment by BaptisteFrancois** [comment]
Here is an example - hope it helps.

`{"name": "example_loss", "type":"losslink", "loss_factor":"my_parameter"}`
while "my_parameter" is defined in the parameter section
`"my_parameter": {"type": "constant", "value"=0.2}`

In the node definition, if I replace the string "my_paramter" by 0.2, it works, if not, I am getting the error above mentioned.

**Comment by Jmiguel17** [comment]
Hi James, any update on this?

In my case, I want to use a `MonthlyProfileParameter`.

This is the full error message:

`model = Model.load(filename, solver='glpk')
  File "pywr/_model.pyx", line 290, in pywr._model.Model.load
  File "pywr/_model.pyx", line 208, in pywr._model.Model.loads
  File "pywr/_model.pyx", line 298, in pywr._model.Model.load
  File "pywr/_model.pyx", line 421, in pywr._model.Model._load_from_dict
  File "pywr/_model.pyx", line 466, in pywr._model.Model.pre_load_node
  File "/Users/user/Dropbox (The University of Manchester)/Doctorado/pywr/pywr/nodes.py", line 70, in pre_load
    non_param_data[key] = load_parameter_values(model, value)
  File "pywr/parameters/_parameters.pyx", line 2350, in pywr.parameters._parameters.load_parameter_values
AttributeError: 'str' object has no attribute 'get'`

Pywr is not loading the data. I added a print statement in the `load_parameter_values` method, and the `values_key` is not there. If I print the `data` in that method, what I get is just a `str`, the name of the `MonthlyParameter`. 

Best,

JM

**Comment by jetuk** [comment]
@Jmiguel17 I've attempted to fix this in #1113. Are you able to test if this works in your case?

**Comment by Jmiguel17** [comment]
Hi @jetuk, I just tested and is working correctly. Thanks!!

JM

**Comment by jetuk** [comment]
Great. Hopefully we can get it merged and released soon enough.
