### ISSUE TITLE
understanding scenarios

### ISSUE THREAD

**Issue by xoxshirl** [pywr/pywr#1092]
I cannot understand why my set up for a scenario is returning an error, any help appreciated 

In my json file: 

  "scenarios": [
    {
      "name": "inflows",
      "size": 12,
      "slice": [
        0,
        11
      ]
    }
  ],
  "parameters": {
    "__River__:flow": {
      "type": "dataframe",
      "url": "River_scenarios.xlsx",
      "scenario": "inflows",
      "index_col": "0",
      "parse_dates": true,
      "comment": "units [ML/day]"
    },

my excel data as follows 
<img width="1076" alt="River_scenarios" src="https://user-images.githubusercontent.com/126896906/234807409-5c1813bd-8de4-4cb3-8621-1ff2fff8a097.png">

Error as follows : 
ValueError: '0' is not in list

Thank you

**Comment by monuronen** [comment]
Not sure but try "index_col": 0
instead of "index_col": "0"

**Comment by xoxshirl** [comment]
> 

TypeError: Invalid DataFrame index type "object" in "daysweirscenarios2.xlsx".


 still an error unfortunately

**Comment by jetuk** [comment]
Oh. I see this is the same issue. Closing in favour of #1093
