### ISSUE TITLE
two reservoir example freezing / run not completing 

### ISSUE THREAD

**Issue by xoxshirl** [pywr/pywr#1094]
Hi, 

I am trying to run the two reservoir example and I have tried a few different approaches but I keep getting frozen in the same place ... 
<img width="525" alt="Screenshot 2023-05-06 at 13 24 03" src="https://user-images.githubusercontent.com/126896906/236623870-206f06d9-13e5-424a-9f5e-ed65ae63efc4.png">

i am running all my packages through anaconda and i am wondering if this may be the reason or if there is another common issues, any help would be greatly appreciated. 

i have been using the following command line argument to specify platypus, have tried a few variations to see if it would make a difference but always gets stuck in the same place. 
python -i two_reservoir_moea_copy.py --harmonic --library platypus

**Comment by jetuk** [comment]
Have you tried without the `-i` flag? This will cause Python to enter an iteractive prompt when the script finishes running, and it may appear not to finish if it is waiting for input.

**Comment by xoxshirl** [comment]
> Have you tried without the `-i` flag? This will cause Python to enter an iteractive prompt when the script finishes running, and it may appear not to finish if it is waiting for input.

I have tried a few different ways and managed to finish after a while! something on my computer extending the run time so will get to the bottom of this, thanks
