### ISSUE TITLE
(Question) efficiency of dataframe vs aggregated parameter

### ISSUE THREAD

**Issue by ccalvocm** [pywr/pywr#1097]
Greetings @jetuk:

I built a whole basin model with hundreds of nodes that takes hours to solve. My JSON file has many maximum flow parameters calculated from river flows as "aggregated" value with "product" as agg_func". Only one flow is currently read from a .csv as dataframe. 

My question is: which is more efficient for pywr, reading a csv or computing flow values from another parameters?

My JSON is in https://github.com/ccalvocm/Nuble/blob/testBombeo/scripts/nuble.json

Many thanks in advance.

**Comment by jetuk** [comment]
Generally it is quite efficient to do the calculations via parameters. Reading separate timeseries as CSV files will likely increase memory usage, so it may be a trade-off between those. 

The long run time might be the solver you are using. To start profiling the run you can do something like this:

```python

# run the model and see if it works
run_stats = model.run()

run_stats = run_stats.to_dataframe()
print(run_stats)
```
If you paste the output of this here I can help you interpret where the time is spent.

**Comment by ccalvocm** [comment]
Thanks @jetuk, I will profile and let you know.

Kind regards.

**Comment by ccalvocm** [comment]
Well, it finally didn't converge. Seems like I'm using a rivergauge too high for a link that ends in a Keating Aquifer with no enough storage capacity.

```
Simplex solve returned: None (0)
Simplex status: no feasible solution exists (4)
Scenario ID: 0
Timestep index: 0
Writing problem data to 'pywr_glpk_debug.mps'...
4404 records were written
Writing problem data to 'pywr_glpk_debug.lp'...
1488 lines were written
GLPK Simplex Optimizer 5.0
577 rows, 733 columns, 6467 non-zeros
2: obj =   2.200000000e+12 inf =   1.583e-02 (1)
```
