### ISSUE TITLE
Can a threshold be a parameter 

### ISSUE THREAD

**Issue by xoxshirl** [pywr/pywr#1101]
Is it possible for a threshold to be a parameter e.g, a way to track a daily or monthly profile that a flow or storage may fall below or above? If not what would be the best way to approach this as I have not come across any? Thanks in advance !

**Comment by jetuk** [comment]
Yes, I think this is already possible. The threshold parameters should accept a parameter for the `"threshold"` argument (or key in JSON).

**Comment by jetuk** [comment]
Can you provide the JSON or code that is causing this error?

**Comment by xoxshirl** [comment]
"Reservoir_failure": {
      "type": "MinimumThresholdVolumeStorageRecorder",
      "node": "Reservoir",
      "threshold": "failure",
      "comment": "returns 1.0 if below threshold e.g. failure, 0 otherwise",
      "is_objective": "minimise"
    },

where "failure" is a parameter which is a daily profile of storage values

**Comment by jetuk** [comment]
Did this resolve your problem?
