### ISSUE TITLE
 Minimum flow requirement (water rights)

### ISSUE THREAD

**Issue by ccalvocm** [pywr/pywr#1106]
Greetings:

I'm building a model which need minimum flow requirements in some links due to existing water rights. I've tried to use RiverGauge instead a link, with a "mrf" flow, but it doesn't meet the water rights flow I require. ¿Is there any other way to model water rights constraints?.

Thank you in advance.
Kind regards,

**Comment by jetuk** [comment]
In what way does the RiverGauge/MRF not meet the water rights you require? If I can understand in some more detail exactly what you are trying to model and how it should behave I can offer some suggestions.
