### ISSUE TITLE
Classes should have __repr__ and __str__

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#113]
As per subject

**Comment by snorfalorpagus** [comment]
What do you think it should look like?

**Comment by jetuk** [comment]
Only came across this wanting to print out a list of `Recorder` objects. I added this temporarily, 
```
    def __str__(self):
        return "{} on {}".format(self.__class__.__name__, self._node.name)
```

However perhaps the recorders should have a name attribute, because you can multiple instances of the same `Recorder` on a `Model`.

**Comment by snorfalorpagus** [comment]
`Storage` is missing this too.

`<pywr.core.Storage object at 0x1121aed08>`

**Comment by snorfalorpagus** [comment]
There is a commit that adds `repr` for the `Storage` nodes in the JSON branch. Still need one for recorders.

**Comment by jetuk** [comment]
`Recorder` now has a name so this shouldn't be too difficult.

**Comment by snorfalorpagus** [comment]
Has this been done?
