### ISSUE TITLE
Recorders need a name

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#117]
They don't have one which makes identifying them difficult.

**Comment by snorfalorpagus** [comment]
Do the recorder names need to be unique (as they are for nodes)? If so is it worth abstracting the code so it can be used for both?

**Comment by jetuk** [comment]
Probably. The `NodeIterator` can be easily reused? Anything to share between them?

I had thought `Recorder` should inherit from a common `Controller` class that we can use for general hooks in to the `setup`, `reset`, `before` and `after` routines. I guess the only difference is that `Recorder` should have some extra methods for objectives? What is currently `Recorder.value`

I also don't think we've made a concious decision whether `Recorder` or `Parameter` is updated first during `before` or `after`.
