### ISSUE TITLE
Reservoir emergency and dead storage

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#12]
* flood storage
* emergency storage
* dead storage

**Comment by snorfalorpagus** [comment]
Dead storage needs to set `max_flow = 0` from the reservoir's outflows. Presumably this could happen at different volumes for different outflows, e.g. due to pumps/intakes being at different levels.

The failure condition needs to be configurable to raise at either the emergency or dead level.

We should also be able to handle evaporation, but I think that's just an outflow like anything else. Probably worth demonstrating all of this in an example script.

**Comment by jetuk** [comment]
We should review the `Reservoir` subclass and decide what our default reservoir behaviour should be. I know we discussed before about the different approaches to `get_cost` and control curves.

**Comment by snorfalorpagus** [comment]
This can be done using `Storage.min_volume`.
