### ISSUE TITLE
Add hydropower 

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#121]
This might require some thinking. A subclass of `Reservoir` might be needed to correctly map the power generation to head etc. Perhaps this could be done in a `Recorder` instead?

**Comment by snorfalorpagus** [comment]
I think an extension to reservoirs that converted the volume to a depth and surface area would be of general use. The hydropower node then just needs to look at the available head at the start of the timestep and set the maximum flow and cost accordingly.

**Comment by snorfalorpagus** [comment]
Presumably this could make use of the new `level` property for `Storage`.

**Comment by jetuk** [comment]
#493 added a hydropower example. 
#525 added surface area, and we already had level. What else is missing for this?

**Comment by snorfalorpagus** [comment]
That's enough for me.
