### ISSUE TITLE
Efficient date-indexed parameters

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#127]
The current test suite makes extensive use of `ArrayIndexedParameter` owing to it's simplicity and speed. However this is less useful for real world data which is often not aligned to the model.

The proposed solution is a subclass of this parameter which accepts a `pandas.DataFrame`. During the Model's `setup()` phase the parameter will work out how to slice and resample the data frame in order for fast numeric indexing.

In the simplest case this could be just a reference to the underlying numpy array and maybe a beginning offset. More complex examples will require resampling, interpolation, etc.

**Comment by snorfalorpagus** [comment]
The first step will be to identify what the input data set looks like:

 - Daily timestep
 - Weekly 
 - Monthly timestep
 - Annual timestep

Where the timestep is the same we just need to work out an offset for the array.

Where the timestep is larger in the model (e.g. monthly) than it is in the dataset (e.g. daily) do we just subsample?

How do we handle the inverse?

**Comment by jetuk** [comment]
Could we simply make the conversion a wrapper around `DataFrame.resample`? You could pass a dict of keyword arguments to give to `resample` during `setup`. It would need to check that the resampling has not resulted in any missing values and throw an error.

**Comment by jetuk** [comment]
Actually perhaps a combination of `resample` and `align`?

**Comment by snorfalorpagus** [comment]
Closed by #136.
