### ISSUE TITLE
Add additional controls to draw_graph

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#151]
The `draw_graph` function doesn't currently accept any arguments - you have no control over the graph that comes out.

Add some basic controls, e.g. height + width, url/data to custom css.

**Comment by snorfalorpagus** [comment]
Additionally it would be nice to have some SVG icons for different node types instead of circles.

e.g. http://bl.ocks.org/syntagmatic/4963194

**Comment by snorfalorpagus** [comment]
Also add directional arrows to edges.

**Comment by snorfalorpagus** [comment]
Added directional arrows in 36610140bd2e30835365aac0a2f002098ce8ade1.

**Comment by snorfalorpagus** [comment]
There are some issues with the graph rendering in D3. The change made to add directional arrows has completely removed the edges from view, and the canvas is the wrong size (it gets clipped).

**Comment by jetuk** [comment]
Was there also a different an issue with IE having the wrong canvas size? Is that related?

**Comment by snorfalorpagus** [comment]
Sorry, missed "IE" from that comment. It's fine in Firefox.

**Comment by snorfalorpagus** [comment]
The fact edges do not draw is a known bug with dynamic SVGs in Internet Explorer... and was reported in 2013.

https://connect.microsoft.com/IE/feedback/details/801938/dynamically-updated-svg-path-with-a-marker-end-does-not-update

Honestly I think the answer is: I cannot be bothered to support IE.

**Comment by snorfalorpagus** [comment]
Fixed some issues with the chart on IE in dd5b7e0a0148e6bb59632a2c1a7fd304399b4625. The arrows don't display, but we'll have to live with it.

I'm closing this in favour of more specific issues (e.g. SVG icons).
