### ISSUE TITLE
ArrayIndexedParameter should convert to float64

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#152]
`pandas.read_csv` returns `int64` if all the numbers are integer even if formatted as "number" in Excel. This causes a type problem for `ArrayIndexedParameter`

Solution is that `ArrayIndexedParameter` does the type conversion and accepts any dtype to `__init__`. Same would apply to other Cython `ArrayIndexed` parameters.

**Comment by snorfalorpagus** [comment]
Sounds good to me.

**Comment by snorfalorpagus** [comment]
Does this just need a call to `np.asarray()`?

**Comment by jetuk** [comment]
It needs to be given a `dtype` otherwise it will do `ints` if it can.
