### ISSUE TITLE
Deficit tracking

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#153]
It's a common query as to how much deficit exists at a particular demand (or group of demands). We can use recorders to calculate the flow at an `Output`, but not the deficit which is `max_flow - flow`. This is also important when tracking "failure days".

I can see two approaches to this:

1. A property of `Output` (or the new `Demand`?) which returns the deficit
2. A recorder which calculates deficit

Either way we'd need a new recorder type (similar to what we did for NumpyArrayLevelRecorder). Failure days can then be tracked with a meta-recorder.

**Comment by jetuk** [comment]
`TotalDeficitNodeRecorder` does this?

**Comment by snorfalorpagus** [comment]
I had overlooked that, although I was thinking of a daily timeseries rather than a total.

**Comment by jetuk** [comment]
Why would you want a daily timeseries?

**Comment by snorfalorpagus** [comment]
I think this will be covered (or something better) by #170.
