### ISSUE TITLE
Nodes coordinates

### ISSUE THREAD

**Issue by khaledk2** [pywr/pywr#154]
Nodes coordinates are needed mainly for network visualization in PywrApp, as JSON does not contains this information, I set random numbers for the nodes coordinates. 
If Pywr doesn't need nodes coordinates to function, I would suggest having a separate csv file which contains the coordinates, what do you think?

**Comment by snorfalorpagus** [comment]
Coordinates aren't required to run the model, but they are useful for visualisation.

Pywr does currently support storing an x,y coordinate pair on a node:

https://github.com/pywr/pywr/blob/master/pywr/core.py#L724-L729

To set these properties from JSON use the "position" keyword. e.g.

```
        {
            "name": "supply1",
            "type": "Input",
            "max_flow": 15,
            "cost": 1,
            "position": [5, -20]
        },
```

I've also been considering allowing for multiple pairs of coordinates. This would allow a "schematic" view as well as a geographic coordinate for overlaying on a map. I'm not sure what this would look like in JSON. Maybe: `{"schematic_position": [5, -20], "geographic_position": [-1.509445, 51.30284]}`.

**Comment by khaledk2** [comment]
Not all the nodes have position in this example:

https://github.com/pywr/pywr/blob/master/model.json

only catchment1 has a position and the other nodes do not
It is needed that all nodes have coordinates to visualize the network.

**Comment by khaledk2** [comment]
I think it is a good idea to have multiple pairs of coordinates.

**Comment by jetuk** [comment]
With geographic position would we need to define the coordinate system somewhere? Should this be a the top or with each position pair?

**Comment by snorfalorpagus** [comment]
My preference would be to do the same as GeoJSON - require coordinates to be given in WGS84 (i.e. latitude and longitude). Most of the JavaScript libraries are set up to work in with LatLngs.

**Comment by khaledk2** [comment]
GeoJSON format is a good option, this would be my preference also

**Comment by jetuk** [comment]
That's agreed then, and it's simple! So the remaining question is do we set it up like,

```
{"schematic_position": [5, -20], "geographic_position": [-1.509445, 51.30284]}
```

or

```
{"position": {
    "schematic": [5, -20],
    "geographic": [-1.509445, 51.30284]
} }
```

**Comment by khaledk2** [comment]
I would prefer the second format, i.e. 
{"position": {
    "schematic": [5, -20],
    "geographic": [-1.509445, 51.30284]
} }

**Comment by jetuk** [comment]
:+1:

**Comment by snorfalorpagus** [comment]
Looks good. How should the Python API look? Currently I think it accepts either `x` and `y` keyword arguments, or a `position` keyword argument of a 2-tuple `(x, y)`.

How about:

```
Node(..., geographic_position=(x1,y1), schematic_position=(x2,y2))
```

Do we drop support for `x=` and `y=`? Or have them as aliases of schematic_position?

**Comment by snorfalorpagus** [comment]
Reopening until the PR is merged.

**Comment by snorfalorpagus** [comment]
Merged.
