### ISSUE TITLE
Additional constraint parameters

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#155]
Following on from #143, there are a couple of constraints/patterns we don't have a standard parameter for.

1. Parameters with a timestep-counting constraint. e.g. `max_flow` is dependent on the number of days since a node had max_flow > 0, or number of days since a demand saving level was breached.
2. Parameter dependent on the average flow over the last x timesteps, e.g. an option is only enabled if average flow for the last week is < X.

**Comment by snorfalorpagus** [comment]
@jetuk What do you think of this approach?

https://gist.github.com/snorfalorpagus/97cf8877c3094b124aa6a3b07b0ca9ce

**Comment by jetuk** [comment]
I like this. It's blurring the lines between Recorder and Parameter. Does it imply that the license classes are implemented incorrectly? I.e. the Parameters track the state there rather than Recorders

**Comment by snorfalorpagus** [comment]
I think the first parameter can be implemented in a similar fashion: a counting recorder (+1 each timestep a condition is met) and a parameter which divides that count by a constant and uses it as an index. The easiest way to implement the counting recorder is to have it as a meta-recorder (it's value is based on another recorder). However, I think this might require the dependency tree we talked about a little while ago for updating parameters/recorders.

**Comment by snorfalorpagus** [comment]
The `MeanFlowRecorder` implements the second feature.

The first feature turned out to be more involved / too specific to the model.
