### ISSUE TITLE
Model.nodes.__delitem__ doesn't remove subnodes

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#166]
A node can be removed from a model as follows:

```
del(model.nodes["nodename"])
```

This works, unless the node is a compound node (reservoirs, gauging stations) as the subnodes are not removed.

https://github.com/pywr/pywr/blob/master/pywr/core.py#L136-L139

In order for this to work we need to also delete any node whos parent is the node being removed. In the short term, a loop that checks every node in the model and deletes it if it's parent is being removed will do. It's not 100% robust though (think multiple levels of compound node).

**Comment by jetuk** [comment]
This code has moved to here:

https://github.com/pywr/pywr/blob/master/pywr/_model.pyx#L745

**Comment by jetuk** [comment]
>  In the short term, a loop that checks every node in the model and deletes it if it's parent is being removed will do.

Suggest we do this for 0.5
