### ISSUE TITLE
`IndexedArrayParameter` doesn't add it's subparameters as children

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#167]
There are probably other instances of this we need to hunt for. This means their before and after methods aren't called. This isn't causing issues yet as we rarely use those methods.

Also the reverse needs to work. When a node is deleted it should remove itself as the parent it's children. We can't just put this in `__del__` as it wont be called (as the children's reference keeps it alive!). Need to handle this in `Model.delete`. See #166

**Comment by jetuk** [comment]
The other option is to throw an exception if you try to delete a compound node?

**Comment by snorfalorpagus** [comment]
That's too much of a cop-out for me. :)

**Comment by snorfalorpagus** [comment]
The specific issue has been resolved in e4e9f1d444bb3ea01b4a05f1900c0cf01c3e582a. The more general issue remains.

**Comment by snorfalorpagus** [comment]
All of the parameters should be well behaved now that we've implemented the dependency tree.
