### ISSUE TITLE
Attributes types

### ISSUE THREAD

**Issue by khaledk2** [pywr/pywr#168]
I have explored the Pywr repo in the git looking for additional examples to test the PywrApp with and have found some in this folder

https://github.com/pywr/pywr/tree/master/tests/

The models have some attributes which I need your help to explain them

o	"monthlyprofilecontrolcurve” for  “cost” attribute in “reservoir1” node
        https://github.com/pywr/pywr/blob/master/tests/models/reservoir_with_cc.json

o	“monthlyprofilecontrolcurve” for “max_flow” attribute for “demand1” nodes
         https://github.com/pywr/pywr/blob/master/tests/models/demand_saving.json

o	“demand_saving_factor” in parameters section 
         https://github.com/pywr/pywr/blob/master/tests/models/demand_saving2.json

**Comment by jetuk** [comment]
The `type` key in the json refers to a `Parameter` subclass. See `pywr.parameters` sub-package for the valid subclasses. The general pattern here is that some `Node` attributes like `cost` and `max_flow` can be `Parameters` and not single numbers. 

I don't know how this will translate in the Hydra format / DB. I think we will need special handling of the various types that exist. For example `monthlyprofile` must reference a monthly profile stored somewhere in the DB. However I don't know how Hydra deals with this.

FYI the `monthlyparametercontrolcurve` is probably one of the more complex examples.

**Comment by khaledk2** [comment]
Hydra supports these attributes types:

•	Scalar
•	Array
•	Timeseries which includes Seasonal
•	Descriptor (string)

They can handle most of the attributes types, for example monthlyprofile is represented as a seasonal attribute.

Could you please clarify what “monthlyprofilecontrolcurve” and “ControlCurveInterpolated” attributes types are and what they represent?

**Comment by snorfalorpagus** [comment]
Does the documentation help you?

https://github.com/pywr/pywr/blob/master/pywr/parameters/control_curves.py#L235-L255
https://github.com/pywr/pywr/blob/master/pywr/parameters/_control_curves.pyx#L81-L114

**Comment by jetuk** [comment]
I think they would have to created from multiple attributes in Hydra.

**Comment by khaledk2** [comment]
I have modified the Pywr App and added the support for the following attributes 
Aggregated parameters,  ControlCurveInterpo-latedParameter, MonthlyProfileControlCurveParameter, and monthlypro-filecontrolcurve attributes 
It creates them from multiple Hydra attributes and their metadata
So, the app reads the Pywr JSON string and creates hydra network and pushes it to the Hydra. It also generates the Pywr JSON string from the Hydra network.
