### ISSUE TITLE
Add "divide" aggregation function

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#193]
I hadn't thought we'd need this, but have just come across a function that requires it, where:

```
target flow = MRF / weir efficiency
```

This can obviously be converted to a factor:

```
target flow = MRF * (1 / weir efficiency)
```

However, efficiency is 0.95, which ends up as 1.0526315789473684210526315789474. For the sake of readability it would be nice to preserve the 0.95.

**Comment by snorfalorpagus** [comment]
This doesn't work. None of the other aggregate functions care about their order and are stored in a `set`. A divide aggregate would require the parameters had an order.

**Comment by jetuk** [comment]
We added a separate `DivisionParameter` in #722
