### ISSUE TITLE
Implement seasonal and rolling licences

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#2]
Implement a licence class to be handled by the solver that supports:
- [x] Daily licence
- [x] Annual licence
- [x] Seasonal licence
- [x] Rolling licence
- [x] Licence groups (done via aggregated nodes)
- [x] JSON support

**Comment by snorfalorpagus** [comment]
Daily and annual licenses implemented in 5047294a67845992e9674490605b752c28ecb139. Solver applies licenses as constraints in 5029478d999b8b50e21269f7a7de98bbaca195ce. Still need to implement other license types, including:

* Group licenses

**Comment by snorfalorpagus** [comment]
Remove timestep specific code from DailyLicense. TimestepLicense?

**Comment by snorfalorpagus** [comment]
I've begun to make the changes required for licenses to work with non-daily timesteps, and for the use of seasonal and rolling licenses in ddaca50.

However, to continue a decision needs to be made: should licenses have access to `model.timestamp` (currently they do not) or should `License.commit` be called with `timestamp` as an argument?

**Comment by jetuk** [comment]
I vote for something on commit. This way in theory it could vary. However
does it need timestamp and timestep?

I've begun to make the changes required for licenses to work with non-daily
timesteps, and for the use of seasonal and rolling licenses in ddaca50
<https://github.com/snorfalorpagus/pywr/commit/ddaca50377427431a353a810f08c906850a3d0ad>
.

However, to continue a decision needs to be made: should licenses have
access to model.timestamp (currently they do not) or should License.commit
be called with timestamp as an argument?

—
Reply to this email directly or view it on GitHub
<https://github.com/snorfalorpagus/pywr/issues/2#issuecomment-112209932>.

**Comment by snorfalorpagus** [comment]
Are you thinking of a variable timestep? I hadn't really considered that.

**Comment by jetuk** [comment]
It's common when solving differential equations in time. They often have
some sort of error check to reduce the timestep if it thinks the one it has
just done is too large. That's probably not needed here, but you could
imagine specifying weekly or daily during different periods of the year, or
if storage was low?

Perhaps not the highest priority.

**Comment by snorfalorpagus** [comment]
Currently licences that have a state (e.g. annual licences) are not scenario-aware.

**Comment by snorfalorpagus** [comment]
As of 491f764bbe3e4a4b1692c4d1d545596eba040abb the licence classes have been refactored. They are now scenario-aware.

XML support is now broken (I think).

Still need to implement seasonal and rolling licences, but I don't think this should be too difficult using the annual licence as a template.

**Comment by snorfalorpagus** [comment]
Need to add JSON support for licences.

**Comment by jetuk** [comment]
I received a query about this today, and also happened to think about it last week.

Generally we need a licence based from `VirtualStorage` so it can be used to both constraint availability and as a state for remaining licence. There are two approaches I think,

1. Extend `VirtualStorage` (probably in Cython for speed) and incorporate a memory into the new class that during `after` increments storage by the usage N time-steps ago (stored in the memory).
2. Write a new delay parameter (that does the memory part), and have a new Python space subclass of `VirtualStorage` the adds you a node to supply the flow from N days in the LP. 

I think (1) is probably better to be honest, but the delay parameter in (2) would have other uses. @Batch21 @JackJohnson93 thoughts?

**Comment by Batch21** [comment]
1. seems like the better option. What are the other use cases you thinking of for the delay parameter?

**Comment by jetuk** [comment]
Solving https://github.com/pywr/pywr/issues/505

**Comment by jetuk** [comment]
Rolling and seasonal licenses implemented in #891 and #923 respectively.
