### ISSUE TITLE
Dependency graph for Parameters and Recorders

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#205]
The solver(s) currently update `Parameters` recursively. This results in some inefficiencies (e.g. #107). This is partly resolved using the `CachedParameter` object. I think a better solution would be to resolve the dependency tree of the `Parameters` during `setup`, then at the start of each `solve` calculate the value of every parameter and use the cached result instead of calling `node.get_max_flow` etc.

A similar problem exists for recorders, which means it's not possible to have a meta-recorder (a recorder dependent on another recorder) as the order of resolution is not necessarily sensible.

The resolution order can be solved using the `nx.dfs_postorder_nodes` function.

A down-side to this is for `ControlCurveIndex` parameters, which have a short-circuit optimisation - when they find a control curve the reservoir is above, they don't evaluate the rest.

**Comment by snorfalorpagus** [comment]
Here's the prototype code I wrote for this.
```
from pywr._core import Storage, Node
from pywr.parameters._parameters import Parameter
from pywr.core import AggregatedNode, AggregatedStorage
import networkx as nx

G = nx.DiGraph()

all_parameters = set()

for node in model.nodes:
    if isinstance(node, Storage):
        if isinstance(node.max_volume, Parameter):
            all_parameters.add(node.cost)
        if isinstance(node.cost, Parameter):
            all_parameters.add(node.cost)
    elif isinstance(node, AggregatedStorage):
        if isinstance(node.max_volume, Parameter):
            all_parameters.add(node.cost)
    elif isinstance(node, AggregatedNode):
        if isinstance(node.max_flow, Parameter):
            all_parameters.add(node.max_flow)
        if isinstance(node.min_flow, Parameter):
            all_parameters.add(node.min_flow)
    else:
        if isinstance(node.max_flow, Parameter):
            all_parameters.add(node.max_flow)
        if isinstance(node.min_flow, Parameter):
            all_parameters.add(node.min_flow)
        if isinstance(node.cost, Parameter):
            all_parameters.add(node.cost)
            
to_process = list(all_parameters)
            
visited = set()

while len(to_process) > 0:
    parameter = to_process.pop()
    if not parameter.parents:
        G.add_edge("root", parameter)
    visited.add(parameter)
    for child in parameter.children:
        G.add_edge(parameter, child)
        if not child in visited:
            to_process.append(child)

check = set()
            
for node in nx.dfs_postorder_nodes(G, "root"):
    if node == "root":
        break
    
    # check dependencies have been resolved
    check.add(id(node))
    for child in node.children:
        assert(id(child) in check)

nx.draw(G)
```

**Comment by snorfalorpagus** [comment]
We discussed this today and decided it's a priority.

We decided to move away from PairedSet and keep track of the parameter/recorder tree in a networkx graph on the model. This means parameters will need a reference to model (recorders already have this).

The focus here is on the setup/reset/before/after methods. We can have another PR/issue for getting solver to make use of this (only calling parmeter.value once per parameter).

**Comment by jetuk** [comment]
It occurred to me that `Recorder` and `Parameter` should share a parent class.

**Comment by snorfalorpagus** [comment]
I've considered this too. Should save be renamed to after?

**Comment by jetuk** [comment]
I just did that :)
