### ISSUE TITLE
DailyProfileParameter handling of leap years

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#212]
Our current approach to leap days in daily profiles is to make all profiles 366 days long. In leap years 31st December is day 366. In non-leap years 31st December is day 365. This seems like a bug to me.

The solution would look something like this (in `DailyProfileParameter.value`):

```
if not is_leap_year:
    if dayofyear > 28th February:
        dayofyear += 1
return values[dayofyear]
```

is_leap_year can be taken from here: http://stackoverflow.com/a/11595914/1300519

This would behave more like a dictionary:
```
value = values[(month, day)]
```

(On that note, probably worth checking that a dictionary isn't in fact faster - I assume not)

**Comment by jetuk** [comment]
The last part of this confuses me. Where does that go?

**Comment by snorfalorpagus** [comment]
It doesn't. Was more for illustration of the behaviour. The same day, month pair will return the same value, regardless if the year is a leap year. See the PR for implementation.
