### ISSUE TITLE
Redefining parameter types causes problems for parameter_registry

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#215]
When interactively developing a new parameter type (in Jupyter) we can end up with many different versions of the parameter stored in `parameter_registry`. Should `parameter_registry` be a dict? I can't remember why it's a set.

Same applies for other registries.

#159.

**Comment by jetuk** [comment]
The registries are only accessed by class name? So they should be unique per name. I assume set so it is unique as opposed to list?
