### ISSUE TITLE
Catchment can only have one successor

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#225]
https://github.com/pywr/pywr/blob/master/pywr/domains/river.py#L42-L43

I can't remember what the reason for this was. I don't think it's technical.

**Comment by jetuk** [comment]
https://github.com/pywr/pywr/commit/a0f6a96fe0c275ebfd53e0619855994de1769286

**Comment by snorfalorpagus** [comment]
It's ancient then. I think we should remove this constraint. Perhaps do at the same time as #118.
