### ISSUE TITLE
Why doesn't GLPK from conda-forge work with Pywr?

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#226]
The GLPK available from conda-forge doesn't work with our Pywr build. Why?

**Comment by snorfalorpagus** [comment]
The conda-forge GLPK package doesn't include the shared library, only the static library. Need to find out why.

**Comment by snorfalorpagus** [comment]
https://github.com/conda-forge/glpk-feedstock/issues/12

**Comment by snorfalorpagus** [comment]
The PR to the glpk-feedstock has been merged but the build failed on OS X and Windows. Need to wait for it to be rebuilt.

**Comment by jetuk** [comment]
One thing I noticed is that the GLPK build doesn't include the headers to allow you to compile.

**Comment by snorfalorpagus** [comment]
This has been resolved upstream.

The build does include the headers but you need to point the compiler at them.
