### ISSUE TITLE
Documentation: extending Pywr

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#228]
Example of extending Pywr to create custom nodes, parameters and recorders.

**Comment by snorfalorpagus** [comment]
I'm going to have a go at writing this as it think it's quite important. I'm aware we're going to be changing the JSON loading for Parameters in the future, but that's only a small part of it.

**Comment by jetuk** [comment]
I have some uncommitted text I'll post here.

**Comment by jetuk** [comment]
Added in #652.
