### ISSUE TITLE
Evaporation from reservoirs based on surface area

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#229]
What's the best way to implement this? Perhaps a demand node, where the max flow is dependent on a reservoir node? Where should the volume/area relationship be stored?

**Comment by jetuk** [comment]
Should we add `area` in the same way as `level` ?

Does evaporation need to be in the solver? Can it just be done in `after`?

**Comment by snorfalorpagus** [comment]
Remember that `level` is implemented only for `KeatingAquifer`, not for `Storage` in general. Should this be part of the default `Reservoir` class?

If we do evaporation in `after`, it implicitly is lowest priority (as anything else would take before).

**Comment by jetuk** [comment]
`level` is actually part of `Storage`.

**Comment by jetuk** [comment]
#525 added surface area to `Storage` and included an evaporation example in the tests.

**Comment by snorfalorpagus** [comment]
> #525 added surface area to Storage and included an evaporation example in the tests.

That's good enough for me.
