### ISSUE TITLE
Tests for optimisation subpackage

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#230]
This needs doing. 

As an aside I was thinking about writing a generic test that used introspection to test whether the methods `update`, `lower_bounds` and `upper_bounds` have been implemented for all `Parameter` subclasses. What do you think?

**Comment by snorfalorpagus** [comment]
How do we get the tests for this to run in a reasonable amount of time on the CI?

Do we want every parameter to support this? What about aggregated parameters - does it make sense?

**Comment by jetuk** [comment]
First we can test the components work. E.g. the suggestion to test for the methods. 

No there will be some exceptions. Ideally you shouldn't be able to set `is_variable = True` if it's not supported.

**Comment by snorfalorpagus** [comment]
> Ideally you shouldn't be able to set is_variable = True if it's not supported.

I think that can be achieved by making `is_variable` a property on `Parameter`. We'd need a class variable that declares if Parameter can be a variable, which causes the `__set__` method to raise an exception if needed.

At first I thought that sounded like two variables doing the same thing, but one would describe if a Parameter can be a variable and the other would describe if it actually is.

**Comment by jetuk** [comment]
#610 is addressing some of the testing issue. I'm going to make a new issue for `is_variable = True`.

**Comment by jetuk** [comment]
Tests were added in #610 for all modules exception `inspyred`.
