### ISSUE TITLE
monthlyprofilecontrolcurve parameter

### ISSUE THREAD

**Issue by khaledk2** [pywr/pywr#231]
Demand_saving.json example, for demand1 node, max_flow parameter which has monthlyprofilecontrolcurve type
I have tried to use parameters references for both or any of
scale
profile
I got errors as it seems that it assigns the reference string value to each of them rather than getting the values from parameters section.
While I have used the parameter reference for:
control_curve
It worked fine.
In addition I thinks values for this parameter type (monthlyprofilecontrolcurve) could be assigned in using parameter reference

**Comment by snorfalorpagus** [comment]
The `MonthlyProfileControlCurve` class was created as a convenience class for demand nodes. I don't think I've ever used it in practice, as the approach demonstrated in "demand_saving2.json" is more flexible.

It's not possible to move the values into a parameter, as they are 2D. In this case the `MonthlyProfileControlCurve` *is* that parameter.

I guess we should question if we need to continue to support `MonthlyProfileControlCurve`. @jetuk you wrote this. Do you think it's still useful?

**Comment by snorfalorpagus** [comment]
Bump @jetuk

**Comment by jetuk** [comment]
I don't think I use this anywhere. Could be deprecated I guess.

**Comment by snorfalorpagus** [comment]
Let's ditch this in 0.5.

**Comment by jetuk** [comment]
This has been given a deprecation warning in 0.5. Remove completely in 0.6
