### ISSUE TITLE
Remove `Blender`

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#234]
The `Blender` node has be superseded by use of `AggregatedNode`. The new setup is actually more flexible. Previous the Blender node would ensure a fixed ratio of two inputs to the node. AggregatedNode allows a fixed ratio between any two (or more) nodes, which means we can fix both incoming and outgoing.

Fixed ratio incoming:

```
(A) -->--|
         +-->-- C -->-- D
(B) -->--|
```

Fixed ratio outgoing:

```
               |-->-- (E)
C -->-- D -->--+
               |-->-- (F)
```

Or a combination thereof. Do we need a convenience class for this?

**Comment by snorfalorpagus** [comment]
@jetuk You mentioned you were looking into this. Did you get anywhere?

**Comment by snorfalorpagus** [comment]
See #754 also.

The `Blender` node still exists, but it's constraint is not respected at all by the solver. As a minimum I think we should raise an exception on it's instantiation directing users towards aggregated node, as it's current situation is misleading to users.

**Comment by jetuk** [comment]
Why do we not just remove `Blender`?

**Comment by snorfalorpagus** [comment]
That works for me, given that it's broken currently.
