### ISSUE TITLE
Separate model and state

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#24]
To facilitate running multiple models it would be a good idea to allow multiple states of the model to be tracked independently. The model structure (graph) is common, but the Parameters are potentially different. 

If we refer to each execution as a scenario, then suggest we look at something like a ScenarioParameter that can store a value on a per scenario basis. The commit methods would then look something like this,

```
def commit(self, scenario, volume, chain):
    pass
```

**Comment by snorfalorpagus** [comment]
This shouldn't be *too* difficult. Any object that has a state (or is dependent of the state of another component) would need to be "scenario" aware. This is basically any `Parameter`, `Variable`, `License`, or any of the more external components (e.g. a `CatchmodCatchment` object would need to store multiple states).

I think it's worth absolutely nailing down how we expect the model to be used first though. It would be easy to run off and implement something, that didn't then fit later.

**Comment by snorfalorpagus** [comment]
We also need to think about how it ties in with logging/graphing. The aim is to be able to dump timeseries of output variables (e.g. amount demanded, amount supplied [per component, or for groups]) as well as intermediate variables like reservoir storage and license capacities.

**Comment by jetuk** [comment]
I see the requirement as running one model (graph) with multiple parameters simultaneously. I imagine this would require a `ModelController` object to manage the runs. Subclasses of such would provide different functionality, for example,
- robust decision making (i.e. just running lots of scenarios)
- interface to evolutionary algorithm
- Scottish DO method
- automated calibration

The EA stuff will require parameters to be modified (i.e. the variables) by the algorithm, and then the population reran. However I don't see why this is fundamentally a problem. There is code some to translate the EA's "DNA" into model parameters, and return fitness.

Re the logging. I think in addition to dumping variables (which may not be required for EA) we will need to have some components providing statistics. For example for reservoirs this could be days below a level, similar for MRF and demands. This will allow you to provide objectives in an easier fashion, either by returning them to the EA, or by grouping them in some way.

**Comment by jetuk** [comment]
Also as per the title of this issue. Should the XML separate model and parameters (or at least parameter data)?

**Comment by snorfalorpagus** [comment]
I think this is covered in the scenarios code.
