### ISSUE TITLE
Issues while loading JSON

### ISSUE THREAD

**Issue by khaledk2** [pywr/pywr#251]
-  “extra2.json”
      o   If the JSON does not contain metadata section or timestepper section it will throw an error.
      o   Also, “link” is not defined in the nodes section for this file.

-  “reservoir_with_cc.json”
      o   generates this error:
             	“ValueError: No objects to concatenate”

-  “virtual_storage1.json” 
      o   generates this error:
              “KeyError: 'annualvirtualstorage”

**Comment by jetuk** [comment]
Thanks @khaledk2. I'll check why these aren't loaded in the tests.

**Comment by jetuk** [comment]
So

- "extra2.json" - this is not intended to be loaded from Python. It is referenced in the "includes" section of "extra1.json". Hence it doesn't need the metadata and timestepper sections. 
- "reservoir_with_cc.json" - is not used in any of the tests.
- “virtual_storage1.json”  - is used. Have you recompiled master recently? `VirtualStorage` is relatively new.

**Comment by snorfalorpagus** [comment]
I'm not sure why "reservoir_with_cc.json" isn't tested, but it is valid - I can load an run it without any problem.
