### ISSUE TITLE
Initial timestep index

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#254]
Consider the following:
```
>>> from pywr.core import Model, Input, Output
>>> model = Model()
>>> inpt = Input(model, "input")
>>> otpt = Output(model, "output")
>>> inpt.connect(otpt)
>>> model.timestepper.current.index
0
>>> model.step()
>>> model.timestepper.current.index
0
>>> model.step()
>>> model.timestepper.current.index
1
```
Before the model is run, the current timestep index is 0. After one step, it's still at 0 (but the end of the day). After another step it's at 1 (at the end of the day).

Should the initial timestep report -1 for it's index? I came across this in #253, when calculating a parameter dependent on the reservoir state outside of the call to step.

**Comment by jetuk** [comment]
Yeah this has confused me before. Perhaps it should be `None` to begin with? -1 might cause weird errors where the last item is taken from a list?

**Comment by snorfalorpagus** [comment]
Should `current` be None, or should `current` be a `_core.Timestep` where `.index` is None?

**Comment by jetuk** [comment]
I'm not sure what breaks / needs a `Timestep.index` before the model starts? I guess `current == None` would be better.

**Comment by snorfalorpagus** [comment]
This breaks a few tests which test parameters outside of the normal model loop. It shouldn't be too difficult to tweak them though.
