### ISSUE TITLE
Rename MeanParameterRecorder

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#257]
`MeanParameterRecorder`  -> `RollingMeanParameterRecorder`

Argument `timesteps` could be called `window` too.

`MeanParameterRecorder` would then be a mean of all the timesteps.

**Comment by snorfalorpagus** [comment]
What's the reason for changing `timesteps` to`window`?

**Comment by jetuk** [comment]
Compatibility with pandas? I think calling it a window makes it clearer that it's a rolling calculation.

**Comment by snorfalorpagus** [comment]
Is there any merit in expanding this parameter into a more general RollingWindowParameter that could record the mean/min/max/sum?

**Comment by jetuk** [comment]
I don't see why not.
