### ISSUE TITLE
Make core.py more modular

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#259]
The `core.py` file is now 1500+ lines. I think this is too much, and would benefit from being split into smaller parts, perhaps:

```
core/__init__.py
core/timestepper.py
core/model.py
core/nodes/__init__.py
core/nodes/basic.py
core/nodes/storage.py
core/nodes/???
core/scenarios.py
core/domains/__init__.py
```

Also, maybe drop the "core" name entirely.

```
from pywr.model import Model
from pywr.nodes import Input, Output, Link
```

**Comment by jetuk** [comment]
I agree with this.

**Comment by jetuk** [comment]
This is complete now?

**Comment by snorfalorpagus** [comment]
I'm undecided if we should actually remove core.py now.

**Comment by jetuk** [comment]
I think I made a comment about a `pywr.api` module. Some other projects use that approach.

**Comment by snorfalorpagus** [comment]
You mentioned it in #311. I'm not familiar with this approach. Does the `api` module just provide access to anything and everything, with the details of the sub-modules hidden? Can you give me an example project?

**Comment by snorfalorpagus** [comment]
The current setup is good enough for now. The code is more manageable and keeping core around keeps everything working for older code.
