### ISSUE TITLE
Releases and version numbers

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#260]
I've been thinking about how we manage releases with Git. I think this is what we need to do:
```
current state ---> tag "0.1"
    |
    v
increment to "0.2dev"
    |
    v
do some more work
    |
    v
increment to "0.2" ---> tag "0.2"
    |
    v
increment to "0.3dev"
    |
    v
even more work
```

I think #259 should be in "0.2".

**Comment by jetuk** [comment]
Follows https://www.python.org/dev/peps/pep-0440/ 

I don't see a problem with this. Do you want date based versions (e.g. `2016.1`) or not?

**Comment by snorfalorpagus** [comment]
I don't like date based versions.

**Comment by jetuk** [comment]
That's settled then.
