### ISSUE TITLE
TablesRecorder can't handle AggregatedNode

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#268]
When attaching a `TablesRecorder` to a model without passing it any nodes, it tries to record every node. It can't handle `AggregatedNode`:

```
ValueError: Unrecognised Node type '<class 'pywr.core.AggregatedNode'>' for TablesRecorder
```

**Comment by jetuk** [comment]
I see the issue. This is because we now have some more fundamental node types than we had when it was written. Should be easy to fix.

**Comment by jetuk** [comment]
It also has no way to handle recording `Parameter` objects.
