### ISSUE TITLE
Documentation: aggregated parameters

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#273]
AggregatedParameter: sum, product, max, min, mean, custom
AggregatedIndexParameter: sum, max, min, any, all, custom
## Example usage
- [sum] Adding supplies or demands together (i.e. one node instead of two)
- [product] Complex demands (see demand saving)
- [max] Worst-case demand saving level between two (or more) reservoirs
- [any / all] As above, with different condition.

Custom function only available via Python (not JSON).

Also worth mentioning MaxParameter/MinParameter/NegativeParameter as these are optimised replacements for common AggregatedParameter tasks.

**Comment by snorfalorpagus** [comment]
I've written 90% of this. Just need to finish it off and upload.

**Comment by jetuk** [comment]
Is median not implemented? It is in the recorders equivalent.

**Comment by snorfalorpagus** [comment]
It is not. #408
