### ISSUE TITLE
Detecting parameter type of CachedParameter

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#289]
`CachedParameter` currently inherits from `IndexParameter`. This was done so that index parameters can be cached (which is the primary use case - caching expensive to calculate control curves). This creates problems for `TablesRecorder`, which needs to know the type of a parameter in order to correctly guess the `dtype` (float or int).

https://github.com/pywr/pywr/blob/00e33b4c1861ba7d2f69630beffcc9fd599aac7d/pywr/parameters/_parameters.pyx#L186

**Comment by jetuk** [comment]
The inheritance structure for `Parameters` is a bit confusing. 
- `IndexParameter` is a subclass of `Parameter`
- `CachedParameter is a subclass of `Parameter`

This makes it difficult to check the underlying type of the `Parameter` that is cached. 

At the moment we `cdef IndexParameter` where we know we want an integer index. We could drop `IndexParameter` entirely and have each subclass decide whether to implement `index()` or not. This will clean the type inheritance structure.

Ideas,
- Incorporated caching directly in `Parameter`
 - challenges with ensuring caching is not accidently remove in subclasses.
- Drop `IndexParameter`
 - rename `index()` to `value_int()`
 - is there a default implementation to cast from the double return by `value()`?
 - how to solve #258 at the same time?

**Comment by snorfalorpagus** [comment]
See approach to doubles/integers used in #302. Can we apply this?

**Comment by snorfalorpagus** [comment]
Implementation #205 could make cached parameters redundant.

**Comment by snorfalorpagus** [comment]
This has been addressed in #323 (by removing CachedParameter).
