### ISSUE TITLE
Nash-Sutcliffe Recorder

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#294]
And/or a general class of `Recorder` for comparison other timeseries.

**Comment by snorfalorpagus** [comment]
Presumably this doesn't have to be too efficient, as it will only be used during testing a model?

**Comment by jetuk** [comment]
It  could be used as an optimisation variable also. 

The N-S calculation can be accumulated each time-step. So there is no need for this recorder to keep the modelled timeseries as such.

**Comment by snorfalorpagus** [comment]
@jetuk I know you've been using N-S recently - has this been done?

**Comment by jetuk** [comment]
No it has not. Recent work has be outside of Pywr.

The following paper has a bunch of other metrics that could also be implemented.

http://swat.tamu.edu/media/90109/moriasimodeleval.pdf

**Comment by snorfalorpagus** [comment]
Implemented in #397.
