### ISSUE TITLE
Tests calling step without setup/reset/finish

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#306]
We have quite a few tests which run the model manually (i.e. by calling `step()` rather than `run()`). This is useful for testing. However, most of them don't call `setup()`/`reset()`/`finish()`. Is this an issue?

e.g. https://github.com/pywr/pywr/blob/8c6b2873b59e16fa9fe886c510d6aa73668eedbb/tests/test_run.py#L85-L91

**Comment by jetuk** [comment]
Some of the only work because they know they don't call these methods, or they call them explicitly if needed. Is it a problem? I think the tests generally know what they're doing?

**Comment by snorfalorpagus** [comment]
Closed, assuming that the tests know what they are doing.
