### ISSUE TITLE
Error on unknown keywords to Node

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#31]
Should `Node.__init__` raise an error when given unknown/unused keywords?

**Comment by snorfalorpagus** [comment]
I have considerred this, but couldn't see an obvious way to implement it given the way `Node` is so frequently subclassed. Must a class keep a record of every valid kwarg for it's parent nodes? Or should each `__init__` method append to a list (can this be done at instance rather than class level?)

**Comment by jetuk** [comment]
Don't you usually do this with crazy metaclass magic that turns class attributes into instance attributes?

**Comment by snorfalorpagus** [comment]
Closed by #85.
