### ISSUE TITLE
Writing metadata to TablesRecorder

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#317]
It would be useful to be able to write metadata into the h5 files produced by TablesRecorder. e.g.:

```
        "database": {
            "mode": "w",
            "nodes": [...],
            "metadata": {"demand_scenario": "medium", "demand_year": 2020}
          }
```

This, combined with the jinja templating we're using to create the JSON document(s), would be useful when post-processing the results.

**Comment by jetuk** [comment]
This works be easy to add to `h5file.root._v_attrs`
