### ISSUE TITLE
Add deficit recorder

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#320]
Our current approach to recording the deficit at demand nodes is to add a "deficit" node with a high cost and use traditional node recorders. This creates more routes in the LP. I wonder if we could speed models up by having a dedicated deficit recorder which doesn't require an additional node. We already have a `TotalDeficitNodeRecorder`. I propose a `DeficitNodeRecorder` (based on numpy) and also a new "deficit" section to `TablesRecorder`.

**Comment by snorfalorpagus** [comment]
I've confirmed that removing the deficit routes can significantly speed up a model.

We had some debate about whether the deficit (max flow - actual flow) should be calculated for all nodes. Then recording the deficit would be as simple as reading a variable. I'm not sure I see the value in this as the information isn't useful/interesting for most nodes?

**Comment by jetuk** [comment]
We also discussed precalculating and storing `max_flow` et al on the object directly. I think this relates to #205 too.

**Comment by snorfalorpagus** [comment]
Now that #411 is resolved it should be easy to add a deficit section to tables recorder.

**Comment by snorfalorpagus** [comment]
This would require creating parameters within the init of the recorder, which I'm not too keen on. The user can still pass an existing DeficitRecorder as a parameter.
