### ISSUE TITLE
Automatic documentation builds

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#328]
I've figured out how to do automatic documentation builds on Travis for Shapely. It shouldn't be too difficult to port this to Pywr. Not much point in doing it until we have some more documentation though?

**Comment by jetuk** [comment]
Agreed, probably not.

**Comment by snorfalorpagus** [comment]
https://github.com/drdoctr/doctr

This simplifies the whole process!

**Comment by jetuk** [comment]
I'm not sure I understand how any of this actually works

**Comment by snorfalorpagus** [comment]
I made some attempt at this in the doctr branch.

https://travis-ci.org/pywr/pywr/jobs/203614484

The issue is that we're building / installing / testing the module using conda-build, so it's all done in an environment. I see a few options:

* Don't use conda-build. Install the dependencies, then install pywr using setup.py and run tests as normal. Then build the docs.
* Build the docs inside conda-build. It's not clear where it would go, but needs to be after tests.
* Build/test in conda as we are. After success, activate the still-existing test environment and build the docs.

All three have merits.

**Comment by jetuk** [comment]
What happened to the doctr branch?
