### ISSUE TITLE
Add labels to d3 graphs

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#330]
I have a working prototype of dynamic labels on a d3 graph (i.e. the labels can be updated without redrawing the whole graph).

I was thinking of an API something like this:

```
# draw the graph
graph = create_graph(model, width=200, height=200)
# define a function to format node labels
def label_func(node, ctx):
    return "{} [{}]".format(node.name, node.recorders[0].data[ctx.timestep])
graph.label_func = label_func
# update the node labels in-place
graph.update(timestep=20)
```

**Comment by jetuk** [comment]
Could `label_func` return `None` if you don't want a label?

**Comment by snorfalorpagus** [comment]
> Could label_func return None if you don't want a label?

That sounds good.

**Comment by jetuk** [comment]
This was added in #612.
