### ISSUE TITLE
Evaporation and minimum storage

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#332]
Our current approach to dead storage - setting the minimum volume of the node - doesn't play nicely with evaporation, which may in theory draw down a reservoir below the dead storage level. The effect is likely to be minor.

Perhaps it would be possible to have different minimum storage volumes for different storage outputs in the same compound node?

**Comment by jetuk** [comment]
This doesn't seem very trivial to do in a clean fashion?
