### ISSUE TITLE
y=mx+c parameter

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#334]
I've seen quite a few inflows that are based on regression from another inflow. It's ugly/slow to create these using the existing AggregatedParameter objects. It would be nice to have a parameter that could calculate y=mx+c where y is the new flow and x is the original flow.

In theory we could implement something more complex, that took an arbitrary equation. I don't think this is needed right now though.

**Comment by snorfalorpagus** [comment]
@jetuk suggested we use a generic 1D polynomial parameter, possibly with an extension to protect against negative values.

**Comment by snorfalorpagus** [comment]
@jetuk Do we have some code for this already related to the LPM? I have a model I'd like to use this with so will implement it otherwise.

**Comment by jetuk** [comment]
Yes. I will dig it out. We have both 1D and 2D of arbitrary order I think.
