### ISSUE TITLE
Install docs doesn't have all dependencies

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#337]
This needs double checking but `packaging` and `future` are missing.

**Comment by snorfalorpagus** [comment]
Related to #335.

**Comment by matrosoe** [comment]
MS Visual Studio 2015 Community on doesn't install C++ compiler by default, need to specify
When not installing Pywr in an Anaconda environment, put glpk.h into Anaconda3\include

**Comment by matrosoe** [comment]
For Python 3.5, need to compile glpk library (v4.6) using Visual Studio 2015 (v 14.0)
 ftp://ftp.gnu.org/gnu/glpk/
Download the latest (4.60) source code from the above FTP
Extract, go to w64 directory. There are VC14 (VS2015) bat files that look pretty much good to run as is. Use the the DLL one.
Read w64/readme.txt

**Comment by matrosoe** [comment]
Alternatively can install GLPK via conda.
Need to add the conda-forge channel.

conda config --add channels conda-forge
conda install glpk

https://anaconda.org/conda-forge/glpk/files

**Comment by snorfalorpagus** [comment]
I'll add these comments to the installation document. I think the gist is:

- You need to use the right version of MSVC for the version of Python you have
- You need GLPK installed, with the library and headers in the right place. A binary is available.
- Anaconda and conda-forge make this simpler (and is how we develop internally).

**Comment by snorfalorpagus** [comment]
Resolved by #396.
