### ISSUE TITLE
Wrapped cython calls in GLPK solver

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#338]
Here's some output from a recent profile of a big model. The 53s of the solve is in the main solver function. 39s is inside the function, but 14s (~25%) is in calls to other functions.

```
 ncalls  tottime  percall  cumtime  percall filename:lineno(function)
10600   38.932    0.004   53.300    0.005 pywr\solvers\cython_glpk.pyx:353(_solve_scenario)
```

Look at the calls from `_solve_scenario` we can see a bunch are "wrapped". This means they are not C calls, but are dropping to Python space instead. This happens to two functions,

1. `commit` is [called from an untyped object.](https://github.com/pywr/pywr/blob/master/pywr/solvers/cython_glpk.pyx#L472)
2. `get_cost` is called from a typed object, but that type is `AbstractNode` which doesn't have a cdef'd `get_cost`. This is only defined from `Node` upwards.

Fixing these should improve performance a little.

```
   Ordered by: internal time
   List reduced from 315 to 1 due to restriction <'_solve_scenario'>

Function                                           called...
                                                       ncalls  tottime  cumtime
pywr\solvers\cython_glpk.pyx:353(_solve_scenario)  ->  212000    0.017    0.017  pywr\_core.pyx:164(__get__)
                                                      4494400    1.053    2.007  pywr\_core.pyx:292(commit (wrapper))
                                                      4293000    1.024    1.346  pywr\_core.pyx:352(get_cost (wrapper))
                                                      4346000    1.387    1.557  pywr\_core.pyx:377(get_min_flow)
                                                      4346000    1.561    5.756  pywr\_core.pyx:404(get_max_flow)
                                                        95400    0.038    0.134  pywr\_core.pyx:598(commit (wrapper))
                                                        95400    0.037    0.560  pywr\_core.pyx:602(get_cost (wrapper))
                                                        95400    0.031    0.136  pywr\_core.pyx:607(commit (wrapper))
                                                        95400    0.034    0.947  pywr\_core.pyx:611(get_cost (wrapper))
                                                       106000    0.032    0.474  pywr\_core.pyx:676(get_cost (wrapper))
                                                       106000    0.040    0.040  pywr\_core.pyx:703(get_min_volume)
                                                       106000    0.037    0.037  pywr\_core.pyx:721(get_max_volume)
                                                      4452000    0.412    0.412  pywr\solvers\glpk.pxi:13(constraint_type)
                                                      8692000    0.761    0.761  pywr\solvers\glpk.pxi:35(inf_to_dbl_max)
                                                        42400    0.056    0.090  stringsource:643(memoryview_cwrapper)
                                                        42400    0.013    0.013  stringsource:649(memoryview_check)

```

**Comment by snorfalorpagus** [comment]
To do this I think we'd need to change the `all_nodes` and `nodes_with_cost` lists to a typed array. I can't remember if I didn't do this at the time because I was lazy or if there was some other reason.

**Comment by jetuk** [comment]
For the first the easiest fix is to use `node` instead of `_node` because this typed with a `cdef get_cost`. However this would need to split the `Node` from the `Storage`. 

It might be better to `cdef get_cost` on `AbstractNode` but return 0.

**Comment by snorfalorpagus** [comment]
My reason for not putting `get_cost` on `AbstractNode` initially is that it's not valid for all nodes to have costs (at least currently).

**Comment by jetuk** [comment]
Sure, but could it just raise `NotImplementedError` by default?

**Comment by snorfalorpagus** [comment]
Has this been resolved with the recent changes?

**Comment by jetuk** [comment]
Yes they both have.
