### ISSUE TITLE
ArrayIndexedScenarioMonthlyFactorsParameter needs JSON support

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#339]
See the change in value() made to MonthlyProfileParameter - this was an optimisation that should be copied across to the scenario variable version.

Also... wow. What a parameter name...

**Comment by jetuk** [comment]
It also needs JSON support

**Comment by snorfalorpagus** [comment]
The original issue was resolved in #340. You're right though - it needs JSON support.
