### ISSUE TITLE
Ensemble ensemble ensemble!

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#341]
The members of a `Scenario` should be called ensembles! Then we have combinations of ensembles. Some of internal variable names should be changed to reflect the distinction between `Scenario` and an ensemble.

**Comment by snorfalorpagus** [comment]
I know we've had problems with this terminology. Isn't the collection itself the ensemble?

Example usage: http://ukclimateprojections.metoffice.gov.uk/23222
> When a global climate model is run to provide a projection of future climate it produces a 'simulation'. Multiple simulations form an ensemble.

**Comment by snorfalorpagus** [comment]
This use of "ensemble" was criticised in the paper.
