### ISSUE TITLE
TablesRecorder doesn't seperate mulitple scenarios in to different dimensions

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#353]
Take this example.

```
        "scenarios": {
            "weather": {
                "size": 200
            },
            "socio-economic": {
                "size": 4
            }
        }
```
The shape of the arrays in a `TablesRecorder` is currently `(number_of_timesteps, 800)`. Should it be `(number_of_timesteps, 200, 4)`. However this implies some ordering of the scenarios which isn't necessarily deterministic given the dictionary above.

**Comment by snorfalorpagus** [comment]
Interesting. I'll have to think about this!

**Comment by jetuk** [comment]
We could make scenarios a list with a name key?

**Comment by jetuk** [comment]
In fact the underlying `ScenarioCollection` uses a list. So this is just a JSON issue.

**Comment by snorfalorpagus** [comment]
In that case I'm happy to modify the JSON syntax to a list, e.g.

```
"scenarios": [{"name": "weather", "size": 200}, {"name": "socio-economic", "size": 4}]
```

**Comment by jetuk** [comment]
And happy with scenarios + 1 dimensional output arrays?

**Comment by snorfalorpagus** [comment]
We already have this a little with the TablesRecorder which has a multi-column (I think?).

I guess this would impact all of the recorders, e.g. `NumpyArrayNodeRecorder` currently has 2 dimensions (timesteps, combinations). We'd be moving to (timesteps, *scenarios). Does this make the recorder code more complicated? Currently in update we do:

```
for i in range(self._data.shape[1]):
    self._data[ts._index,i] = self._node._flow[i]
```

Where `i` is the scenario "global id". This would need to handle more dimensions?

From the end user's perspective though, indexing becomes easier, e.g. `recorder.data[:, 0, 3]` for the 0th weather scenario, 3rd socio-economic scenario.

**Comment by jetuk** [comment]
This is true. It's a call to `np.reshape` to get it in the correct format. `TablesRecorder` is only 2D.

**Comment by jetuk** [comment]
I should also say the reshape call should not be much overhead because it's already contiguous in memory.

**Comment by snorfalorpagus** [comment]
Do we keep the internal arrays 2D, but provide a method to access them in as ND? I think you're right in thinking the overhead of reshape is small. The `_data` implies the user shouldn't be accessing this directly anyway.

**Comment by jetuk** [comment]
TablesRecorder is special because it saves to disk. The others could give you the data in either further. I think the tables arrays should be nd though. And a scenario table should be added so you know the dimensions.

**Comment by jetuk** [comment]
I'm just implementing this. The `to_dataframe` method on the `NumpyArrayNodeRecorder` creates a `MultiIndex` so this feature is essentially already available.
