### ISSUE TITLE
Add a simple MaxParameter and NegativeParameter

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#362]
A common pattern seems to be a inflow series with negative values for `Storage` nodes. It would be best if we could consume the single input timeseries instead of splitting the +ve and -ve bits into their own series. I suggest a simple `MaxParameter` (more efficient that using `AggregatedParameter`) to do the `max(inflow, 0)`, and a `NegativeParameter` to do take the -ve of another parameter. This latter one can be used for the output node. 

I did consider a way to have a single node apply this, but it doesn't really work due to the directional nature of the graph. So you'd still need to make the input and output nodes separately.

**Comment by snorfalorpagus** [comment]
This seems reasonable to me. To add a little more flexibility you could make the number it compares to a variable, which defaults to 0. I don't think that adds anything to the speed? Should it be MinParameter?

**Comment by jetuk** [comment]
I don't think so? Easy enough to add one for completeness though.

**Comment by snorfalorpagus** [comment]
I think I misunderstood. You're suggesting that `NegativeParameter` would do `-inflow`? As opposed to `MinParameter` which would do `min(inflow, 0)`.

I was thinking that if we have a single timeseries representing net flow (say, to a reservoir, where a negative flow represented a reduction in storage), we could use an Input node with the MaxParameter and an Output node with the MinParameter. I guess you could also do MaxParameter(NegativeParameter) for the output, but that would be less efficient?

**Comment by jetuk** [comment]
Yes, `NegativeParameter` would do `-inflow`.

You hit the nail on the head. You need to do Max(Negative) to get it to work. See example JSON below. I think this makes most sense with the names discussed. It would be easy to do a `MaxNegativeParameter` that combines both for efficiency.

```
        {
          "type": "max",
          "parameter": {
            "type": "negative",
            "parameter": "my_parameter"
          }
        }
```

**Comment by snorfalorpagus** [comment]
OK. Now I get it. `MinParameter` would still return a negative, which isn't what we need. I'm happy for these parameters to be included.

It's a shame we can't have something more generic - some sort of simplex expression parsing, but that still has the speed of cython.
