### ISSUE TITLE
Catchment flow getter and setter are unrelated

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#366]
There is a shortcut to set the min and max flow at the same time for `Catchment` nodes, like this:

```
catchment.flow = 42
```

However, the getter for the `flow` attribute is used to store the flow at the end of the timestep. This is not sensible.

https://github.com/pywr/pywr/blob/master/pywr/domains/river.py#L42

**Comment by jetuk** [comment]
This is clearly the best API ever.

**Comment by jetuk** [comment]
the `load` method also uses `None` for the default flow which is not a permitted value.  It should be `0.0`

**Comment by snorfalorpagus** [comment]
I can't think of a good alternative to the current setup. `Catchment.fixed_flow` or `Catchment.eq_flow` are awkward.
