### ISSUE TITLE
Add warning (or error) if factors in AggregatedNode a very small

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#371]
It is possible to create an ill-conditioned LP by supplying very small factors to `AggregatedNode`. This results in the following and quite an unstable model,
```
Warning: basis matrix is ill-conditioned (cond = 7.93e+014)
7%, 1106 steps/second
Warning: basis matrix is ill-conditioned (cond = 7.64e+014)
8%, 1124 steps/second
9%, 976 steps/second
Warning: basis matrix is ill-conditioned (cond = 7.93e+014)
Error: basis matrix is singular to working precision (cond = 7.22e+015)
```

Solution is to not provide small factors. Solver or the `AggregatedNode` class should warn about this. The problem is caused by dividing by the small factor and creating a constraint matrix entry with a very large value (~1e16).

**Comment by snorfalorpagus** [comment]
That seems reasonable to me. Can you suggest a minimum value? 1e-5?
