### ISSUE TITLE
Default value of agg_func in recorders is "mean"

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#376]
Following from comment in #355.

The default value of agg_func in recorders is "mean". Should this be None? Not all recorders even have an agg_func.

**Comment by jetuk** [comment]
All `Recorders` do have an `agg_func`. The current API is as follows,

- `Recorder.values` is meant to return a single value for each scenario.
- `Recorder.aggregated_value` is meant to return a aggregated value across `Recorder.values`

**Comment by snorfalorpagus** [comment]
OK. I hadn't understood how it worked. We need to write some more documentation...
