### ISSUE TITLE
Circular reference with group control curves

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#380]
> [‎07/‎02/‎2017 12:40] Arnott, Joshua: 
> I came across an issue with a circular reference in Pywr yesterday.
> I tried to set the cost of a reservoir to a control curve parameter which used the storage from an aggregated storage which included the original reservoir.
> It didn't like that.
> [‎07/‎02/‎2017 12:40] Tomlinson, James E: 
> I had the same thing this morning
> FYI I came across it ... and worked around it
> [‎07/‎02/‎2017 12:41] Arnott, Joshua: 
> I just put the cost on the WTW instead.
> [‎07/‎02/‎2017 12:41] Tomlinson, James E: 
> If you set it to the node directly it works
> [‎07/‎02/‎2017 12:41] Arnott, Joshua: 
> In Python-space?
> [‎07/‎02/‎2017 12:42] Tomlinson, James E: 
> In JSON
> [‎07/‎02/‎2017 12:42] Arnott, Joshua: 
> You mean not in the parameters section?
> [‎07/‎02/‎2017 12:42] Tomlinson, James E: 
> Yes

**Comment by jetuk** [comment]
We discussed this further and there was not an obvious answer to this problem. For now I guess we should have an example / test that shows how this is broken.

**Comment by snorfalorpagus** [comment]
I think adding a failing test (with mark.xfail and a comment) is the way forward for now.
