### ISSUE TITLE
Add git hash to builds

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#389]
It would be useful in addition to the `__version__` string if we include the git hash in the builds.

**Comment by jetuk** [comment]
And added it to the `ModelResult` object

**Comment by jetuk** [comment]
Is this the best way of doing this?

http://stackoverflow.com/questions/14989858/get-the-current-git-hash-in-a-python-script

**Comment by snorfalorpagus** [comment]
Something like that yes. Part of the install process should copy it into a
text file in the module folder. You can then read that when the module
loads.
