### ISSUE TITLE
Scatter some logging calls about the place

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#390]
A good idea?

**Comment by snorfalorpagus** [comment]
What did you have in mind?

**Comment by jetuk** [comment]
Nothing in particular, just wondered if we should.

**Comment by snorfalorpagus** [comment]
I agree that this would be useful. I've just been hit with this:

```
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/baseline/block0_values``
```

No indication which file this relates to. With some debug messages it would be easy.

**Comment by jetuk** [comment]
#533 probably addressed sufficiently for now. Anything additional can be raised in new issues or PR.
