### ISSUE TITLE
Anaconda organisation

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#398]
I've created an organisation on anaconda.org for future releases of Pywr, so that I don't have to spell snorfalorpagus to people over the phone as often.

https://anaconda.org/Pywr/

I propose we work towards a 0.2 release this/next week and aim to do more frequent numbered releases going forward.

**Comment by snorfalorpagus** [comment]
Need to notify users of the new location.

Also need to decide where the lpsolve anaconda package should live. Currently it's on my channel. Should it move to pywr? Ideally I'd like it on conda-forge, but there is some effort involved in doing that.

**Comment by snorfalorpagus** [comment]
Which platforms should we commit to doing builds for? I don't think we need to do everything.

* OS: windows / linux / mac
* NumPy: 1.10, 1.11, 1.12
* Python: 2.7, 3.4, 3.5, 3.6
* OLDGLIBC - specific to manchester cluster

I can't be bothered with mac builds as I'm the only one that uses it (currently).

I don't know which versions of numpy we should support. Is there a reason to support < 1.12?

We've talked about dropping Python 2.7 in general. I don't plan on doing a build for it. We're using 3.4 on Windows because of MSVC, although we should explore mingw more I think - it'd be nice to be on 3.6.

**Comment by jetuk** [comment]
Does mingw work reliably? Can't we just use the updated version of MSVC?

I am not precious about 2.7 any longer. I am not sure we have a good reason to keep it, but nothing too hard in supporting it either at the moment. I can't think of any >=3.4 features that we are desperate to use. I suppose it means we can drop the requirement for `six`.

Supporting numpy versions isn't hard as we're not using bleeding edge features. This is mostly a cython thing so it could be sensible to support the same versions as cython in Conda?

**Comment by snorfalorpagus** [comment]
It might make sense to set up a build system akind to conda-forge. We could automate all the builds that way, for windows and linux.

**Comment by jetuk** [comment]
We would run this ourselves?

**Comment by snorfalorpagus** [comment]
I was thinking of using Travis:

https://github.com/pywr/pywr-deploy
https://travis-ci.org/pywr/pywr-deploy/builds/204416991
https://anaconda.org/Pywr/pywr/files

**Comment by snorfalorpagus** [comment]
I've cleaned things up a bit and added support for appveyor, so we have Linux and Windows builds now. Doing the next build should be as easy as updating the tag and build number in the recipe and pushing.

Further discussion re: builds should go on the pywr-deploy repo here: https://github.com/pywr/pywr-deploy
