### ISSUE TITLE
Cython docstrings not in sphinx autodoc

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#404]
Should be easy to fix. Sphinx autodoc isn't picking up any of the cython classes.

https://github.com/abingham/cython-sphinx-example

**Comment by jetuk** [comment]
I think the new `pywr.recorders` subpackage is also missing.

**Comment by snorfalorpagus** [comment]
@jetuk Did you build the docs yourself? Those on the website haven't been updated.

**Comment by jetuk** [comment]
No, I haven't I can do though? Might as well fix this first.

**Comment by jetuk** [comment]
Solved in #573
