### ISSUE TITLE
ScenarioCollection.multiindex doesn't use scenario slices

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#409]
ScenarioCollection.multiindex doesn't respect the new slices property of scenario objects. This results in indexes that aren't the right shape for the data.

**Comment by snorfalorpagus** [comment]
ScenarioCollection.shape is also wrong. This causes problems here:

https://github.com/pywr/pywr/blob/master/pywr/recorders/recorders.py#L272

**Comment by jetuk** [comment]
`ScenarioCollection.shape` is still broken.

**Comment by snorfalorpagus** [comment]
Does the shape even make sense when user combinations are defined? It's not homogeneous.

**Comment by jetuk** [comment]
As we discussed. No, it doesn't. `ScenarioCollection.shape` should raise an error if given user combinations. What sort of error makes sense?

**Comment by snorfalorpagus** [comment]
NumPy uses this exception, which is related:

```
ValueError:shape mismatch:objects cannot be broadcast to a single shape
```

Just a value error with a message.
