### ISSUE TITLE
TotalDeficitNodeRecorder is broken

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#411]
The current implementation of `TotalDeficitNodeRecorder` has a bug. The `max_flow.value` gets called in `save` which is called after `after`. This means the parameter could be in an intermediate state - with the current timestep, but tomorrow's state.

https://github.com/pywr/pywr/blob/d6ad8b5eed65bddb00d20f677ff5196fe8bd9ccd/pywr/recorders/_recorders.pyx#L828-L842

A possible solution to this is to cache the max_flow variable during a (as yet unimplemented) `before` method on the recorder.

Another solution would be to cache all parameter values (this would tie into #205). This suggests the cached value should be *on* the parameters, not in an array in the solver, so that others can access it.

This is a fairly general issue for any recorder that tries to access parameter values during save.

See also #320.

`DeficitFrequencyNodeRecorder` also has this issue.

**Comment by snorfalorpagus** [comment]
This is addressed in #323 (node.get_max_flow uses parameter.get_value).

**Comment by jetuk** [comment]
Is it tested?

**Comment by snorfalorpagus** [comment]
Not in the context it used to fail in, no.
