### ISSUE TITLE
Inconcsistent behaviour in Model.run when using "until_xxx" keywords

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#421]
A couple of inconsistencies in `Model.run`

When the timestepping loop is terminated by either `until_date`, `until_failure` or `timestep.datetime > self.timestepper.end` then the function immediately returns a `Timestep`. This should return a `ModelResult` object.

Also should this `timestep.datetime > until_date` by a `>=` test?

**Comment by snorfalorpagus** [comment]
Do we want to continue to support these features? I've never actually used them. Currently there are no parameters that trigger the failure condition.

**Comment by jetuk** [comment]
I've just used `until_date` in one of the tests in the tree branch.

Another problem is that `Model.finish()` is not called if these happen. I don't know if all parameters behave OK if they don't get to the end. I.e. some might have zeroes allocated arrays that are not populated, but then pollute some statistics during `finish`.

**Comment by snorfalorpagus** [comment]
When I wrote those conditions I was thinking in the context of `model.step`, where the user might want to continue running the model from that point. In that case it doesn't make sense to call finish. If you want to run the model to a particular date you should set `model.timestepper.end`. Stopping on failure is a bit problematic - what state will some of the arrays be in?

**Comment by jetuk** [comment]
OK then let's not support this at all.
