### ISSUE TITLE
Draw D3 graph directly from JSON

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#438]
It would be nice if we could draw the D3 schematic without having to actually load the Model. All the information is available in the JSON.

**Comment by snorfalorpagus** [comment]
It's difficult to work out if nodes are `allow_isolated` or `virtual` as these are instance attributes, not class attributes. We could transfer them to class attributes. This means they'd be stored as Python objects, but I don't think they are used anywhere that's performance critical.

**Comment by jetuk** [comment]
I don't think they are either.

**Comment by snorfalorpagus** [comment]
@Batch21 has this working - expect a PR soon. :)

**Comment by snorfalorpagus** [comment]
This has been implemented. You can pass a filename directly to `draw_graph`.
