### ISSUE TITLE
Implement absolute control curve parameters

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#439]
The current control curves all assume proportional control curves. It would be feasible to abstract their behaviour and make choice regarding the use proportional or abstraction volume.

**Comment by snorfalorpagus** [comment]
Can you explain again why we can't just wrap the control curves in a conversion? Something to do with negative volumes?

**Comment by jetuk** [comment]
The work that has been done with these is using a storage node with a poorly defined upper and lower limit (groundwater). It is ugly to convert the control curves to a unit that is non-intuitive for those storage nodes. Much handier to work in the absolute values. 

Also it might be useful for optimisation where control curves should stay in the same absolute position as an increase in storage is optimised.

**Comment by jetuk** [comment]
No interest in this currently - closing. Re-open if someone wants to implement it.
