### ISSUE TITLE
Compound node for transfers

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#449]
I've been using a compound node which contains a storage with zero volume to reduce the number of routes in highly interconnected models.

The node looks like this, where X and Y are actually many nodes:

```
X ->- | -- storage ->- link -- | ->- Y
```

Internally the storage is an input and output which crucially are *not* connected. This means that for X1..3 and Y1..3 there are 6 routes in the model (3+3), not 9 (3*3).

The node uses iter_slots to expose the correct node when connecting, so you can do this:

```
T = Transfer(max_flow=1.5, cost=10)
X1.connect(T)
T.connect(Y1)
```

I'll submit a PR for this on Monday. What do you think about the node name `Transfer`? It's really applicable anywhere you want to collapse the routes, not just inter-zone transfers (which is what it was designed for).

**Comment by jetuk** [comment]
I think that the name is fine. I would like to understand how this changes the LP internally. In theory it's the same LP so is it just more compact? Is the overhead in just iterating the routes before & after solve, and solving the two different LP is very similar.

Also i wondered whether a similar class would be useful for bi-directional transfers.

**Comment by snorfalorpagus** [comment]
I'm not sure the reason for the speed up. Obviously it reduces the number
of variables and only adds one constraint. It'd be interesting to profile
it.

**Comment by jetuk** [comment]
This should be relatively easy to test in one of the existing benchmarks I have written.

**Comment by snorfalorpagus** [comment]
Posting here so I don't lose it.
```
from pywr.nodes import Node, Storage, Link

class Transfer(Node):
    """Compound node used to reduce the number of routes in a model
    """
    allow_isolated = True

    def __init__(self, model, name, min_flow=0.0, max_flow=None, cost=0.0, *args, **kwargs):
        storage_name = "{} (storage)".format(name)
        link_name = "{} (link)".format(name)
        assert(storage_name not in model.nodes)
        assert(link_name not in model.nodes)
        self.storage = Storage(
            model,
            name=storage_name,
            min_volume=0,
            max_volume=0,
            initial_volume=0,
            cost=0,
        )
        self.link = Link(
            model,
            name=link_name,
            min_flow=min_flow,
            max_flow=max_flow,
            cost=cost,
        )

        self.storage.connect(self.link)

        super(Transfer, self).__init__(model, name, *args, **kwargs)

    def min_flow():
        def fget(self):
            return self.link.min_flow
        def fset(self, value):
            self.link.min_flow = value
        return locals()
    min_flow = property(**min_flow())

    def max_flow():
        def fget(self):
            return self.link.max_flow
        def fset(self, value):
            self.link.max_flow = value
        return locals()
    max_flow = property(**max_flow())

    def cost():
        def fget(self):
            return self.link.cost
        def fset(self, value):
            self.link.cost = value
        return locals()
    cost = property(**cost())

    def iter_slots(self, slot_name=None, is_connector=True):
        if is_connector:
            # connecting FROM the transfer TO something else
            yield self.link
        else:
            # connecting FROM something else TO the transfer
            yield self.storage.outputs[0]

    def after(self, timestep):
        self.storage.commit_all(self.flow)
        self.link.commit_all(self.flow)
        super(Transfer, self).after(timestep)
```

**Comment by snorfalorpagus** [comment]
One issue with this is that you can't easily record the flow - you need to access the subnode. I'm not sure if after is needed?
