### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#451]
I think it might be useful to be able to create arbitrary constraints in the LP, e.g.

sum(A + 0.5*B) <= C + 1000

Where A, B and C are routes/nodes.

What's the best way to expose a API for this? Something similar to AggregatedNode? Or an extension of it?

This would be useful where we want to create an abstraction constraint, but don't want to use costs as it shouldn't impact upstream release.

**Comment by snorfalorpagus** [comment]
I guess the node would look something like this:

```
{
    "type": "constraint",
    "nodes": ["A", "B", "C"],
    "matrix": [1.0, 0.5, -1.0],
    "constraint": "LE",
    "rhs": 1000.0
}
```

It's not really a node - it doesn't have a `max_flow` or `cost` in the same way AggregatedNode does. Does it still belong in nodes?

**Comment by jetuk** [comment]
Could the RHS by a `Parameter`?

**Comment by snorfalorpagus** [comment]
That would require updating the constraint bound only, not the matrix, so I think that would be OK?

**Comment by jetuk** [comment]
Yes, exactly. It gives a bit more flexibility. I guess `Constraint` would be a subclass of `Component`, or does it not need to be in the hierarchy?

**Comment by snorfalorpagus** [comment]
I agree - I think it makes sense to make it a `Component`.

**Comment by jetuk** [comment]
I'm not sure this is needed since min/max flow constraints were added to `AggregatedNode` in #462
