### ISSUE TITLE
It should be possible to define initial volume in percentage terms

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#453]
I suggest a second attribute to `Storage`. We would have to have `initia_volume` default to `nan` and check the `initial_volume_pc` in that case. If both are `nan` then error.

```
s = Storage(initial_volume_pc=1.0)
assert s.initial_volume_pc == 1.0
```

**Comment by snorfalorpagus** [comment]
This should be possible now that we have access to the maximum volume during reset.

**Comment by snorfalorpagus** [comment]
I should mention, although I started work on this I stopped when I hit #470. I didn't save what I'd done.
