### ISSUE TITLE
Storage max volume parameter is accessed before initialisation

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#470]
The `setup`/`reset` method on nodes is called before the component tree is evaluated. See:

https://github.com/pywr/pywr/blob/0b12cadb34b7207737ba53b258168fb67cceb353/pywr/model.py#L607-L621

If the maximum volume of a `Storage` node is defined by a parameter, the current percent full is mis-calculated in the initial timestep, as the parameter is accessed during the `Storage.reset` method *before* the parameter has been evaluated.

I came across this while trying to implement #453, which also requires the maximum volume.

The solution to this seems to be to include the nodes in the component tree, which I think we have discussed as a possibility already.

**Comment by snorfalorpagus** [comment]
I started work on trying to make `Node` into a subclass of `Component`. Most of the tests pass with only a few changes. However...

The difficult part will be maintaining the parameters relationship with the nodes. When a node property is set to a parameter it and edge needs to be added to the tree. When another parameter is set to the same property the edge must be removed, *but only if it's not also used by another property of the same node*.

A possible solution would be to add a tuple to the tree in the form: `G.add_edge((node, "max_flow"), parameter)`.

I wonder if the whole thing is complicated by some nodes needing to call setup before the parameters, and some after? Not sure if this is the case - just thinking aloud.

**Comment by snorfalorpagus** [comment]
The cost of a reservoir may depend on it's volume (storage before parameter), but the volume is defined by the max volume (parameter before storage). This suggests it *does* need to go into the tree. I still get the feeling it's more complicated than that though.

**Comment by jetuk** [comment]
> The cost of a reservoir may depend on it's volume (storage before parameter), but the volume is defined by the max volume (parameter before storage). 

I don't think this is a problem. The cost uses previous time-steps volume (and max volume) for its calculations. It's not until `current_pc` is updated at the end of this time-step that the correct max volume is needed. Which works as advertised.

**Comment by snorfalorpagus** [comment]
We've agreed a work-around: in the reset method of Storage, check if the max_volume parameter is defined and if it has any children. If it does, raise an exception. If it doesn't, call calc_values immediately.

We should also add a test for this. Create a ConstantParameter = 50 and set it to the max_volume of a Storage. Set the initial volume to 25. Call setup/reset on the Storage, then check the _current_pc. It should be 0.5, but will often be 0.0 or NaN if the constant parameter was uninitialised when it was accessed.

**Comment by snorfalorpagus** [comment]
Tag #488.

**Comment by jetuk** [comment]
I've hit this again. @snorfalorpagus where is the work you did before on making nodes components. I am debating whether this should be done or not.

**Comment by jetuk** [comment]
Once again the work around here is quite limiting for non-trivial max_volume parameters. I would like to propose a different work around whereby the user specifies both `initial_volume` and `initial_volume_pc`. These values are then used as is for the first time-step.

**Comment by jetuk** [comment]
> I would like to propose a different work around whereby the user specifies both initial_volume and initial_volume_pc

This was implemented in v1.8.0 (#690). Closing this issue now.
