### ISSUE TITLE
Create a CHANGELOG.txt

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#472]
It would be useful to include a list of changes in releases.

**Comment by jetuk** [comment]
How would we manage this? Update the change log in relevant PR?

**Comment by snorfalorpagus** [comment]
Admittedly, more frequent releases make this less of a difficult task. Either update in the PR, or troll throught commits during release.

**Comment by jetuk** [comment]
You removed this from 0.4 milestone?

**Comment by jetuk** [comment]
Should this be in a separate file or just in readme?

**Comment by snorfalorpagus** [comment]
I think it should be a separate file as it can get very long.

e.g. https://github.com/Toblerity/Fiona/blob/master/CHANGES.txt

I removed it from the previous milestone because I couldn't be bothered to write it and didn't want to block the release.

**Comment by snorfalorpagus** [comment]
Changelog is available here:

https://github.com/pywr/pywr/blob/master/CHANGELOG.md
