### ISSUE TITLE
AnnualTotalFlowRecorder - to be included/cythonised?

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#491]
```
class AnnualTotalFlowRecorder(Recorder):
    """
    For each scenario, record the total flow in each year

    Shape: (years, scenario combinations)
    """
    def __init__(self, model, name, nodes, *args, **kwargs):
        super(AnnualTotalFlowRecorder, self).__init__(model, name=name, *args, **kwargs)
        self.nodes = nodes

    def setup(self):
        super(AnnualTotalFlowRecorder, self).setup()
        timestepper = self.model.timestepper
        self.num_years = timestepper.end.year - timestepper.start.year + 1
        self.ncomb = len(self.model.scenarios.combinations)
        self.data = np.zeros([self.num_years, self.ncomb], dtype=np.float64)

    def reset(self):
        self.data[...] = 0
        self.current_year = None
        self.start_year = self.model.timestepper.start.year

    def after(self):
        timestep = self.model.timestepper.current
        index = timestep.year - self.start_year
        for node in self.nodes:
            flow = node.flow
            self.data[index, :] += node.flow

    def values(self):
        return np.array(self.data, copy=True)
```

**Comment by laurenpetch** [comment]
@jetuk  @snorfalorpagus 
did this ever get included? i have a couple of other recorders from the UU model that I can't find in the code but might be useful to have, e.g.:

```
class AnnualCountIndexThresholdRecorder(Recorder):
    """
    For each scenario, count the number of times a parameter exceeds a
    threshold in each year.

    Shape: (years, scenario combinations)
    """
```

**Comment by jetuk** [comment]
I can't see any references to it in this repo besides this issue. Therefore, I guess it has not made its way in here. Would be good if you can do a PR with these? I guess it would be good to Cythonise them if possible. 

One issue with what was originally posted is the use the `values()` function. In Cython this is defined to return `double[:]`, but here it is returning a 2D array.

**Comment by laurenpetch** [comment]
Yes, i'll have a go. Should I be trying to get it to work with the `values()` function to return a 1D array then or is there another way around that?

**Comment by jetuk** [comment]
The API specifies that `.values()` should return 1D array, and that `aggregated_value()` will aggregate over those values for contrain & objective purposes. If you need to use this parameter for an objective or constraint then it should to follow that pattern. 

Generally the recorders apply some sort of temporal aggregation in the `values()` method to give a single number for each scenario. If you want to have access to the full array then there are two approaches in existing recorders:

1. Add a property that gives access to a copy of the internal memoryview (e.g. `.data`). In the Python example one would just get access to the numpy array. However, if you Cythonise this that should become a memory view.
2. Add a `to_dataframe()` method which wraps the data array in `pandas.DataFrame`. This would give you a nice column index derived from the scenarios also.

**Comment by jetuk** [comment]
I see you've done (1) in the WIP commit.

```
    property data:
        def __get__(self):
            return np.array(self._data, dtype=np.float64)
```
