### ISSUE TITLE
LE and GE constraints for aggregated nodes

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#506]
The aggregated node allows you to constrain the flow in nodes as a fixed ratio, e.g.

A * a - B * b = 0

For the special case where the number of nodes being aggregated, it would be useful to have less than / greater than constraints, e.g.

A * a - B * b <= 0
A * a - B * b >= 0

**Comment by jetuk** [comment]
I think #603 enables this?

**Comment by jetuk** [comment]
Done in #603.
