### ISSUE TITLE
Potential non-determinism caused by storage nodes

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#507]
I believe I've found a problem with the storage constraints in two cases. Both due to floating point rounding errors.

1. When `min_volume == max_volume` (e.g. zero as in `BreakLink`). The solver can return a very small but non-zero value (e.g. 1e-15) which then results in some very small constraint RHS values. In this case there should be a short-cut to set the constraint to zero RHS value.
2. Generally the `Storage` node accumulates floating point rounding errors during `after` when the volume is updated. This again can result in very small RHS values when the storage is very close to either min or max volume. A small tolerance on this should set the current volumes to these limits exactly.

**Comment by snorfalorpagus** [comment]
Fixed in #500.
