### ISSUE TITLE
Variable length timesteps

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#510]
It would be useful to support variable length timesteps, specifically to allow the model to be run on a 12-month or 52-week year, rather than approximations (28-days or 7 days).

I don't think this will be too difficult although we'd need to review the code to identify any places where the timestep length is assumed to be fixed.

- [ ] Modify `Timestepper` to produce weekly/monthly timesteps

**Comment by jetuk** [comment]
A related, but more complex, improvement would be adaptive timesteps. This would have be based on some kind of predictor-corrector approach common in ODE solvers. 

Also what about sub-daily timesteps?

**Comment by snorfalorpagus** [comment]
Some thoughts about what is required to do weekly/monthly timesteps:

* Calculation of length becomes more complex
* Some start dates are not valid (e.g. "1920-01-08" is OK but "1920-01-09" is not)
* `Timestepper.delta` can't be a pandas.Timedelta any more, as delta is variable.
* Calculation of `Timestepper.datetime_index` can't use pandas.date_range for the same reason

Should we be switching to `pandas.Period` from `pandas.Timestamp`? I know we've discussed this before...

**Comment by snorfalorpagus** [comment]
@jetuk You mentioned you'd worked on this. Looking forward to the PR. :)

**Comment by jetuk** [comment]
No pressure!

**Comment by jetuk** [comment]
Closed in #675!
