### ISSUE TITLE
Version 0.4

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#512]
Is there anything major preventing a release of 0.4? If so please tag with the 0.4 milestone.

@jetuk

**Comment by jetuk** [comment]
I've had a quick look through some issues. I added a couple of documentation things that are low hanging to 0.4, and some more complex stuff to 0.5.

**Comment by snorfalorpagus** [comment]
Version 0.4 has been tagged (v0.4) and deployed to conda.
