### ISSUE TITLE
Storage node does not load area parameter from JSON

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#585]
`Storage` node does not appear to load the "area" parameter passed to it via JSON - see code for level.

https://github.com/pywr/pywr/blob/7b8515fb048a2a6e1900d60251e409a95da3c32d/tests/models/reservoir_evaporation.json#L18

https://github.com/pywr/pywr/blob/7b8515fb048a2a6e1900d60251e409a95da3c32d/pywr/nodes.py#L377

This doesn't actually break the behavior of the model, but is still a bug.

**Comment by jetuk** [comment]
Fixed in #587
