### ISSUE TITLE
Anaconda installation route not finding lpsolve package

### ISSUE THREAD

**Issue by AndyWillo** [pywr/pywr#599]
Anaconda installation route not finding lpsolve in current channels and aborting install

Should lpsolve be Lp_solve as I've been able to install directly that way, but that forces me to install all elements manually

Error below

Andy

>conda install pywr
Fetching package metadata .................
Solving package specifications:

PackageNotFoundError: Packages missing in current channels:

  - pywr -> lpsolve

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/pywr/win-64
  - https://conda.anaconda.org/pywr/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch>conda install pywr
Fetching package metadata .................
Solving package specifications:

PackageNotFoundError: Packages missing in current channels:

  - pywr -> lpsolve

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/pywr/win-64
  - https://conda.anaconda.org/pywr/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch

**Comment by jetuk** [comment]
Andy,

Thanks for this. I think we were using the `lpsolve` package on the "snorfalorpagus" channel. See: 

https://anaconda.org/snorfalorpagus/lpsolve

I wasn't aware of this version in conda forge. However, that should be better supported. I'll get this updated. 

In the meanwhile try the version from the channel above. 

James

**Comment by jetuk** [comment]
Actually this has already been done! It's just not in the last release. It should work when v0.5 is released which is just waiting on #584.

https://github.com/pywr/pywr/commit/21656b1491a9a591971d1bb561e7b237841a7428

**Comment by jetuk** [comment]
We've just released 0.5 so this should be fixed. If not please reopen.

**Comment by AndyWillo** [comment]
Great – will try on a fresh machine – I added your channel and it worked fine this morning
