### ISSUE TITLE
Duplicate conda recipes in pywr/pywr-deploy

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#600]
It's awkward having two conda recipes (one in `pywr` and one in `pywr-deploy`). It would be nice to avoid this somehow. There are some subtle differences between them though (e.g. the pywr-deploy uses a specific git_rev in order to build a specific tag, rather than master).

**Comment by jetuk** [comment]
Is the answer to this not to ditch `pywr-deploy` and then use a `deploy` job in this repo that only triggers on `tags: true` ?

**Comment by jetuk** [comment]
Decided against this. For a couple of reasons. We'll stick with the two recipes because we might want two different builds environments/configurations for testing and release. Perhaps we can revisit this at some point, but I will close it for now.
