### ISSUE TITLE
pypi distribution

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#613]
We should do a source release on pypi.

**Comment by jetuk** [comment]
Initial attempt here. 

https://pypi.org/project/pywr/0.5/

It uses the current README for the long description (I need to do the PR for this). It is also sdist only. Apparently binary wheels are broken on Linux.

**Comment by jetuk** [comment]
OK, so this will need some work. `setup.py` is broken with the git repo. I'll try to do a PR so we can do a v0.5.1 release quickly in pypi that actually works.

**Comment by snorfalorpagus** [comment]
Specifically, setup.py doesn't work when not run from a git repository as it tries to access the version. Traceback here:

```
$ pip install pywr-0.6.dev0.tar.gz 
Processing ./pywr-0.6.dev0.tar.gz
    Complete output from command python setup.py egg_info:
    fatal: not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-33kiv9d2-build/setup.py", line 143, in <module>
        git_hash = subprocess.check_output(["git", "rev-parse", "HEAD"]).rstrip().decode("utf-8")
      File "/home/snorf/miniconda3/envs/python36/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/home/snorf/miniconda3/envs/python36/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
    Using setuptools for setup!
```

This shouldn't be difficult to fix.

**Comment by snorfalorpagus** [comment]
Also need to configure the source distribution to include pyx files, as well as .c files. See how Fiona does this.

**Comment by jetuk** [comment]
So this was a mess. #614 was merged and also attempt to do pypi (and conda) deployment in this repo. Turns out building wheels for Linux is quite difficult and needs its own process. This process is semi-manually and is being added to `pywr-deploy`. The core problems here have been fixed in terms of generating a sdist and being able to generate wheels for pypi.

**Comment by snorfalorpagus** [comment]
We have a source distribution on pypi now:

https://pypi.org/project/pywr/#files

I've just successfully built and run this without doing anything special, so making this as done.

Binary wheels for the various combinations of OS / Python version can be handled in separate issues as they are likely to have their own specific needs.
