### ISSUE TITLE
Add Python 3.7 to CI

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#617]
Related to dropping 2.7 (#572) support and 3.4 (#548) in CI. We can also add 3.7. It is due to release on 2018-06-15, but we'll have to wait until there is support in conda and conda-forge. See here:

https://www.python.org/dev/peps/pep-0537/#schedule

**Comment by snorfalorpagus** [comment]
Python 3.7 is available from conda-forge now, but it could be a while before all the dependencies catch up.
