### ISSUE TITLE
Lots of open PR

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#636]
@snorfalorpagus @Batch21 @laurenpetch I'm going to try and get some of the open PR merged to master at the end of this week. I will go through them again myself before merging, but I think things are diverging a bit too much. If you have any comments or major concerns please flag them and I'll avoid those PR.

Let me know if you think this is a bad idea.

**Comment by Batch21** [comment]
Sorry I've not had much time to look at the PRs recently. I did have a quick look again at the marshmallow stuff at the weekend so I can have a more thorough look this week. Initial thoughts was that it is good to go.

**Comment by jetuk** [comment]
Thanks both.

**Comment by jetuk** [comment]
We've done a release.
