### ISSUE TITLE
Polynomial1DParameter doesn't set parameter parent/child relationship

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#637]
Fixed here, but might need to come out into it's own commit/PR if #586 isn't merged.

https://github.com/pywr/pywr/pull/586/files#diff-b0fd60b2d30175d03ecb93e965dc4ff0R47
@jetuk

**Comment by jetuk** [comment]
https://github.com/pywr/pywr/blob/85758fb3c402f29a700a314bc1e534b698a5ef6b/pywr/parameters/_polynomial.pyx#L57

This is not broken? Not sure what we were talking about the other day. It looks like the parent/child stuff is done correctly.
