### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#639]
I think it's time we did a 1.0.0 release.

https://semver.org/

Especially if we are planning to break backwards compatibility with the JSON documents in #611.

**Comment by jetuk** [comment]
I spoke with @Batch21 this morning. Plan is to merge #635, release next as v1.0.0. A merge of #641 would create v2.0.0 due to back incompatible JSON changes. We could also do a v1.1.0 release deprecating various things in the structure planned for v2.

**Comment by jetuk** [comment]
We've adopted semantic versioning with the release of v1.0.0.
