### ISSUE TITLE
Tests for invalid network structures.

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#64]
I assume our network has to be acyclic. The path finding algorithm only returns *simple* paths with no repeated nodes. So we need to check for this. `Node.connect` should raise an error if a cycle would be created by the connection?

**Comment by snorfalorpagus** [comment]
My intent was that the model could be cyclic, but only simple paths are evaluated. Consider the following system:
```
from pywr.core import Model, Link, Input, Output
from numpy.testing import assert_allclose

model = Model()

supply1 = Input(model, 'supply1')
supply2 = Input(model, 'supply2')

j1 = Link(model, 'j1', cost=0)  # downhill
j2 = Link(model, 'j2', cost=10)   # uphill, needs to be pumped

demand1 = Output(model, 'demand1', max_flow=5, cost=-999)
demand2 = Output(model, 'demand2', max_flow=5, cost=-999)

supply1.connect(j1)
supply2.connect(j2)
j1.connect(j2)
j2.connect(j1)
j1.connect(demand1)
j2.connect(demand2)

for supply in (supply1, supply2):
    for demand in (demand1, demand2):
        for route in model.find_all_routes(supply, demand):
            print(' -> '.join([node.name for node in route]))

for supply1_flow, supply2_flow in ([0, 10],[10, 0],[5, 5]):
    supply1.max_flow = supply1_flow
    supply2.max_flow = supply2_flow
    model.step()
    assert_allclose(demand1.flow, 5, atol=1e-7)
    assert_allclose(demand2.flow, 5, atol=1e-7)
```

The duplex connection between `j1` and `j2` could represent a single physical connection, that can be used in either direction.

**Comment by snorfalorpagus** [comment]
After discussion on the phone, we need to work out how to handle this:

```
supply1.connect(demand1)
demand1.connect(demand2)
```

Find out if we can replace the demand variable with a constraint, and apply the demand cost to the route instead.

**Comment by jetuk** [comment]
Have started issue #66 for the inline stuff which is different to the cycles.

**Comment by jetuk** [comment]
We also need to handle isolated nodes that are not on any valid route.

**Comment by snorfalorpagus** [comment]
Presumably this needs to be added to `Model.check`?
