### ISSUE TITLE
BreakLink __init__ method is broken

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#642]
The `__init__` method of `BreakLink` doesn't work as expected. The min/max flow is set, but then the super() init resets these values to default 0/inf. We didn't notice this earlier because the `BreakLink.load` method sets the min/max flow *after* the instance is created. We should fix this in #641.

**Comment by jetuk** [comment]
Noting that this is also a documentation issue as per the discussion in #652.
