### ISSUE TITLE
Enable embedsignature=true in Cython

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#644]
> embedsignature (True / False)
    If set to True, Cython will embed a textual copy of the call signature in the docstring of all Python visible functions and classes. Tools like IPython and epydoc can thus display the signature, which cannot otherwise be retrieved after compilation. Default is False.

https://cython.readthedocs.io/en/latest/src/reference/compilation.html#compiler-directives

Seems like this would be useful to turn on by default?

**Comment by snorfalorpagus** [comment]
Closed by #645.
