### ISSUE TITLE
Add a division parameter

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#651]
Add a Parameter to divide one parameter by another. I think this should be a separate parameter rather than an extension to `AggregatedParameter`.

**Comment by snorfalorpagus** [comment]
See #193. We'd need to explicitly set the numerator and denominator.

A more generic solution would be nice. Something like:

```
{
  "type": "equationparameter",
    "parameters": {
    "a": "aparameter",
    "b": "anotherparameter"
  },
  "equation": "a * b + 4"
}
```

There must be a symbolic library that makes this easy although it probably wouldn't be very quick.

**Comment by jetuk** [comment]
Gah I searched for "division"! This was a specific request from someone. 

See https://github.com/pywr/pywr/issues/553 for the expression based parameter.

I think both would be useful.

```
{
  "type": "division",
  "numerator": "aparameter",
  "denominator": "anotherparameter"
}
```
It might need some option to handle `ZeroDivisionError` (e.g. cast to a value such as 0.0).
