### ISSUE TITLE
Area parameter is not assigned to Storage

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#656]
https://github.com/pywr/pywr/blob/77d576ab45dfda867094cca4812d1221b1b86e2c/pywr/nodes.py#L305

This keyword is not assigned to `self.area`.

**Comment by avnish98** [comment]
I can do this one

**Comment by jetuk** [comment]
Great! It would be good if a test for this assignment is added to the existing surface area test:

https://github.com/pywr/pywr/blob/c9c86ceb0087d89ddf8b9e564073ac3423480c34/tests/test_run.py#L461

**Comment by avnish98** [comment]
@jetuk If I am understanding this right I have to add self.area attribute to Storage class and improve test
that in test_reservoir surface_area(). Right?

**Comment by jetuk** [comment]
Yes that's right. The change should be a one line addition to `__init__`
method. I.e. the same as the level one.

The change to the test could simply test that the node has a `.area`
property being a reference to the area parameter.

**Comment by avnish98** [comment]
@jetuk Ok, I am making a pull request thanks for help

**Comment by jetuk** [comment]
Thanks, I'll take a look later.

**Comment by jetuk** [comment]
Fixed in #657
