### ISSUE TITLE
Set cython language_level

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#685]
Cython has started issuing this warning. We should explicitly test and switch to `language_level=3` before it randomly happens.

```
FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/james/dev/pywr/pywr/parameters/_thresholds.pxd
```

**Comment by snorfalorpagus** [comment]
I did this for Fiona and didn't need to change anything in the main code.

https://github.com/Toblerity/Fiona/pull/677/commits/547bd0ce0531630ebb9e68e904933fe8d002df25

**Comment by jetuk** [comment]
So this was already done in: https://github.com/pywr/pywr/pull/645

I'll have to check why I got those warnings.

**Comment by jetuk** [comment]
I'm closing this as it is already in master. I must have been using an old branch or something.
