### ISSUE TITLE
Using an input to a virtual reservoir not connected to the network

### ISSUE THREAD

**Issue by BaptisteFrancois** [pywr/pywr#699]
Hi Pywr team!
I am trying to represent an accounting mechanism via a virtual storage. 
I have several questions related to this task. 

First, in the description of the virtualstorage class I found the definition of the 'factors' parameters confusing. I suspect a typo in the description. cf. below:

447    _factors: list of floats_
448            _List of factors to multiply node flow by. Positive factors remove_
449           _water from the storage, negative factors remove it._

My guess is that is should be ''negative factors **add** it''.

Besides, I am having trouble to account for the input to this virtual storage. For instance, my  virtual storage is:
``` json
{
	"name": "water_bank_reservoir",
	"type": "virtualstorage",
	"initial_volume": 560000,
	"max_volume": 570000,
	"nodes": [
		"water_bank_input",
		"tid_district",
		"mid_district"
	],
	"factors": [
		-1.0,
		1.0,
		1.0
	]
},
```
_tid_district_ and _mid_district_ are two links in my network with max_flow parameters defined via a dataframe.
My problem actually relates to the input _water_bank_input_ . The value of this input is defined via an aggregated parameter:

```json
"water_bank_inflow": {
	"type": "aggregated",
	"agg_func": "min",
	"parameters": [
		"natural_flow",
		"water_bank_entitlement"
	]
},
```
_natural_flow_ and _water_bank_entitlement_ are both defined in the parameter section via a dataframe.

Finally, my concern is that _water_bank_input_ is actually not physically linked to the modeled network, though I would like to use it as input to my virtual storage. I try several type of node to represent this 'virtual_input' with no success. 
For instance my last trial was to use a 'discharge' class:
```json
		{
			"name": "water_bank_input",
			"type": "discharge",
			"max_flow": "water_bank_inflow",
			"min_flow": "water_bank_inflow"
		},
```
I also tried, 'node', 'input', "catchment' ... 
Depending on the node class I consider, I run into different issue, ranging from an LP with no solution (e.g., with a 'catchment' class) or with a 'water_bank_input' being a time series filled with 0, while 'water_bank_inflow' is correct (e.g., with the generic 'node' class).
Any thoughts?
Thanks!

**Comment by BaptisteFrancois** [comment]
I think I solved my problem. I do not think I used the best way to do it though..
I have added a 'second network' with dummy link and output.

```json
		{
			"name": "water_bank_reservoir",
			"type": "virtualstorage",
			"initial_volume": 560000,
			"max_volume": 570000,
			"nodes": [
				"water_bank_input",
				"tid_district",
				"mid_district"
			],
			"factors": [
				-1.0,
				1.0,
				1.0
			]
		},
		{
			"name": "water_bank_input",
			"type": "input",
			"max_flow": "water_bank_inflow",
			"cost":-10
		},
		{
			"name": "dummy_link",
			"type": "link"
		},
		{
			"name": "dummy_output",
			"type": "output"
		},
....
	"edges": [
	        ["water_bank_input", "dummy_link"],
		["dummy_link", "dummy_output"],
...

```

If you have a better way to do it, I'll be happy to try it.
B.

**Comment by jetuk** [comment]
@BaptisteFrancois I see the issue. You would like to use a parameter as input to the virtual storage but it requires that the flow come from a node. This is because it is only the node's constraints that enter the linear programme, not the parameter's directly. 

Your solution is fine and I can not immediately think of a more elegant way to do it. It can be simplified if you remove "dummy_link" and connect the "water_bank_input" directly to the "dummy_output".

**Comment by BaptisteFrancois** [comment]
Many thanks!
