### ISSUE TITLE
Bespoke functions for aggregated recorders

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#70]
Change `_core.Node.recorder` to a `list` of recorders.

**Comment by snorfalorpagus** [comment]
We discussed this a little, and decided that perhaps recorders should be moved outside of the Nodes and onto the Model. This would allow for more complex recorders, that could (for instance) record compound variables, e.g. the total storage for a group of reservoirs.

**Comment by snorfalorpagus** [comment]
I believe that this was achieved in PR #76. However, I'm going to leave this open with a new goal: bespoke functions for aggregate recorders, e.g. the total storage in a group of reservoirs, or something more complicated (the mean?).

**Comment by jetuk** [comment]
I think this is just a matter of writing some more `Recorder` subclasses. For example the aggregated could be achieved using a basic (i.e. no saving/storing of values) subclass of `NodeRecorder` which passes values to a `AggregatedRecorder(Recorder)`.

The other I want is a N-highest values `Recorder` this is a useful way to calculate a percentile on the fly. Keep a list of the top 10% of values and then the 90th %ile is the smallest one of those.

**Comment by jetuk** [comment]
This is complete with #133 merged?
