### ISSUE TITLE
Combining a StorageThresholdParameter with an Interpolatevolume paramter

### ISSUE THREAD

**Issue by BaptisteFrancois** [pywr/pywr#703]
Hi,
I am trying here to create a parameter set that model preventive release when storage at a reservoir becomes higher than a storage target.
The idea is that once the actual storage becomes higher than the target (''preferred_storage', which is defined via a dailyprofile parameter (i.e., 366 values)), the preventive release ('controlled_spill_reservoir_policy') depends on the storage. For this, I tried to combine a "StorageThresholdParameter" to activate an 'interpolated volume' parameter but I cannot get it working. 

I am guessing that I should used a control-curve parameter but I cannot figure out to make it work. Any advice / guidance is very welcome!
Once again - thanks for your hard work.

```json
"controlled_spill_reservoir_policy": {
	"type": "StorageThresholdParameter",
	"values": [0, "safe_ctrl_release"], 
	"storage_node": "reservoir",
	"threshold": "preferred_storage",
	"predicate": "GE"
	},
"safe_ctrl_release": {
	"type": "interpolatedvolume",
	"node": "reservoir",
	"volumes": [0, 2000, 3000, 5000, 5500],
	"values": [0, 150, 240, 400, 560],
	"kind": "cubic"
},```

**Comment by jetuk** [comment]
Something like this should work all in one.

```json
"release" : {
  "type": "controlcurve",
  "control_curves": "my_control_curve_parameter",
  "storage_node": "reservoir",
  "parameters": [
    {"type": "constant", "value": 0.0},
    "safe_ctrl_release"
  ]
}
```

**Comment by BaptisteFrancois** [comment]
aarrrggg still not working ... 
Below is my json script

```json
"preferred_storage": {
	"type": "dailyprofile",
	"url": "../data/reservoir/Preferred_StorageCurveEnfofMonth_daily_percent.csv",
	"index_col": "Reservoir",
	"index": "reservoir_1"
},
"controlled_spill_policy": {
	"type": "controlcurve",
	"control_curves": "preferred_storage",
	"node": "reservoir",
	"parameters": [
		{"type": "constant", "value": 0.0},
		"safe_ctrl_release"
	]
},
"safe_ctrl_release": {
	"type": "interpolatedvolume",
	"node": "reservoir",
	"volumes": [3000, 5000, 5500, 6000, 6500],
	"values": [0, 150, 240, 400, 560],
	"kind": "cubic"
},
```
It looks that Pywr cannot load a parameter. I am not sure to fully understand how works the 'controlcuve'. In the json script below, 'preferred_storage is a dailyprofile (i.e., 366 values that give the relative storage (values ranging from 0 to 1)). 

When I take out the ''controlled_spill_policy'' parameter, the model can be load w/out problem

Below is the Traceback message
```python 
Traceback (most recent call last):
  File "pywr\parameters\_parameters.pyx", line 1399, in pywr.parameters._parameters.load_parameter
KeyError: 'c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "SFPUC_pywr_Sunol.py", line 355, in <module>
    m = Model.load('../model/SFPUC_pywr_Sunol.json')
  File "pywr\_model.pyx", line 257, in pywr._model.Model.load
  File "pywr\_model.pyx", line 191, in pywr._model.Model.loads
  File "pywr\_model.pyx", line 382, in pywr._model.Model.load
  File "pywr\parameters\_parameters.pyx", line 1433, in pywr.parameters._parameters.load_parameter
  File "pywr\parameters\_control_curves.pyx", line 450, in pywr.parameters._control_curves.ControlCurveParameter.load
  File "pywr\parameters\_control_curves.pyx", line 155, in pywr.parameters._control_curves.BaseControlCurveParameter._load_control_curves
  File "pywr\parameters\_parameters.pyx", line 1401, in pywr.parameters._parameters.load_parameter
KeyError: "Unknown parameter: 'c'"

```

**Comment by jetuk** [comment]
With one control curve it is singular. `control_curves` should be a list.

```
"control_curves": ["preferred_storage"],
```
or
```
"control_curve": "preferred_storage",
```

**Comment by jetuk** [comment]
Though I'm not sure, from the example, why it is saying `"Unknown parameter: 'c'"`. I would expect it to load `preferred_storage` as an iterable, and therefore fail with `'p'` first.

**Comment by BaptisteFrancois** [comment]
It works! 
Many thanks!
