### ISSUE TITLE
Is there way to set priority for demands or objects of each demand？

### ISSUE THREAD

**Issue by muguangyuze** [pywr/pywr#709]
Hi:
Can we set priority for demand1 ~demendN nodes from one storage or in other words to set priority for every supply object of one demand, (i.e industry,daily life,agriculture,ecology...)?
Then can we  simulation the condition that sacrifice industry or agriculture or ecology for daily life demand when inflow is dry?

**Comment by jetuk** [comment]
Hi @muguangyuze, if I understand correctly, then yes you can do this.

```
      /----> D_1
S ----|----> D_2
      \----> D_N
```

You would created D1 - DN as seperated `Output` nodes and give each a negative `cost` value equal to their priority.

You might also be interested in the demand restrictions example in the documentation: 
https://pywr.github.io/pywr-docs/cookbook/demand_saving.html

**Comment by muguangyuze** [comment]
@jetuk 
Thanks very much.
Is that mean i can set cost -1 for demand1 and cost -2  for demand2... cost -n for demandn and then the demand1 is highest priority? 
And i want to know whether the "cost" don't just mean supply cost, its unit can be scalar quantity(e.g represents the priority) ？

**Comment by jetuk** [comment]
@muguangyuze pywr uses a cost minimisation. In this case -n would be the "highest priority" because it would give the lowest cost (-n*flow). But yes cost is just a scalar quantity that goes in to a linear programme (to be minimised) as the objective coefficient.

**Comment by muguangyuze** [comment]
@jetuk  Yes, i understand this explanation. I will try my best to read the cookbook. It would be better if you could give a more complex modeling example in this open source project. 
Thank you very much for your contribution.

**Comment by jetuk** [comment]
There are a couple in the `examples/` folder, but none with this particular case.

**Comment by muguangyuze** [comment]
@jetuk  Thanks. Pywr seems can solve most problems. 
Emmm... Now I have a idea that can we write a topology modeling tool to generate the model.json for practical application for network allocation. Of course, it's just a suggestion before Pywr More complete and this need more think.

**Comment by muguangyuze** [comment]
@jetuk Thanks. Pywr seems can solve most problems.
Emmm... Now I have a idea that can we write a topology modeling tool to generate the model.json for practical application of network allocation. Of course, it's just a suggestion before Pywr More complete and this need more think.
