### ISSUE TITLE
Cross-domain conversion factor is not time varying

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#71]
Currently the conversion factor from one domain to another is not time varying. It should be.

https://github.com/snorfalorpagus/pywr/blob/ab78b6ea33293866f36b0a7f5e282bead3100f62/pywr/solvers/cython_glpk.pyx#L76

**Comment by jetuk** [comment]
It's explicitly not allowed to be in `_core.Node`

https://github.com/snorfalorpagus/pywr/blob/master/pywr/_core.pyx#L403

**Comment by snorfalorpagus** [comment]
This relates more generally to the issue of whether the matrix of the LP is allowed to change between timesteps / scenarios.

I have a model with a river flow split, which varies each day, based on the flow the previous day. This is an attempt to represent a nonlinear relationship between the upstream flow and the proportion that goes into each channel downstream. Is there a better way to do this, that doesn't involve changing the matrix?

**Comment by jetuk** [comment]
Can you model it implicitly through the cost weights on either side?

**Comment by snorfalorpagus** [comment]
I don't think so. I'm happy to be corrected thought.

**Comment by snorfalorpagus** [comment]
I suggested (on gitter) that this could be supported by some solvers and not others. The suitability for a solver for a particular model could be checked at runtime with a `Solver.check` similar to `Model.check`. I think it's reasonable that different solvers do different things, and we should be willing to trade off features for speed in some instances.

We need to have a way to check which parameters are time-varying in order to minimise the amount the matrix needs to be updated as this could slow the solver down. If it's only the `Storage` and cross-domain components that do this at least that's a start.

**Comment by jetuk** [comment]
This is being addressed in #919.

**Comment by jetuk** [comment]
Was completed in #919
