### ISSUE TITLE
Debbuging an infeasible LP 

### ISSUE THREAD

**Issue by BaptisteFrancois** [pywr/pywr#712]
Hi - 
I am struggling to find a way to debug an infeasible LP. 

Below is the error I am getting: 

``` python
Simplex solve returned: None (0)
Simplex status: no feasible solution exists (4)
Scenario ID: 0
Timestep index: 0
Writing problem data to 'pywr_glpk_debug.mps'...
1687 records were written
Writing problem data to 'pywr_glpk_debug.lp'...
578 lines were written
GLPK Simplex Optimizer, v4.65
224 rows, 283 columns, 2369 non-zeros
7: obj =   3.497550828e+06 inf =   2.630e+02 (2)

LP HAS NO PRIMAL FEASIBLE SOLUTION
Traceback (most recent call last):
  File "SFPUC_pywr_UpCountry_Sunol_Peninsula.py", line 4028, in <module>
    m.run()
  File "pywr\_model.pyx", line 579, in pywr._model.Model.run
  File "pywr\_model.pyx", line 556, in pywr._model.Model._step
  File "pywr\_model.pyx", line 562, in pywr._model.Model.solve
  File "C:\Users\bfrancois\AppData\Local\Continuum\Anaconda3\envs\wrs\lib\site-packages\pywr\solvers\__init__.py", line 57, in solve
    return self._cy_solver.solve(model)
  File "pywr\solvers\cython_glpk.pyx", line 445, in pywr.solvers.cython_glpk.CythonGLPKSolver.solve
  File "pywr\solvers\cython_glpk.pyx", line 451, in pywr.solvers.cython_glpk.CythonGLPKSolver.solve
  File "pywr\solvers\cython_glpk.pyx", line 618, in pywr.solvers.cython_glpk.CythonGLPKSolver._solve_scenario
RuntimeError: Simplex solver failed with message: "None", status: "no feasible solution exists".
```

I have noticed the issue #88 that mentions an infeasibility API to track nodes that cause the infeasibility of the LP. Is this already implemented? Is there any doc about how to use it?

I have noticed the two debug information files 'pywr_glpk_debug.mps' and 'pywr_glpk_debug.lp'. Maybe all the information I need is already in these files, however, I find them difficult to understand. 

Any help would be really appreciated.

**Comment by jetuk** [comment]
The `.mps` and `.lp` files are dumped by the solver when it has an error. The idea being you can use GLPK (or other LP solver) to debug the actual LP that failed. However, it is quite difficult to understand what is going and debug this.

It looks like #88 was not merged and similar functionality has not been added. There was historic naming of the rows in the LP, but I think we had issues with that - I don't recall the details.

The other option to explore is the `--enable-debug` compile option. This will add some additional checking to the bounds updating of the rows in GLPK. For example, 

https://github.com/pywr/pywr/blob/9c51147757c537a98c0bc485d268d43806a9dbf1/pywr/solvers/cython_glpk.pyx#L663

If one of these assertions fail you can then trace back to which row update and therefore node was causing the problem. 

However, it is perfectly possible to create a model with sensible inputs that is infeasible. I would suggesting relaxing some constraints (particularly any min_flows) on your model to see if you can make it run. 

Does it fail on the first time-step or part way through a run?

**Comment by BaptisteFrancois** [comment]
Ok - I fixed several issues. Model is running now. 
Thanks.
