### ISSUE TITLE
IndexError: Out of bounds on buffer access (axis 0)

### ISSUE THREAD

**Issue by rheinheimer** [pywr/pywr#715]
I'm trying to run a model I've run previously with v1.1.0. Since I've had to re-install Pywr, I was only able to (eventually) re-install v1.0.0 via Conda, or by building from source (the master branch at time of writing - v1.1.1-dev-something). Either way, when I run the model I now get an errror `IndexError: Out of bounds on buffer access (axis 0)`. I've googled this, and know it's within the Cythonized version of Pywr. With my latest attempt (v1.0.0 from Conda), I have a little more info: this error occurs at `File "pywr/parameters/_parameters.pyx", line 675, in pywr.parameters._parameters.MonthlyProfileParameter.value`.

I'm a bit stuck now, as it's unclear how to debug further. Is this error something someone has encountered, and knows how to resolve?

**Comment by jetuk** [comment]
Re conda. You should remove the `pywr` channel, and install pywr from the `conda-forge` channel. This should give you v1.1.0.

Re the `IndexError`, this is quite strange. It'll occur if there are less than 12 values in the monthly profile. I am not sure how that can happen (it checks for length == 12 on init). Could you do something like this where `parameter` is the parameter instance causing the problem.

```
values = parameter.get_double_variables()
print(values)
```

**Comment by jetuk** [comment]
@rheinheimer did you figure this out?

**Comment by rheinheimer** [comment]
@jetuk I was taking a breather, since I previously spent 2 hours trying to install Pywr. I'll try again today with the current master branch (and also conda-forge).
