### ISSUE TITLE
Branch protection

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#718]
GitHub has a branch protection feature to prevent certain potentially destructive actions for some branches:

https://github.com/pywr/pywr/settings/branch_protection_rules/new

I think as a minimum we should enable prevention of force-push and delete to master.

We could also consider requiring review before merge.

@pywr/pushers

**Comment by jetuk** [comment]
> I think as a minimum we should enable prevention of force-push and delete to master.

> We could also consider requiring review before merge.

Done.
