### ISSUE TITLE
Test failures with cython 3.0a

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#730]
I need to a proper report (not time now) but we have some issues with the Cython 3.0a pre-release. I think this might be a regression in Cython, but not to confirm here first.

**Comment by snorfalorpagus** [comment]
I just tried building with Python 3.8 and Cython master (14fd58bbf44be7f9b72bc3b5d77dcbd86b988b03). Seems to work OK - no build failures and the tests all pass.
