### ISSUE TITLE
string / descriptor parameter type

### ISSUE THREAD

**Issue by rheinheimer** [pywr/pywr#732]
I am trying to create a simple parameter that is a string, rather than a number. Is there a way to do this? I have not found a way so far. A use case would be, say, to use the parameter to specify a data folder based on the parameter value. I tried to assign a string to a "constant" parameter, but this caused an error.

**Comment by snorfalorpagus** [comment]
It's not possible to do this with parameters. Can you describe a little more the use case? Where we've done this in the past it's either been by scripting the creation of the JSON models with a template, or using different scenarios within an HDF5 file.

**Comment by rheinheimer** [comment]
Really the main use case is what I mentioned above, which is to specify a data path. For example:
```
scenario_name = self.model.parameter['Scenario Name Parameter'].value(timestep, scenario_index)
path = "{}/data.csv".format(scenario_name)
data = pandas.read_csv(path)
...
```
There's way more to it than this (and no, I'm not reading any csv file more than once), but this is basically it. Another use case could be for water year type (eg., "dry", "wet", etc.) but these can easily be made numeric.

I guess I should assume a path location for the case of one scenario, and for more than one scenario create some kind of scenario_index -> scenario_name lookup if needed. This isn't super optimized yet, and I like the hdf5 approach, but am trying to stick with conventional csv files for now.

**Comment by jetuk** [comment]
Yes, in the past we have made separate columns in our datasets (CSV, XLSX, HDF5) for use in each ensemble of a scenario set. 

However, I think in this case you could just include a list of paths to map to the scenario index? Something like this ...

```python
# This assumes one path for each global scenario. It's a bit more
# complex if you just want to use one set of scenarios. There are 
# examples of this in the existing code base however.
scenario_path = self.scenario_paths[scenario_index.global_id]
path = "{}/data.csv".format(scenario_name)
data = pandas.read_csv(path)
```
```json
{
  "type": "mydataparameter",
  ...
  "scenario_paths": ["/path/one/", "/path/two", "/path/three"]
}
```

However, if this is in the `value()` method then `read_csv` is going to be called every time-step? I think this will be inefficient? You would be better reformatting the data before passing to Pywr IMO, or at the very least loading all the data in `setup()` in one go and storing in memory as a numpy array?

**Comment by rheinheimer** [comment]
Thanks. Just curious: does your `self.scenario_paths` above refer specifically to that defined in the parameter JSON setup? If so, cool! I didn't know you could do that. If not, then I guess the assumption is `self.scenario_paths` would be defined somewhere elsewhere in the class (or even in a base class?).

Re: "if this is in the value() method then read_csv is going to be called every time-step? I think this will be inefficient?" - yes, of course I'm not doing this. Worst case scenario is I use
```
if timestep.index == 0:
    self.mydata = read_csv(...)
return self.mydata[timestep.timestep]
```
Again, not super optimized, but it works. I haven't looked into the `setup` function yet, but that looks like the right route.

I actually have a `self.read_csv` function in my base parameter class that checks a faster store (redis? hdf5?) for the data before resorting to pandas. This way, you can call `self.read_csv` for the same file & args multiple times reasonably efficiently.

**Comment by jetuk** [comment]
> Thanks. Just curious: does your self.scenario_paths above refer specifically to that defined in the parameter JSON setup?

Yes. The idea is that all the keys in the JSON document / section become arguments to the class's `__init__` method. This is how you can define and load specific data with your custom classes. You may need to implement the classmethod `load`.

> I haven't looked into the setup function yet, but that looks like the right route.

Yes this is the preferred approach rather than the pseudo code above. Make sure you call `super().setup()` if you inherit the `setup` method.

**Comment by jetuk** [comment]
@rheinheimer can I close this issue now?

**Comment by rheinheimer** [comment]
Yes - I'll close. Just one additional comment: since I've now finally discovered Pywr tables, I note that tables are another possible way to read in data for any kind of arbitrary lookup table needed (scenario index to path, water year index to name, etc.). And, of course, we can subclass to pass in arbitrary data.
