### ISSUE TITLE
Check use of "position" kwarg in nodes.py

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#733]
The `Drawable` mixin class handles the `"position"` kwarg, but it seems most (all?) node classes also handle the same keyword. This should be tidied up.

**Comment by Batch21** [comment]
Is the preference here to let the `Drawable` mixin handle the position kwarg in all cases and to remove the code that deals with it in the node classes?

**Comment by jetuk** [comment]
Yes, I think so.
