### ISSUE TITLE
Calibrating Model: Memory allocation issue

### ISSUE THREAD

**Issue by GateauXD** [pywr/pywr#743]
I am trying to calibrate my model parameters and am using Spotpy to do so. When iterating to tweak parameters I am creating a new model instance using a modified JSON file with parameters changed. 

The issue I come to happens when I run the calibration for more than 5 iterations. I get an error code shown bellow.

```
glp_free: memory allocation error
Error detected in file ..\src\env\alloc.c at line 72

Process finished with exit code -1073740791 (0xC0000409)
```

I have narrowed the crash to the line when creating the 5th model.
```python
model = Model.load(model_path, path=model_path)
```

**Comment by rheinheimer** [comment]
@GateauXD Did you try totally deleting the model? i.e. `del model`

**Comment by GateauXD** [comment]
Yes I do have a line that releases the model's variable and data after the output of the model is saved in a variable.

```python
results = model.to_dataframe()
results.to_csv('results.csv')
del model
```

**Comment by jetuk** [comment]
Does removing the `del model` help at all?

I don't think we call `glp_free` directly any more. However it is might be called in `glp_delete_prob` which is executed when a solver is deallocated. As for why this is happening I am not sure.

**Comment by GateauXD** [comment]
No ``` del model``` did not make a difference. The issue is odd because the first 4 models run without deallocation issues.

**Comment by jetuk** [comment]
OK. Can you run iteration 5 on its own? Does it fail in isolation? What is different from iteration 5 from 4? Is your computer running out of memory (this seems a long shot for a `glp_free` call).

Reassigning `model` to another model instance will also cause the old model to be deallocated. However, `glp_free` is probably called by various internal GLPK routines, so it is not guaranteed to be the deallocation procedure that causes this.

To debug this we're going to need to use GDB (or other proper debugger). I don't mind looking at that if you can share the model/code, but can also give you instructions on how to do it. 

First you'll need to enable debugging by compiling Pywr your self. This is done by using `--enable-debug` with `setup.py`. Here is the code in `setup.py`: https://github.com/pywr/pywr/blob/21948c60152234b3f98c8036e1d4f2326056b64a/setup.py#L94

Once that is done you would invoke your python script using gdb (or other debugger). Use continue to run the model/script until it crashes and then inspect the traceback. It is this traceback that will help us isolate the cause.

**Comment by GateauXD** [comment]
I found a solution to the error I was having. I separated the initialization and running of the model to another file and used subprocess.run.

```python
proc = subprocess.run(['python', 'simulation_run.py', model_path, root_dir, bucket, network_key, str(vector[0])], stdout=subprocess.PIPE)
```

I have tested calibrating with 20 iterations without a problem.

**Comment by jetuk** [comment]
Great news.

Is there a reason you're running this as a subprocess?

**Comment by GateauXD** [comment]
There isn't a particular reason. I had a chat with a colleague and he suggested the use of running the model via a subprocess. In the future I will look for the root cause of the bug. 

Thank you for the help.
