### ISSUE TITLE
use metaclass kwarg instead of with_metaclass function for node classes

### ISSUE THREAD

**Issue by Batch21** [pywr/pywr#744]
Now pywr is 3.6 only this change would remove an unneeded import

**Comment by jetuk** [comment]
We might not even need metaclasses now that `__init_subclass__` exists as an easier way to register classes. 

We can probably get rid of `six` entirely.

**Comment by Batch21** [comment]
I had a play round with `__init__subclass__` and its definitely a clearer way of doing it. However it looks like the metaclass is still needed so that nodes are are only added to the model graph after their initialisation. I couldn't see a nice way of doing this without metaclasses, other than shifting the functionality to the end of the init function of each node class.

I ended up with this:

```python

class NodeMeta(type):
    """Node metaclass used to keep a registry of Node classes"""
    def __call__(cls, *args, **kwargs):
        # Create new instance of Node (or subclass thereof)
        node = type.__call__(cls, *args, **kwargs)
        # Add node to Model graph. This needs to be done here, so that if the
        # __init__ method of Node raises an exception it is not added.
        node.model.graph.add_node(node)
        node.model.dirty = True
        return node

class NodeRegistry:
    node_registry = {}
    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        cls.node_registry[cls.__name__.lower()] = cls

```

**Comment by jetuk** [comment]
You are right. I forgot about the use of `__call__`.

**Comment by Batch21** [comment]
Do you think this is an update worth making or is it better to leave as is?

**Comment by jetuk** [comment]
If we need a metaclass then probably keep it as is. I wouldn't object to `six` being removed.

A lot of the `super()` calls can be simplified to remove their arguments too, but that's maybe a separate issue.

**Comment by Batch21** [comment]
ok, I've created a PR that removes `six` (#745) and a separate issue for super
