### ISSUE TITLE
Updating PiecewiseLink values every timestep 

### ISSUE THREAD

**Issue by GateauXD** [pywr/pywr#748]
I am trying to utilize the piecewise type for a node. When I try to update the values per timestep 
 the PiecewiseLink does not pass the values from a class. Instead the kwargs hold the names of the class.

```
<= JSON File =>
{
     "name": "Donnells PH [node]",
      "type": "PiecewiseLink",
      "max_flow": [flow_class_val_1, flow_class_val_2, flow_class_val_3, flow_class_val_4],
      "cost": [cost_class_val_1, cost_class_val_2, cost_class_val_3, cost_class_val_4]
},

<= In _init_ piecewise =>
# Would print out "flow_class_val_1" instead of a numerical value
costs = kwargs.pop('cost')
```

**Comment by jetuk** [comment]
I think these should be "max_flows" and "costs" in the JSON.

**Comment by GateauXD** [comment]
Oh, that was a typo on my part. Sorry but the issue still remains. 

For example, when I try to create a piecewiseLink with max_flow and cost values as parameter names. Instead of the parameter's value being sent to peicewiseLink it would be the name of the parameter
```
    {
      "name": "Donnells PH [node]",
      "type": "PiecewiseLink",
      "max_flow": "node/Donnells PH/Water Demand",
      "cost": "node/Donnells PH/Cost"
    },

<= peicewiseLink  =>
# Would print out "node/Donnells PH/Cost" instead of a numerical value
costs = kwargs.pop('cost')
```

**Comment by jetuk** [comment]
Your example still has "cost" and not "costs"?

I see this code is not terrible clear. The JSON wants "costs", but the `load` method converts these to parameters and then passes them as the "cost" keyword argument to `__init__`. Are you sure the you are using plural key names in the JSON?

**Comment by GateauXD** [comment]
Yes that did it for me. 

When running that code I found a error in PYWR PiecewiseLink load method. 

```
# Currently
data["max_flow"] = [load_parameter(p) for p in max_flow]
data["cost"] = [load_parameter(p) for p in cost]

# What worked for me 
data["max_flow"] = [load_parameter(model, p) for p in max_flow]
data["cost"] = [load_parameter(model, p) for p in cost]
```

Thank you

**Comment by jetuk** [comment]
@GateauXD thanks for finding this. I've opened #749 to address this problem. It drops support for the plural versoins of the keys and requires the singular versions to be lists. It will also correctly convert parameter references to objects. 

Is there any chance you can test the branch in #749 and report back whether it works as intended for you? If so I can merge and release this fix. Thanks

**Comment by GateauXD** [comment]
Yes I just tested the changes and everything works. Just needed to change JSON names from plural to singular. Thank you
