### ISSUE TITLE
Question about the use of Blender link

### ISSUE THREAD

**Issue by BaptisteFrancois** [pywr/pywr#754]
Hi, 
I would like to split the outflow of a link to different nodes. I noticed that Blender link class was made for that, although I am having hard time to figure out how to use it within a json file.

My understanding of the issue #234 is the Blender link is likely to be removed at some point. The use of an AggregatedNode is mentioned but as far as I understand the aggreagted node, they cannot be linked to a network.

Do you have any guidance to provide on how to implement the splitting?
The ration between the two nodes would be 75% and 25%.
Thank you.
Baptiste

**Comment by snorfalorpagus** [comment]
For now you should not use the `Blender` node. I don't think it's constraint is respected by the solver at all. Instead you must use the `AggregatedNode`. There isn't any documentation for this yet so the best I can suggest is to read the tests.

https://github.com/pywr/pywr/blob/f8de20b28d59fc5437fa658a0f649018a413c315/tests/test_agg_constraints.py

For example, the test below checks that the aggregated node "agg" is correctly constraining the flow via nodes "A" and "B" to be equal. This has the effect of limiting the flow in "A" to 40, the same as "B", despite "Z" demanding 100.

As you mention, the aggregated node is not "connected" to the network in the conventional sense. The constraint it applies is however respected by the solver. In fact, it would be an error to attempt to connect it.

```python
def test_aggregated_node_two_factors(model):
    """Nodes constrained by a fixed ratio between flows (2 nodes)"""
    A = Input(model, "A")
    B = Input(model, "B", max_flow=40.0)
    Z = Output(model, "Z", max_flow=100, cost=-10)

    agg = AggregatedNode(model, "agg", [A, B])
    agg.factors = [0.5, 0.5]
    assert_allclose(agg.factors, [0.5, 0.5])

    A.connect(Z)
    B.connect(Z)

    model.run()

    assert_allclose(agg.flow, 80.0)
    assert_allclose(A.flow, 40.0)
    assert_allclose(B.flow, 40.0)
```

**Comment by jetuk** [comment]
@BaptisteFrancois are you happy with this response? `Blender` has now been removed from the code based entirely.

**Comment by BaptisteFrancois** [comment]
@jetuk @snorfalorpagus thank you both for your answer. 
I have found a work around that works well (that I can describe if you want) but your solution is definitely more elegant and certainly more efficient as well. 
I am gonna give a try and let you node. This only thing is that I am mainly coding this model using the json format. I know how to make the aggregated node with a ratio in json, but is this enough to impose the constraint to the LP solver?

Another way to ask my question is;: how would you code in json format the lines:
A.connect(Z)
B.connect(Z)
 ?
Thanks again for your help.

**Comment by snorfalorpagus** [comment]
> Another way to ask my question is;: how would you code in json format the lines:
> A.connect(Z)
> B.connect(Z)

These are the edges in the network, i.e.

```
"edges": [
    ["A", "Z"],
    ["B", "Z"]
]
```

So that the simple model looks like:

```
A ---> Z <--- B
```
