### ISSUE TITLE
Use glp_error_hook to catch unhandled errors

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#759]
Following #758, we could use `glp_error_hook` to catch unhandled errors in GLPK which would prevent the program exiting and instead raise an exception in Python.

> 6.1.13    glp_error_hook—install  hook  to  intercept  abnormaltermination
>Synopsis
>`void glp_error_hook(void (*func)(void *info), void *info);`
>Description
>The routine `glp_error_hook` installs a user-defined hook routine to inter-cept abnormal termination.The parameterfuncspecifies the user-defined hook routine.  It is calledfrom  the  routineglp_errorbefore  the  latter  calls  the  abort  function  toabnormally terminate the application program because of fatal error.  
>The parameter info is a transit pointer,  specified in the corresponding call tothe routine `glp_error_hook`;  it may be used to pass some information tothe hook routine.
>To uninstall the hook routine the parametersfuncandinfoshould bespecified as `NULL`.
> Usage note
> If the hook routine returns,  the application program is abnormally terminated.  To prevent abnormal termnation the hook routine may perform aglobal jump using the standard function `longjmp`, in which case the application program must call the routine `glp_free_env`.

Example usage below. We could put the setjmp in `solve()` before the call to GLPK.

https://www.tutorialspoint.com/c_standard_library/c_function_longjmp.htm

```c
#include <stdio.h>
#include <stdlib.h>
#include <setjmp.h>

int main () {
   int val;
   jmp_buf env_buffer;

   /* save calling environment for longjmp */
   val = setjmp( env_buffer );
   
   if( val != 0 ) {
      printf("Returned from a longjmp() with value = %s\n", val);
      exit(0);
   }
   printf("Jump function call\n");
   jmpfunction( env_buffer );
   
   return(0);
}

void jmpfunction(jmp_buf env_buf) {
   longjmp(env_buf, "tutorialspoint.com");
}
```

It's probably worth doing some reading to see if there are any issues with this in Cython.

**Comment by snorfalorpagus** [comment]
There is a small complication with this.

> To prevent abnormal termnation the hook routine may perform aglobal jump using the standard function longjmp, in which case the application program **must** call the routine glp_free_env

> The routine glp_free_env frees all resources used by GLPK routines (memory blocks, etc.) which are currently still in use.

The `glp_free_env` function frees memory for all resources, not a specific `glp_prob`. This means that for a program with more than one `Model` (unusual, but supported), if a crash occurs in one model it will invalidate any GLPK resources in the other(s). We'll need some sort of global flag to track this. This could be done with a counter that tracks how many times `glp_free_env` has been called. If the number is greater than the reference the model has then it needs to call `setup` again, even if it would normally only need to call `reset`.

**Comment by jetuk** [comment]
And an added complication is that we have two GLPK based solvers as independent modules. This global counter will need to be in a shared module. That starts us along the road of solving #760 .

**Comment by jetuk** [comment]
This was done in #1021.
