### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by rubenmu** [pywr/pywr#761]
Hi,
fist, thank you for the nice package.
I would like to know how the best cite pywr, is there a paper available?

Regards,
Ruben

**Comment by jetuk** [comment]
Hi Ruben,

We have a paper in submission at the moment if you can wait for that. Until that is published could you please cite this repository. 

Thanks.

**Comment by snorfalorpagus** [comment]
The paper is in pre-proof now and can be cited as:

> Tomlinson, J.E., Arnott, J.H. and Harou, J.J., 2020. A water resource simulator in Python. Environmental Modelling & Software. https://doi.org/10.1016/j.envsoft.2020.104635

The full citation wont be available until the journal is published. We should add this into the documentation when it is.
