### ISSUE TITLE
setup.py doesn't report any information about build failures.

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#77]
Following implementation of #58 setup.py does not give you any useful information to debug the failing extensions - unless I am missing something?

**Comment by snorfalorpagus** [comment]
PR #80 attempts to address this.

I'm not happy with setup.py at all, but I think it's going to be difficult to get right. Python packaging is a mess. By the time we hit 1.0 I think we at least need a binary/wheel distribution for Windows users, and a smooth process for *nix.

**Comment by jetuk** [comment]
Do we distribute GLPK and/or lpsolve with the binary distribution?

**Comment by snorfalorpagus** [comment]
Yes. I think it's too hard for Windows users otherwise.

In terms of the GPL (v3) we're just required to provide instruction on how to access the source for those projects (i.e. a link to their download pages).

> One of the fundamental requirements of the GPL is that when you distribute object code to users, you must also provide them with a way to get the source. GPLv2 gave you a few ways to do this, and GPLv3 keeps those intact with some clarification. It also offers you new ways to provide source when you convey object code over a network. For instance, when you host object code on a web or FTP server, you can simply provide instructions that tell visitors how to get the source from a third-party server. Thanks to this new option, fulfilling this requirement should be easier for many small distributors who only make a few changes to large bodies of source.

**Comment by snorfalorpagus** [comment]
Closing this because the original issue is resolved. We can create a new issue for the Windows build.
