### ISSUE TITLE
perfect foresight mode

### ISSUE THREAD

**Issue by rheinheimer** [pywr/pywr#773]
For some problems, a perfect foresight optimization model is needed, whereby the LP problem is run as one temporally connected problem, rather than as sequential yet independent steps. Has anyone considered implementing this for Pywr?

**Comment by jetuk** [comment]
Not as far as I know. I think it could be feasible with a custom solver, and perhaps reuse the existing LP stuff if it were refactored (as suggested in #760 ). However, the biggest problem I see is that you would not be allowed to use any parameters that depended on model state. All the data would have to be computed for all time-steps before LP solve. 

That might mean the existing LP formulation is too simple and needs some more sophisticated constraints. In that case you would be moving logic that is currently in the parameters space to the LP space (and possibly linearising it).

Alternatively, use a standard simulation with global optimisation configured to allow it to find a perfect foresight style solution.

**Comment by rheinheimer** [comment]
> Alternatively, use a standard simulation with global optimisation configured to allow it to find a perfect foresight style solution.

Personally, I'm partial to this solution. Am exploring various options though.

**Comment by jetuk** [comment]
It's be quite interesting to try. I recently advised someone against setting up a model like this because I didn't see the value in the solution! However, the approach we discussed was to have a decision variable each time-step or year that was globally optimised. 

The former could be done by implementing the variable API on `ArrayIndexedParameter`. This would then give a variable for every time-step.

**Comment by rheinheimer** [comment]
Thanks! I'm trying the single-LP problem approach first. I'll look into ArrayIndexedParameter. In the meantime I'm trying a hacky approach using time steps encoded into parameter names (e.g., "myparameter/1" for January). The name can be parsed to get the month. Not pretty, but it works.

**Comment by jetuk** [comment]
Does this mean you have multiple copies of the network in your model to represent each timestep?

**Comment by rheinheimer** [comment]
Yes, that's right. But it's all one big network in the end. The "multiple copies" are represented in a single big network in the JSON file. This means that I've also replicated all parameters as well (i.e. also with the month), so I think the problem will be quite large (though in my case I'm only doing a monthly planning model of one year, so x12).

I've added a custom `setup` function for my base parameter class that parses the calling parameter name to get the associated month. Actually, it's not really a month, but a month offset. So if we move our timestepper forward, we can get the actual month with, say, `timestepper.month + month_offset`.

**Comment by rheinheimer** [comment]
So I've made some progress with this, though am struggling with the time step scheme:

I don't think I can set the time step frequency to 'M', since Pywr will convert all input data to monthly according to the nominal month, which isn't appropriate, since most data (11 of 12 values for each parameter in my 12-month model) do not correspond to the current first month of the planning period.

So... given I need to use daily time steps (and trick Pywr by pre-aggregating data to monthly), and my planning model is run only once per month (i.e., the 1st of each month), how do I set up the timestepper? I don't think I can provide custom dates. However, nor can I seem to update the timestepper current date. Here's my code (which doesn't work):
```
        dates = pd.date_range(
            start=monthly_model.timestepper.start,
            end=monthly_model.timestepper.end,
            freq='M'
        )
        for date in dates:
            monthly_model.timestepper.start = date
            monthly_model.timestepper.end = date
            monthly_model.step()
```
Should it be possible to do this? I think not, as is (since the model needs to know, say, the previous day's storage...). Are there some steps I could take to make this work, such as manually updating initial condition (which I was planning to do anyway)?

My Plan B will be to go with same-length periods (e.g., 30 days instead of months). For planning purposes, the actual step length is somewhat arbitrary.

**Comment by rheinheimer** [comment]
More update: After struggling with the above issues, the following seems to do the trick:
```python
for date in mydates:
    monthly_model.reset(start=date)
    monthly_model.step()
```
where `monthly_model` is a daily timestep model and dates are arbitrarily spaced (monthly in my case). The key here is `model.reset(start=date)`: as far as I can tell, this advances the date, but does not result in resampling that comes with a new `.setup()` which kicks off if you change `model.start` in the middle of a run and significantly slows things down.

The result of this is the ability to 1) use my own custom dates and 2) use my own custom units (not per day units).

Now, the general algorithm for the integrated daily scheduling and monthly planning models will be:
```python
for date in daily_dates:
    if date.day == 1: # first of month, or some other condition
        if i != 0: # or some other conditional statement
            update_monthly_model_from_daily_model()
        monthly_model.reset(start=date)
        monthly_model.step()
        # update daily model as needed here (constraints, etc.)
    daily_model.step()
```

**Comment by jetuk** [comment]
Could you subclass the `Timestepper` class and overload either `setup` or `datetime_index` to create your own periods? I think making `setup` create the `self._periods` to your custom dates might work? You could have to swap the default timestepper on the model with your custom one:

```
model.timestepper = MyCustomTimestepper()
model.setup()
model.run()
```

One thing to bear in mind is that the duration of the periods are used for various things in the model. E.g. multiplying by number of days to update storage volumes. If you are using a pseudo timestep then you'll have to make sure this is done correctly yourself.

**Comment by rheinheimer** [comment]
@jetuk Thanks, I'll try that. Going to close this since I don't think it's an issue that requires any specific change to Pywr (yet). Nonetheless I'll update this thread as warranted for future reference. It would be worth noting some of these tricks in the documentation at some point. I should be able to help with that eventually.

**Comment by rheinheimer** [comment]
Unfortunately my plan of using a daily model but running it only on the first of every month (i.e., w/ `model.reset(start=new_date)` followed by `model.step()` where new_date skips a few dates) doesn't work. @jetuk is there some way to either 1) skip dates, and only run the model intermittently? Or 2) provide my own monthly data, instead of volume/day data?
