### ISSUE TITLE
TypeError: Invalid comparison between Day and MonthBegin

### ISSUE THREAD

**Issue by rheinheimer** [pywr/pywr#781]
I'm trying to load a json model and get the error in the title--`TypeError: Invalid comparison between Day and MonthBegin`--when running `model.setup()`. It's a bit hard to know exactly where to begin to troubleshoot this, but here's the traceback (I guess a lot of this is irrelevant, but I paste the whole error anyway):
```
Traceback (most recent call last):
  File "C:\Users\david\Anaconda3\envs\waterlp-pywr2\lib\site-packages\pandas\tseries\offsets.py", line 2506, in f
    return op(self.delta, other.delta)
AttributeError: 'MonthBegin' object has no attribute 'delta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/david/Documents/PROJECTS/SIERRA2/Pywr models/run_basin_model.py", line 334, in <module>
    run_model(basin, network_key)
  File "C:/Users/david/Documents/PROJECTS/SIERRA2/Pywr models/run_basin_model.py", line 252, in run_model
    monthly_model = create_planning_model(model_path)
  File "C:/Users/david/Documents/PROJECTS/SIERRA2/Pywr models/run_basin_model.py", line 192, in create_planning_model
    monthly_model.setup()
  File "pywr\_model.pyx", line 611, in pywr._model.Model.setup
  File "pywr\parameters\_parameters.pyx", line 213, in pywr.parameters._parameters.DataFrameParameter.setup
  File "pywr\parameters\_parameters.pyx", line 216, in pywr.parameters._parameters.DataFrameParameter.setup
  File "pywr\parameters\_parameters.pyx", line 185, in pywr.parameters._parameters.align_and_resample_dataframe
  File "C:\Users\david\Anaconda3\envs\waterlp-pywr2\lib\site-packages\pandas\tseries\offsets.py", line 2511, in f
    cls=type(self).__name__, typ=type(other).__name__
TypeError: Invalid comparison between Day and MonthBegin
```

Since this is related to Pandas, it is of course related to reading in csv files. I assume this is for reading in csv files via the json file (if related to my own code, I pre-apologize!). However, still wondering if anyone has seen this before. I'll post something if I figure this out, though in the meantime am stuck.

Node/parameter-specific info in the exception would definitely come in handy here.

**Comment by rheinheimer** [comment]
It turns out the issue was I'm reading in monthly time step data. In other words, my csv file has data for the first day of each month, rather than for each day. While this will probably force me to re-think my approach in a good way, though at a cost of performance (for creating a "fake" monthly planning model as in #773), I still think this is an issue. How do we read in monthly--or non-daily--time series? 

In the case of #773, my plan was/is to run the model for one "day", run on the first of each month, where all data for that day is actually monthly data. Hence, reading in monthly data rather than daily. (Each future month corresponding to each start month was to be represented in columns in the csv file, representing imperfectly forecasted inflows)

**Comment by jetuk** [comment]
>  In other words, my csv file has data for the first day of each month, rather than for each day

This should work. Are you using the latest master? We made some changes to allow running pandas offset based time-steps. These changes should allow you to input, for example, a monthly timeseries and run it with a daily model. 

>In the case of #773, my plan was/is to run the model for one "day", run on the first of each month, where all data for that day is actually monthly data

With #675 merged you should be able to run with a timestep of "M". To do a whole month. Inputs are still per day though.

**Comment by rheinheimer** [comment]
Fantastic! Will try with updates

**Comment by rheinheimer** [comment]
Fyi, the updates did solve the problem of missing time steps. HOWEVER, a new error arose (new issue?), resulting from missing values in time series. I'll open a new issue with more detail once I replicate that. In the meantime, closing this since, well, the issue is resolved.

**Comment by jetuk** [comment]
Thanks for confirming. We'll get 1.4.0 released soon so you don't have to use master to have these changes.
