### ISSUE TITLE
Cannot open include file: 'glpk.h': No such file or directory

### ISSUE THREAD

**Issue by rheinheimer** [pywr/pywr#782]
I'm trying to install Pywr from source on Windows 10 using GLPK. Things mostly go okay, with MS Visual Studio 2019, but I get `Cannot open include file: 'glpk.h': No such file or directory`. I've followed #751 (this issue is the followup to that), including using conda to install GLPK. However, this error still arises.

Any ideas? @jetuk in #751 you wrote
> You will need to extract those and put the relevant files (glpk.h and .lib I think) in the correct paths such that the compiler can find them.

Usually I test the path setup by typing `glpsol`, which works fine for me. Do the glpk.h and .lib need to be explicitly in the path as well?

Fyi, this is to include the latest updates. Otherwise, conda (or pip) is definitely way better.

**Comment by rheinheimer** [comment]
Update 1: for glpk.h, you need to copy this file from your glpk src folder (e.g., C:\glpk-4.65\src\glpk.h) to  the pywr\solvers folder.  The same thing doesn't work with the .lib file (there is no glpk.lib, only, e.g., glpk-4.65\w64\glpk_4_65.lib.

So the question now is where to put the lib file? And is any renaming necessary?

**Comment by rheinheimer** [comment]
**Update 2**: RTFM? [Installing from source with Anaconda](https://pywr.github.io/pywr-docs/install.html#installing-from-source-with-anaconda) worked like a charm!

**Comment by jetuk** [comment]
Doing this manually on Windows is possible as you found out, but does require putting some files in the correct places with the correct names. Therefore we usually recommend Anaconda as you found out.

Can I close this?

**Comment by rheinheimer** [comment]
Though closed, if someone is able to do this, having this documented here would be helpful.

**Comment by jetuk** [comment]
Yeah OK. I'll leave #751 open. We can something to the documentation about doing this manually on Windows. I think you do need to rename that `.lib` to `glpk.lib` despite it having the version in the name, but it is a long since I did this.
