### ISSUE TITLE
support 'mynode' in self.model.nodes

### ISSUE THREAD

**Issue by rheinheimer** [pywr/pywr#786]
At some point I need to conditionally check if a node is actually in my model, using:
```python
if 'mynode' in self.model.nodes:
    n = self.model.nodes['mynode']
    # do something
else:
    # do something else
```
This doesn't seem to work - even if `mynode` is known to be a node, `'mynode' in self.model.nodes` returns false. I recommend supporting this, as a low priority nice-to-have feature request to file away. In the meantime, `try-except` works fine.

**Comment by jetuk** [comment]
This sounds like a good addition. It should be easy enough to implement the `__contains__` method in `NamedIterator`.
