### ISSUE TITLE
scenario parameters for daily and weekly profiles

### ISSUE THREAD

**Issue by Batch21** [pywr/pywr#794]
Pywr has a `ScenarioMonthlyProfileParameter` but not corresponding parameters for daily and weekly profiles.

I've just created a daily version. Is it worth adding this and a weekly version to pywr?

**Comment by jetuk** [comment]
Hmm I thought we got rid of this! I don't see why these wouldn't be useful additions.

You might be interested in the `ScenarioWrapperParameter`, but that is unlikely to be very efficient.

**Comment by Batch21** [comment]
got rid of the `ScenarioMonthlyProfileParameter` ?

I had a look at the `ScenarioWrapperParameter` but, like you say, it didn't seem efficient for 50+ profiles

**Comment by jetuk** [comment]
Yeah, I was mistaken. Must have been something else we removed!

**Comment by jetuk** [comment]
These have been merged.
