### ISSUE TITLE
Recorder to perform a temporal aggregation of the flows in a node

### ISSUE THREAD

**Issue by Jmiguel17** [pywr/pywr#800]
Hi @jetuk, 

I want to aggregate the flows in a node in order to the recorder output be an aggregated series of the timesteps.  E.g. timestep of my model is weekly but I want that the recorder's output a monthly value of the flows of a given node. This aggregation could be the sum or mean of the weeks in a given month.

Is there any recorder that could be done something similar to follow it and try to modify it to get what I want?

Thanks

**Comment by jetuk** [comment]
If you are using the numpy array recorders then you can just use the `.to_dataframe()` method, and then using resampling on the dataframe. For example, 

```python
df = my_recorder.to_dataframe()
df = df.resample('M').mean()
```

**Comment by Jmiguel17** [comment]
Thanks

**Comment by jetuk** [comment]
Happy for me to close this one?
