### ISSUE TITLE
update the dayofyear attribute of Timestep and add weekofyear attribute

### ISSUE THREAD

**Issue by Batch21** [pywr/pywr#804]
As noted in #802, all current uses of the dayofyear attribute of `Timestep` involve the calculation: Timestep.dayofyear - 1 

This calculation could be done by the `Timestep` object itself. 

`Timestep` could also calculate a weekofyear value that is currently calculated separately in a couple of  the weekly profile parameters.

**Comment by jetuk** [comment]
This is partially done in #903. 

The `weekofyear` part is not currently done.
