### ISSUE TITLE
setup.py argument logic is un-intuitive

### ISSUE THREAD

**Issue by knoxsp** [pywr/pywr#808]
In setup.py, the logic for turning on and off glpk and lpsolve is not intuitive:
In order to turn off building with lpsolve, you must use the argument `--with-glpk`

A preferrable solution would be to explicitly turn off solvers instead of turning on the other ones, for example using `--no-lpsolve`

**Comment by jetuk** [comment]
Yeah, I agree with this.

You can use the `PYWR_BUILD_GLPK` environment variable also, but I think that suffers from the same logic where specifying GLPK means lpsolve is not built.

**Comment by jetuk** [comment]
Closed in #811
