### ISSUE TITLE
coverage>=5 is broken

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#810]
Coverage 5.0 seems to have a bug when using `--cov-append`. Some info in here:

https://github.com/nedbat/coveragepy/issues/880

This commit pins the CI to use <5.0 and should be reverted once the upstream bug is fixed:

https://github.com/pywr/pywr/commit/65f46faae3055f44a5307dee6fbdde745209d630

**Comment by snorfalorpagus** [comment]
This is fixed in `coverage==5.0.1` (apparently).
