### ISSUE TITLE
glp memory allocation error

### ISSUE THREAD

**Issue by Batch21** [pywr/pywr#819]
After installing the latest changes on master I got the following error when trying to run a  model:

```
glp_free: memory allocation error
Error detected in file ..\src\env\alloc.c at line 72
```

This was originally with python 3.7 and glpk 4.65.  Also tried with a new Python 3.8 env and got the same error.

not sure if I'm missing something with the updates to the solvers and setup.py

**Comment by jetuk** [comment]
I think this is caused by #760, but I am not sure why. 

@Batch21 could you check whether using the GLPK binaries from the winglpk project works for you? I think I had this issue and it is resolved if I don't use GLPK provided by conda. That's not a long term solution, however. I am not sure what might cause there to be different between the two binaries, or why the specific changses in #760 are causing a problem.

**Comment by jetuk** [comment]
Possible process for debugging extensions on Windows: https://stackoverflow.com/a/15266003

**Comment by jetuk** [comment]
@Batch21 can you run your model with the following arguments and paste the traceback here?

`python -q -X faulthandler my_script.py`

**Comment by Batch21** [comment]
```
(py37) C:\Data\tmp\testing>python -q -X faulthandler simple_model.py
glp_free: memory allocation error
Error detected in file ..\src\env\alloc.c at line 72
Fatal Python error: Aborted

Current thread 0x000017ac (most recent call first):
  File "c:\data\dev\pywr\pywr\solvers\__init__.py", line 54 in setup
  File "simple_model.py", line 29 in <module>
```

line 29 in simple_model.py is just `model.run()`

**Comment by jetuk** [comment]
This is during setup of the solver. I really have no idea how to debug this with using a proper debugger as above. Did you confirm it works with the winglpk binaries?

**Comment by jetuk** [comment]
@Batch21 can you confirm which glpk build you are using from conda or conda-forge? And whether updating it or using it from the other channel (probably needs a clean recompile against the new .lib) makes any difference?

**Comment by jetuk** [comment]
OK... so the difference between these two setups is that the .lib from winglpk is just the exports for the DLL and therefore forces our extension modules to be linked dynamically. Whereas the conda-forge .lib file is the full static library which is statically linked to the extensions. I guess this means that each module has its own version of the library with nothing shared. Therefore we are seeing this error when trying to use GLPK functions across multiple modules.

Currently the conda-forge feedstock distributes glpk.dll, glpk_4_65.dll and glpk.lib (static library), but not glpk_4_65.lib (the dll exports). Therefore it seems impossible to actually link dynamically against the conda-forge provided dynamic library.

Without an upstream fix I would guess the only solution is to put all the GLPK solvers in one module.

PS I've probably got some of this terminology wrong.

**Comment by Batch21** [comment]
ok, I think that makes sense. Using winglpk worked for me when running a model. However when running the tests I got this error:

```
INTERNALERROR>   File "C:\Program Files\Anaconda3\envs\py37\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Data\dev\pywr\tests\conftest.py", line 7, in pytest_report_header
INTERNALERROR>     solver_name = Model().solver.name
INTERNALERROR>   File "pywr\_model.pyx", line 99, in pywr._model.Model.__init__
INTERNALERROR>     raise KeyError('Unrecognised solver: {}'.format(solver_name))
INTERNALERROR> KeyError: 'Unrecognised solver: glpk'
```

Not sure if this is due to something I've done wrong somewhere or if its related to this problem

**Comment by jetuk** [comment]
This is likely because it can't find the DLL (or there is some other problem loading the library). Our current code masks the import error by making the solver unavailable.

**Comment by jetuk** [comment]
Issue in the conda-forge feedstock: https://github.com/conda-forge/glpk-feedstock/issues/37

**Comment by jetuk** [comment]
In the interests of moving things forward, and also not breaking people's existing installs (i.e. not requiring a new glpk package from conda should one be made) I vote that we merge the 3 GLPK related modules into one. @Batch21 @snorfalorpagus any objections to this?

**Comment by Batch21** [comment]
@jetuk None from me

**Comment by jetuk** [comment]
I've made the changes. I'll open a PR when I get somewhere I can push them.
