### ISSUE TITLE
Error in Recorders

### ISSUE THREAD

**Issue by shahryaramd** [pywr/pywr#841]
I am running the minimal example given here: https://pywr.github.io/pywr-docs/master/tutorial.html
I am using Ubuntu 16.04 and python 3.8.
The error I am receiving is: 
  **File "pywr/recorders/_recorders.pyx", line 500, in pywr.recorders._recorders.NumpyArrayNodeRecorder.data.__get__
AttributeError: Memoryview is not initialized**

Is there something I'm doing wrong?
The code is attached here. 
[tutorial_pywr.pdf](https://github.com/pywr/pywr/files/4207921/tutorial_pywr.pdf)

**Comment by jetuk** [comment]
You need to do a `model.run()` before accessing the data. The memoryview is initialised in `Model.setup()`, which is called for you in `.run()`.

**Comment by shahryaramd** [comment]
Thanks that worked!
Are there any full examples on how to extract the optimal reservoir state (storage), optimal release etc. after model.run()? I am beginning to use pywr for my research but finding it hard to find working examples for that.

**Comment by jetuk** [comment]
What do you mean by "optimal reservoir state"? Do you mean the simulated volumes? The easiest approach is to use either the CSV or Tables recorder. These will output data to files which you can then open other scripts.

**Comment by jetuk** [comment]
https://github.com/pywr/pywr/blob/master/tests/models/csv_recorder.json 

Here's a test model of the CSV recorder.
