### ISSUE TITLE
Corrupt example file

### ISSUE THREAD

**Issue by shahryaramd** [pywr/pywr#842]
The example data file thames_stochastic_flow.gz is corrupt and can't be opened/read

**Comment by jetuk** [comment]
What are you trying to read it with? Can you try with the same data from the tests folder?

**Comment by snorfalorpagus** [comment]
It looks OK to me.
```
$ zcat examples/data/thames_stochastic_flow.gz | head -3
Date,MeanTemp,rainfall,pet,percolation,flow
2100-01-01,18.6848440352,4.31525891749,0.647017924628,31546.8725386,27.0585016084
2100-01-02,16.4489688317,0.511540014087,0.590400011652,400.53583103,62.56255944
```
The file is a compressed CSV so you need to use software that can decompress (in the example above, `zcat`).
