### ISSUE TITLE
AssertionError: Radial basis function implementation 

### ISSUE THREAD

**Issue by Jmiguel17** [pywr/pywr#844]
Hi @jetuk, I was testing your implementation of the rbf (https://github.com/pywr/pywr/pull/725) but I got the next error when I tried to run an optimisation using Platypus 

``` 
File "pywr\solvers\cython_glpk.pyx", line 439, in pywr.solvers.cython_glpk.CythonGLPKSolver.solve
File "pywr\solvers\cython_glpk.pyx", line 445, in pywr.solvers.cython_glpk.CythonGLPKSolver.solve
File "pywr\solvers\cython_glpk.pyx", line 520, in pywr.solvers.cython_glpk.CythonGLPKSolver._solve_scenario
File "pywr\solvers\cython_glpk.pyx", line 677, in pywr.solvers.cython_glpk.set_row_bnds
AssertionError
```

I was using the attached model, that is basically the test that you implemented with some minor modifications. 

FYI: The implementation works well with a simulation, this only fails in the optimisation.

[model.txt](https://github.com/pywr/pywr/files/4231211/model.txt)
[run_moea.txt](https://github.com/pywr/pywr/files/4231218/run_moea.txt)

How can I solve this? 

Thanks

**Comment by jetuk** [comment]
I guess the RBF is outputting invalid values (e.g. a -ve number) that is used by the constraint bounds? You could try putting a `MaxParameter` around the RBF output to make sure it stays > 0? Or building this clipping to >= 0 in to the RBF parameter itself?

**Comment by Jmiguel17** [comment]
@jetuk, Thanks for your reply. 

This clipping must be added into `def set_double_variables` or `def get_double_variables`. Where do you recommend? 

Thanks

**Comment by jetuk** [comment]
See this comment. https://github.com/pywr/pywr/pull/725#discussion_r382194735

I suggest we close this issue and discuss in this in PR.
