### ISSUE TITLE
Are parameters scenario-safe?

### ISSUE THREAD

**Issue by rheinheimer** [pywr/pywr#849]
Sometimes we track state by storing a variable as a custom parameter method. e.g., within `def value(...):`:
```python
if some_condition:
    self.custom_variable = True
...
if self.custom_variable:
   do_something()
```
Could this cause problems when running multiple scenarios? I.e., are parameters scenario-safe, such that a change in `self.custom_variable` by one scenario won't change it for another scenario? Should any kind of custom variable declared within a parameter like this really be an object/array and referenced by scenario?

**Comment by jetuk** [comment]
No, they are not scenario-safe. You must return a value for the given time-step and scenario (hence the two variables). if you need to track state then you must do so in a scenario specific manner. In this example you would create an array of custom variables, one for each scenario. Several of the existing parameters do this. You could use them as an example.

**Comment by jetuk** [comment]
[Relevant section of documentation.](https://pywr.github.io/pywr-docs/master/extending_pywr/extending_pywr_parameters.html)
