### ISSUE TITLE
annualvirtualstorage resets to initial_volume

### ISSUE THREAD

**Issue by Ryan-Davies** [pywr/pywr#859]
I'd suggest making it reset to the maximum by default and having an optional manual reset volume.
I was using pywr version 1.5.1.dev9+g33d5c0b

**Comment by jetuk** [comment]
Good spot. I think this should be fixed as you suggest.

**Comment by jetuk** [comment]
@Ryan-Davies can you test the `fix859` branch in PR #860 to see if it fixes your issue. Thanks.
