### ISSUE TITLE
ArrayIndexedScenarioParameter is not registered 

### ISSUE THREAD

**Issue by Jmiguel17** [pywr/pywr#862]
Hi @jetuk, I think it is necessary to register the `ArrayIndexedScenarioParameter` parameter, I created a new branch and I did the registration but when I tried to `push` the changes to create an MR I got this:
```
remote: Permission to pywr/pywr.git denied to Jmiguel17.
fatal: unable to access 'https://github.com/pywr/pywr.git/': The requested URL returned error: 403
```

Additionally, could you please suggest me what parameter to use to model the following:

I am coupling an external model to a `pywr` model. This external model will provide the `pywr` model in every timestep a `1D` array of `n` values (where `n>1`) that represent some scenarios to the `max_flow` property in a `node`. I have tried to use `ArrayIndexedScenarioParameter`, `ConstantScenarioIndexParameter` and `ConstantScenarioParameter` directly. However, when I run the models, the `pywr` model does not update the `values` in the model. One example of the `json` formulation using `ConstantScenarioParameter` is:

```
"scenarios":[{
            "name": "water_scenarios",
            "size": 3,
            "ensemble_names": [
                "1st",
                "2nd",
                "3rd"]}],
"nodes":[{
            "name": "G1 Akosombo",
            "type": "generator", #this is node type in pywr-dcopf
            "max_flow": "G1 Akosombo:max_flow scenarios",
            "comment": "Hydro-generator"},],
"parameters":[
        "G1 Akosombo:Hydro generation scenarios": {
            "type": "ConstantScenarioParameter",
            "scenario": "water_scenarios",
            "values": [2, 3, 5]},]
```

To set the new values in the pywr `model` I am using the `set_double_variables()` method. I tested the `set_double_variables()` method using a `ConstanParameter` and the `value` was updated in the `pywr` model in each time step. However, I don't know why this does not work when I try to give an array `n>1`. When I passed the array `n>1` the `pywr` model ran but only used the `values` initialized in the `json` file, ignoring the passed array. 

Beforehand thank you for your help.

**Comment by jetuk** [comment]
I think the issue here is `set_double_variables()` is not implemented for those parameters. It should raise a `NotImplementedError`. This is not implemented because these parameter classes do not support the variable API at the moment. See #632 for one issue around this. I am surprised you are not getting an error though.

> ... when I tried to push the changes to create an MR I got this

You don't have permission to push to this repo. You should push to your fork (make one if you don't have one already) and then open a MR from there. See: https://guides.github.com/activities/forking/

**Comment by Jmiguel17** [comment]
I just added this code to this parameter `ConstantScenarioParameter` and I solved my problem (update each timestep the `values` taken from an external model). 
```
    cpdef set_double_variables(self, double[:] values):
        n = len(self._values)
        self._values[...] = values[0:n]
        print(self._values)
```
However, I would like to ask you if you think this could have a collateral impact (not desired) in the simulation of my `pywr` model? 
Additionally, Do you think is good to have these lines of code in pywr? Could this have other useful applications?

**Comment by jetuk** [comment]
> However, I would like to ask you if you think this could have a collateral impact (not desired) in the simulation of my pywr model?

This function is only used by the optimisation wrappers. It's good to use before you do `setup` or `reset`.

> Additionally, Do you think is good to have these lines of code in pywr? Could this have other useful applications?

Yes, but we should implement the whole variable API so, `get_double_variables`, `set_double_variables`, `double_size`, etc.

**Comment by jetuk** [comment]
> ... register the ArrayIndexedScenarioParameter parameter

This was done in #863

**Comment by jetuk** [comment]
I'm going to close this. We have #864 open for the `ConstantScenarioParameter` API stuff.
