### ISSUE TITLE
Scenario-indexed node "max_flow"

### ISSUE THREAD

**Issue by MohammedBasheer** [pywr/pywr#865]
@jetuk 
Hi there,

I am implementing a parameter intending to assign different "max _flow" values to a node for different inflow scenarios. Can the "max_flow" property of a node be set based on the scenario index?
For example:
self._outflow_control_node.max_flow[scenario_index.global_id]
Where self._outflow_control_node is a node

Thanks

**Comment by jetuk** [comment]
If the numbers are constants (one for each scenario) you can use the [`ConstantScenarioParameter`](https://pywr.github.io/pywr-docs/master/api/generated/pywr.parameters.ConstantScenarioParameter.html#pywr.parameters.ConstantScenarioParameter) if they are different timeseries then the [`DataframeParameter`](https://pywr.github.io/pywr-docs/master/api/generated/pywr.parameters.DataFrameParameter.html#pywr.parameters.DataFrameParameter) supports providing a different timeseries per scenario. For each you have to provide "scenario" key in the JSON and a compatible dataset with the correct number of values or timeseries equal to the size of the scenario. 

Here's one of the test models that uses `ConstantScenarioParameter`: https://github.com/pywr/pywr/blob/master/tests/models/simple_with_scenario.json

**Comment by MohammedBasheer** [comment]
Thanks, @jetuk. I had a look at the ConstantScenarioParamter. It exactly solves my problem.
