### ISSUE TITLE
Should we remove the inspyred wrapper?

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#871]
Reasons:

1. It's broken (see #459 and discussion in #869) - basically objective direction and constraints don't work.
2. Upstream is pretty quiet. Only 3 minor commits in the last ~3 years.
3. No-one I know uses it.

@Batch21 @matrosoe any thoughts?

**Comment by Batch21** [comment]
I've never really used it, so don't mind if its removed. Doesn't seem worth the effort to update the wrapper, especially if the project is pretty quiet.
