### ISSUE TITLE
New Constraints implementation `unexpected keyword argument 'value'`

### ISSUE THREAD

**Issue by Jmiguel17** [pywr/pywr#876]
Hi @jetuk I was testing the new constraints implementation in platypus but I got this error. 

```
 File "c:\users\n65847jg.ds\dropbox (the university of manchester)\doctorado\pywr\pywr\optimisation\platypus.py", line 90, in _make_constraints
    self.problem.constraints[ic] = platypus.Constraint('<=', value=c.constraint_upper_bounds)
TypeError: __init__() got an unexpected keyword argument 'value'
```
I was using the `PyretoJSONPlatypusWrapper` class but I don't know if I have to modify this class to use the new implementation. However, according to my understanding of this class, it is not necessary any change.

Thanks

**Comment by jetuk** [comment]
What version of `platypus` are you using?

**Comment by Jmiguel17** [comment]
Hi 
```
>>> import platypus
>>> platypus.__version__
'1.0.1'
```

**Comment by jetuk** [comment]
Try updating it. The latest is 1.0.4 I think.

**Comment by Jmiguel17** [comment]
:+1:
Thanks! now is working...
I am going to close this issue
