### ISSUE TITLE
Read the internal variables from one class in another class

### ISSUE THREAD

**Issue by NedumEluwa** [pywr/pywr#909]
Hi, 

I am new to using PyWR. I have a hydrologic model (parameter class) which I instance as a parameter from a catchment node. I want to also read the evaporation from the hydrologic model from another parameter class (in an irrigation output node for example to be used to compute farmer benefits for instance). 

However, the value function of the hydrologic model class only permits the return of one real number. 

Is there a way for me to read the evaporation from the hydrologic model parameter class (called from the catchment node) from a separate parameter class (called from the output node).

In my model .json file I have this for the catchment:
`    {
      "name": "catchment_1",
      "type": "catchment",
      "comment": "catchment",
      "flow": "flow_catchment_1"
    },`
and this for the et output node:
`    {
      "name": "catchment_et_out",
      "type": "output",
      "min_flow":  "et_output",
      "max_flow": "et_output"
    },`

I have a parameter `"flow_catchment_1"` which successfully runs the hydrologic model class in each timestep and returns the runoff. I have another parameter `"et_output" `that I want to read the evaporation (or in general, other state variables) from the hydrologic model class. How may I achieve this using PyWR? 

Thank you.

**Comment by jetuk** [comment]
I think there are a couple of ways to structure this. One is to have the class you have now, containing the hydrologic model, but have it return no value (or zero). Its job is to simple control or provide access to the hydrologic model. Then create two "shim" parameters that get a reference to the hydrologic parameter. One provides the flow, the other provides the evaporation. These can then be used in the appropriate place in your Pywr model.

Something like this:

```python

class MyHydrologicalModelWrapperParameter(Parameter):
    def __init__(self, model, hydrological_model, *args, **kwargs):
        self.hydrological_model = hydrological_model

    def setup(self):
        self.hydrological_model.initialise()  # Perform any initialisation of the hydrological model

    def reset(self):
        self.hydrological_model.reset()  # Reset the hydrological model to initial conditions

    def before(self):
        self.hydrological_model.step()  # Step forward the hydrological model by one time-step.

    def value(self, ts, si):
        # This parameter returns zero and should not be used directly; it's main purpose is to wrap 
        # the hydrological model.
        return 0.0

class MyHydrologicalModelFlowParameter(Parameter):
    def __init__(self, model, hydrological_model_parameter, *args, **kwargs):
        self.hydrological_model_parameter = hydrological_model_parameter
        self.parents.add(hydrological_model_parameter)  # Make sure to do this so that the model is updated before this parameter.

    def value(self, ts, si):
        return self.hydrological_model_parameter.get_flow(...)

class MyHydrologicalModelEvaporationParameter(Parameter):
    def __init__(self, model, hydrological_model_parameter, *args, **kwargs):
        self.hydrological_model_parameter = hydrological_model_parameter
        self.parents.add(hydrological_model_parameter)  # Make sure to do this so that the model is updated before this parameter.

    def value(self, ts, si):
        return self.hydrological_model_parameter.get_evaporation(...)
```

This could be made more sophisticated:
 - Have a shared base class for the two shim parameters (their `__init__` methods are identical here).
 - Pass some additional information to `__init__`. For example, if the hydrological model is 2D about which grid cell to return flow from, or to perform a unit conversion.
 - Implement `.load()` which is needed to create these from JSON.

**Comment by NedumEluwa** [comment]
thank you so much @jetuk I will try this and give you feedback

**Comment by NedumEluwa** [comment]
THANK YOU SO MUCH @jetuk ...

I have successfully implemented this method of calling different state variables. Now, I do not have to write out state files each timestep as I did before. 

``` python
   def get_state_variable(self, timestep, scenario_index, val="flow"):
         """This function will call the run_model function in the current timestep and return either flow or et"""
        flow, et = self.run_model(timestep, scenario_index)
        if val == "flow":
            return flow
        elif val == 'et':
            # ET is returned in cubic meters per day
            # convert to cubic meters per second
            return et/(24*3600)
        else:
            print("ERROR: PLEASE ENTER either et or flow to return")
            return None
```


However, the model is run for each time the `get_state_variable` function is called. Is there some way, we can expose the `run_model` return values within the larger class such that it can be called just once, and then we can just read both states? (**this is low priority anyway, but any help is much appreciated**). Thank you.

**Comment by jetuk** [comment]
You could put the call to `self.run_model` in a the `reset()` method of the wrapper parameter. 

```python
    def reset(self):  # This is only called once per simulation.
        self.flow, self.et = self.run_model()

    def get_state_variable(self, timestep, scenario_index, val="flow"):
         """This function will call the run_model function in the current timestep and return either flow or et"""

        if val == "flow":
            return self.flow
        elif val == 'et':
            # ET is returned in cubic meters per day
            # convert to cubic meters per second
            return self.et/(24*3600)
        else:
            print("ERROR: PLEASE ENTER either et or flow to return")
            return None
```

My only query is whether `flow` and `et` are timeseries here?

> ET is returned in cubic meters per day
> convert to cubic meters per second

Note that Pywr uses vol per day as its unit. You probably don't want to do this conversion.

**Comment by NedumEluwa** [comment]
The `flow` and `et` are floating-point numbers. They are returned each timestep, and after a full model run, we can see the timeseries. 

The hydrologic model returns the `flow` in cubic meters per second, so I wanted to convert the `et` to the same units. From your suggestion, I should convert the `flow` to cubic meters per day instead. Thank you so much.

**Comment by jetuk** [comment]
@NedumEluwa has this resolved your issue?

**Comment by PYmeas** [comment]
Hello new to pymeasure for live plotting data. I am trying to call a variable mode ( can take either 2 or 4 ) declared in RandomProcedure class. i want to use it into the MainWindow class in the queue function so that i can have the mode into my file name. i did call the first class into the second but the mode remains stuck to 2 even if i type in 4 in the GUI. I implemented this for 2 or 4 wires measurement using a Keithley 2400 it does change the wire mode on the instrument but same the mode doesnt go through the file name. here i use fake data to test. any input welcome. Thanks
``` ruby
import logging
log = logging.getLogger(__name__)
log.addHandler(logging.NullHandler())

import sys
import tempfile
from tempfile import NamedTemporaryFile
import random
import datetime
from datetime import datetime as dt, timedelta
import time
from time import sleep
import pandas as pd
from pymeasure.log import console_log
from pymeasure.display.Qt import QtGui
from pymeasure.display.windows import ManagedWindow
from pymeasure.experiment import Procedure, Results
from pymeasure.experiment import IntegerParameter, FloatParameter, Parameter

class RandomProcedure(Procedure):
    iterations = IntegerParameter('Loop Iterations')
    delay = FloatParameter('Delay Time', units='s', default=0.2)
    seed = Parameter('Random Seed', default='20')
    mode = IntegerParameter('2 or 4 probes measurement', default=2)

    DATA_COLUMNS = ['Iteration', 'Timecode', 'Elapsed', 'Random Number']

    def startup(self):
        log.info("Setting the time of the random number generator")
        random.seed(self.seed)
        self.mode

    def execute(self):
        log.info("Starting the loop of %d iterations" % self.iterations)
        start = datetime.datetime.now()
        for i in range(self.iterations):
            timecode = dt.now()
            elapsed = (datetime.datetime.now() - start).total_seconds()
            data = {
                'Iteration': i,
                'Timecode': timecode,
                'Elapsed': elapsed,
                'Random Number': random.randint(1, 100)
            }
            self.emit('results', data)
            log.debug("Emitting results: %s" % data)
            sleep(self.delay)
            if self.should_stop():
                log.warning("Caught the stop flag in the procedure")
                break

class MainWindow(ManagedWindow, RandomProcedure):

    def __init__(self):
        super(MainWindow, self).__init__(
            procedure_class=RandomProcedure,
            inputs=['iterations', 'delay', 'seed', 'mode'],
            displays=['iterations', 'delay', 'seed', 'mode'],
            x_axis='Iteration',
            y_axis='Random Number',
            sequencer=True,  # Added line
            sequencer_inputs=['iterations', 'delay', 'seed', 'mode'],  # Added line
            # sequence_file="gui_sequencer_example_sequence.txt",  # Added line, optional
        )
        self.setWindowTitle('GUI Example')
        self.count = 0

    def queue(self, *, procedure=None):
        self.count = self.count + 1
        mode = self.mode
        filename = 'D:\\test\\' + str(dt.now().strftime("%m%d%Y"))+'_' + 'mode' +str(mode) + '_' + str(self.count) + '.csv'
        log.info("Constructing the Results with a data file: %s" % filename)
        if procedure is None:
            procedure = self.make_procedure()
        results = Results(procedure, filename)
        experiment = self.new_experiment(results)
        self.manager.queue(experiment)

if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
'''

**Comment by jetuk** [comment]
@PYmeas have you posted this in the wrong repository? It appears to be a question about pymeasure, not Pywr.

**Comment by PYmeas** [comment]
actually, t i thought it s a general class variable issue . I ll move to another repository sorry about that.

**Comment by jetuk** [comment]
For general help, support & advice in Python I suggest asking a question on a forum like https://stackoverflow.com/

**Comment by jetuk** [comment]
I assume this is solved. Please re-open or open a new issue if there is a remaining query.
