### ISSUE TITLE
Add a lumped parameter groundwater model

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#91]
Represent groundwater as a type of `Storage` that simulates groundwater level and possible steam flow. See this Keating (1981) reference for an approach: http://info.ngwa.org/gwol/pdf/822013336.PDF

**Comment by jetuk** [comment]
I started writing this today. I think it is going to require:

- A `Storage` object to represent the aquifer with a volume-level relationship.
- A `Parameter` to calculate the flow out of the aquifer based on its current level.

**Comment by snorfalorpagus** [comment]
I want to modify `KeatingAquifer` so that you can easily create an aquifer with more than one stream outflow. Presumably you have no objections? You'll need to update your code.

**Comment by jetuk** [comment]
You also modified the flow/transmissivity calculation code?

**Comment by snorfalorpagus** [comment]
> You also modified the flow/transmissivity calculation code?

Yes. The transmissivity is now linked to the stream flow level, i.e. each stream flow level has a corresponding transmissivity. The previous code linked it to the water level/volume so that transmissivity could vary with level. It wasn't done correctly though.

**Comment by jetuk** [comment]
But shouldn't it be linked to the water level? I.e. it's a parameter of the aquifer and not the stream.

**Comment by snorfalorpagus** [comment]
I think that there are two things remaining for this:

 - Option to set the initial volume by passing an initial level
 - Some actual tests

**Comment by jetuk** [comment]
Sorry I missed this and opened the #128.

The current tests need fixing first.

Won't passing an initial level require the level parameter to do a reverse calculation?

**Comment by jetuk** [comment]
Closed by #128 merge.
