### ISSUE TITLE
New aggregate time series recorder

### ISSUE THREAD

**Issue by matrosoe** [pywr/pywr#910]
Howdy!

I am trying to put in a new recorder that sums up the time series (dataframes) eg, reservoir storage at every time step. This would produce an aggreagate sum of the time series at every time step, rather than a statistic of the time series itself (sum, mean, percentile etc... 

Currently I have this coded in:

```
class AggregateNumpyArrayRecorder(NumpyArrayStorageRecorder):
    #Add load method
    def __init__(self, model, **kwargs):

        super().__init__(model, **kwargs)
        self.recorders = list(recorders)

        for rec in self.recorders:
            self.children.add(rec)
            
    
    def to_dataframe(self):
        reservoirs={}
        for recorder in self.recorders:
            reservoir[recorder]=super().to_dataframe()
        print(reservoirs)
        #Aggregation happens here, coming soon....
    
    @classmethod
    def load(cls, model, data):
        recorder_names = data.pop("recorders")
        recorders = [load_recorder(model, name) for name in recorder_names]
        print(recorders)
        rec = cls(model, recorders, **data)
        return rec        

AggregateNumpyArrayRecorder.register() 
```

and am applying this to the two_reservoir example model by adding these recorders:
'''
        "res1storage": {
            "type": "NumpyArrayStorageRecorder",
            "node": "reservoir1"

        },
        "res2storage": {
            "type": "NumpyArrayStorageRecorder",
            "node": "reservoir2"
        },	
        "totalreservoir": {
            "type": "AggregateNumpyArrayRecorder",
            "recorders": ["res1storage", "res2storage"]
        }

```
This this the correct way to do this?

I'm currently getting this error upon running
```
in pywr.recorders._recorders.load_recorder()

<ipython-input-122-a715f53c8919> in load(cls, model, data)
     22         recorders = [load_recorder(model, name) for name in recorder_names]
     23         print(recorders)
---> 24         rec = cls(model, recorders, **data)
     25         return rec
     26 

TypeError: __init__() takes 2 positional arguments but 3 were given

```

**Comment by jetuk** [comment]
In this particular case you could also use an `AggregatedStorage` to have the combined total in the simulation (for control, etc). Then use the regular storage recorders on that node.

You are missing a second argument to `__init__`. I think it should be `recorders` based on the rest of the method:

```python

class AggregateNumpyArrayRecorder(NumpyArrayStorageRecorder):
    #Add load method
    def __init__(self, model, recorders, **kwargs):  # << Missing recorders argument here
        super().__init__(model, **kwargs)
        self.recorders = list(recorders)

        for rec in self.recorders:
            self.children.add(rec)
            
    
    def to_dataframe(self):
        reservoirs={}
        for recorder in self.recorders:
            reservoir[recorder]=super().to_dataframe()
        print(reservoirs)
        #Aggregation happens here, coming soon....
    
    @classmethod
    def load(cls, model, data):
        recorder_names = data.pop("recorders")
        recorders = [load_recorder(model, name) for name in recorder_names]
        print(recorders)
        rec = cls(model, recorders, **data)
        return rec        


```

**Comment by matrosoe** [comment]
I think the storage node is indeed the way to go,
thanks
