### ISSUE TITLE
Error if ConstantParameter value is loaded from DataFrame column containing mixed dtypes

### ISSUE THREAD

**Issue by Batch21** [pywr/pywr#914]
Error looks like this:
```
pywr\_model.pyx:402: in pywr._model.Model.load.load_components
    component = load_component(model, component_data, name)
pywr\parameters\_parameters.pyx:2075: in pywr.parameters._parameters.load_parameter
    parameter = cls.load(model, kwargs)
pywr\parameters\_parameters.pyx:174: in pywr.parameters._parameters.ConstantParameter.load
    value = load_parameter_values(model, data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   values = np.squeeze(values.astype(np.float64))
E   AttributeError: 'str' object has no attribute 'astype'
```
The issue is that the `load_parameter_values` function assumes the value returned from the Dataframe will be a numpy type, which it won't be if its from a column of mixed data types. 

Simplest fix is probably something like:

```python
if isinstance(values, (str, int, float)):
    values = np.array(np.float64(values))
else:
    values = np.squeeze(values.astype(np.float64))
```

**Comment by jetuk** [comment]
> if its from a column of mixed data types

Fix the data?

**Comment by Ryan-Davies** [comment]
That's what we're already planning on doing, it's just whether this is an issue worth fixing in Pywr as well

**Comment by jetuk** [comment]
May initial reaction is that there is no good fix to do in Pywr. Arbitrary strings can't be converted to floats. It's usually an indication of something wrong with the data in my experience and the user should be made aware of it.

**Comment by Batch21** [comment]
I agree about string conversions but if the data is loaded from an .xlsx, then a column of mixed dtypes might return a float or int value which causes the same error. Should pywr convert these values or do you think this is still an instance where the input data should be modified to be a single dtype?

**Comment by jetuk** [comment]
> a column of mixed dtypes might return a float or int value which causes the same error.

I'm surprised `.astype()` wouldn't work in this case?

**Comment by jetuk** [comment]
Also as Pywr's loader is just a wrapper for `pandas.read_excel` you can pass additional type conversion keyword arguments that might help. See `dtype` and `converters`: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html

**Comment by Batch21** [comment]
> Also as Pywr's loader is just a wrapper for pandas.read_excel you can pass additional type conversion keyword arguments that might help. See dtype and converters: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html

Thanks, I didn't think of that option. I'll close this issue
