### ISSUE TITLE
Create Windows binary

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#92]
Create and make available a Windows binary for ease of installation.

**Comment by snorfalorpagus** [comment]
Should we compile GLPK ourselves, or just use the binary provided? http://winglpk.sourceforge.net/#download

Are we going to include lpsolve?

**Comment by jetuk** [comment]
Yes and No? I've not benchmarked the two.

**Comment by snorfalorpagus** [comment]
Started working on anaconda build here:

https://anaconda.org/snorfalorpagus/pywr/files

Still need to do:

- [ ] Move GLPK dependency into it's own conda package
- [ ] Tag builds against a specific numpy version

Target 64-bit, Python 2.7, 3.4 and 3.5.

**Comment by snorfalorpagus** [comment]
This is working now (for 2.7 and 3.4 only - I've not installed VSE2015).

First, install glpk:
```
conda install -c https://conda.anaconda.org/snorfalorpagus glpk
```

Then install pywr:
```
conda install -c https://conda.anaconda.org/snorfalorpagus pywr
```

Alternatively, add the channel to your `.condarc` file (see documentation) and do:
```
conda install pywr
```

**Comment by snorfalorpagus** [comment]
Should the build script for conda be included in the pywr repository? What about it's dependencies (glpk)?

**Comment by jetuk** [comment]
Where else would you put it?
