### ISSUE TITLE
Add a demand node based on SPI or SPEI

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#94]
Standardised Precipitation Index (SPI) is a drought (or dryness) measure that could be computed on the fly to alter demand depending on prevailing weather. Standardised Precipitation-Evapotranspiration Index (SPEI) is an improvement on SPI to include temperature (PET) in the calculation. 

These indices produce positive number when wet and negative when dry - see Table 1. in the WMO reference. For example a value less than -2.0 is "extremely dry". A funciton mapping these indices to demand would be relatively easy to write. However there would be several methods/options for doing this.

References,
- http://www.wamis.org/agm/pubs/SPI/WMO_1090_EN.pdf
- http://sac.csic.es/spei/home.html

**Comment by snorfalorpagus** [comment]
We've been doing this for groundwater DO by calculating the values externally and including them as a dataframe (or similar). I think it's best done like that, rather than trying to include it as a parameter.

**Comment by jetuk** [comment]
Depends if you want to be able to easily explore some of the uncertainty with the relationship between these indices and demand/DO with pywr.
