### ISSUE TITLE
Migrate to Github Actions

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr#944]
Travis' free tier has been removed:

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

We'll run out of our free credits soon if we haven't already. I suggest we move to Github Actions for both Linux and Windows - possibly re-add OSX. We can also start doing the pypi builds and deployment directly from the actions.

**Comment by snorfalorpagus** [comment]
I'm :+1: on doing builds and deployments via the CI.

**Comment by jetuk** [comment]
Maybe use this: https://github.com/joerick/cibuildwheel

**Comment by jetuk** [comment]
The majority of this was done in #948.

Remaining todos:

- [ ] OSX builds
- [ ] Coverage build
- [ ] Pypi upload

**Comment by jetuk** [comment]
Pypi upload is now done.

**Comment by jetuk** [comment]
Closing this as complete.
