### ISSUE TITLE
Using today's flow from a node in calculations

### ISSUE THREAD

**Issue by VJander** [pywr/pywr#949]
The `FlowParameter` is set to read the flow from the previous timestep, however, is there any way to read the flow from the current time step in order to include it in calculations? The reason behind this request is to set the maximum release flow of a reservoir as a function of the storage at the beggining of the timestep (something a simple `controlcurve` or `storagethreshold` can make) and the input flow to the storage in the same timestep.

**Comment by jetuk** [comment]
@VJander unfortunately this is not possible because the current flow is calculated via the linear programme. You either use the previous flow and a small time-step to ensure convergence is not too bad, or you have to embed your rule in to the linear programme using aggregated nodes and constraints.
