### ISSUE TITLE
Warning when setting reservoir volume

### ISSUE THREAD

**Issue by snorfalorpagus** [pywr/pywr#99]
Can we fix this? Rename the parameter to `initial_volume` and remove the warning?

```
C:\Miniconda3\envs\python34\lib\site-packages\pywr\core.py:916: UserWarning: Set
ting volume property directly is not supported. This method is updating the init
ial storage volume.
  self.volume = volume
```

**Comment by jetuk** [comment]
`Storage.initial_volume` already exists. This is purely there for legacy purposes. Delete it if you like, but only the `__set__` part of the property. If you think users might want to update the current volume then change it to set `Storage._volume` instead.
