### ISSUE TITLE
NumpyArrayNodeSuppliedRatioRecorder gives a divide by zero error

### ISSUE THREAD

**Issue by andrew-slaughter** [pywr/pywr#991]
I think this relates to the line below (line 727 in _recorders.pyx:
self._data[ts.index,scenario_index.global_id] = node._flow[scenario_index.global_id] / max_flow

There is no check on whether max_flow is zero before the operation.

**Comment by jetuk** [comment]
Thanks for this. I'm not sure what the correct output should be here. We could tell it to do C style division, but that would just result in a NaN.

**Comment by matrosoe** [comment]
In practice this is usually used as a proxy to quantify a deficit and when the demand is 0, there isn't a deficit. I appreciate that this isn't as eloquent but something like this captures this idea:

```
    cpdef after(self):
        cdef double max_flow
        cdef ScenarioIndex scenario_index
        cdef Timestep ts = self.model.timestepper.current
        cdef Node node = self._node
        for scenario_index in self.model.scenarios.combinations:
            max_flow = node.get_max_flow(scenario_index)
            if max_flow > 0:
                self._data[ts.index,scenario_index.global_id] = node._flow[scenario_index.global_id] / max_flow
            else:
                self._data[ts.index,scenario_index.global_id] = 1 
                
        return 0
```

**Comment by matrosoe** [comment]
I had implemented this idea in my local pywr and now made it into a branch:

https://github.com/pywr/pywr/tree/supply_ratio_0_max_flow

**Comment by jetuk** [comment]
> In practice this is usually used as a proxy to quantify a deficit and when the demand is 0, there isn't a deficit

I agree with this. We should document the behaviour in the docstring, and probably add a test for it.
