### ISSUE TITLE
AggregatedParameter.remove() raises AttributeError exception

### ISSUE THREAD

**Issue by s-simoncelli** [pywr/pywr#996]
The remove method in the AggregatedParameter class does not work as expected. This line
https://github.com/pywr/pywr/blob/c76332e7aa6ced6aac2e041697759fa1422eac19/pywr/parameters/_parameters.pyx#L1474

should read
    `parameter.parents.remove(self)`

The same applies to:
https://github.com/pywr/pywr/blob/b861fdf39d52631aed935870b9bed92d2887897d/pywr/parameters/_parameters.pyx#L1551

**Comment by jetuk** [comment]
@s-simoncelli thanks for spotting this. I'll review your PR ASAP (#997 )

**Comment by jetuk** [comment]
Fixed in #997
